### ISSUE TITLE
Reach "project readme"

### ISSUE THREAD

**Issue by vint66** [GNS3/gns3-gui#2857] opened 2019-09-21 20:25 UTC
GNS3 v2.2.0rc5

"Project readme" needs to be improved to support RTF or HTML + builtin editor.

**Comment by grossmj** [comment] 2019-09-27 08:39
Markdown would be better I think: https://github.com/GNS3/gns3-gui/issues/2550

**Comment by vint66** [comment] 2019-09-27 15:51
Yes, markdown should be good.
Thank you for looking into this, Jeremy.

**Comment by grossmj** [comment] 2020-07-12 11:02
Duplicate of https://github.com/GNS3/gns3-gui/issues/2550

**Closed by grossmj** 2020-07-12 11:02 UTC
Labels: Duplicate, Enhancement
