### ISSUE TITLE
Connect to projects

### ISSUE THREAD

**Issue by Ztaguassi** [GNS3/gns3-gui#1706] opened 2016-12-08 13:44 UTC
I really like if I can connect projects.

I have some project like "Internet" "Client A" Client B" "Office".

The project "Internet" it's a minimized internet with routers, BGP, ISP, etc.

I like to connect the project "Client A" to a router from project "Internet" so I can work with different project for every client and no need to recreate the "Internet" inside this project when needed to simulate internet traffic/routing.

**Comment by noplay** [comment] 2016-12-08 14:38
Thanks for the suggestion it's a duplicate of:
https://github.com/GNS3/gns3-server/issues/517

I just clarify the issue and why it's not possible

**Closed by noplay** 2016-12-08 14:38 UTC
Labels: duplicate
