### ISSUE TITLE
In the doctor dialog warn if user run GNS3 as root

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#939] opened 2016-01-19 17:31 UTC

**Comment by ehlers** [comment] 2016-01-19 18:19
Probably duplicate of https://github.com/GNS3/gns3-gui/issues/608, please see my comments

**Comment by grossmj** [comment] 2016-01-25 22:00
I agree, this should be covered by a more general warning when launching GNS3.

**Closed by grossmj** 2016-01-25 22:00 UTC
Labels: enhancement
