### ISSUE TITLE
[2.0] error message when create IOL bridge

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1651] opened 2016-11-10 18:59 UTC
Hi

When i want to start IOU switch connected to vpcs, i have this error message :
`could not create IOL bridge 'IOL-BRIDGE-513': could not get lock on /tmp/netio1000/513`

Sorry, i don't know where to investigate to give you more details

[gns3_server.log.txt](https://github.com/GNS3/gns3-gui/files/584167/gns3_server.log.txt)

**Comment by grossmj** [comment] 2016-11-10 23:39
Do you reproduce the issue everytime?

**Comment by noplay** [comment] 2016-11-11 09:56
I have reproduce it. It seem the problem is hotlink.

![capture d ecran 2016-11-11 a 10 55 27](https://cloud.githubusercontent.com/assets/345437/20211126/61cee32c-a7fd-11e6-9de5-4fc08ebda954.png)

**Comment by Raizo62** [comment] 2016-11-11 10:18
Super, you can reproduce. 
Sorry for the delay : I created a new config of GNS3. I supposed that perhaps this bug came of adapted config of GNS3 v1.5. But no.

I have the bug one time. When  i restart GNS3, i don't have the bug.
I must restart my Live to have the bug.

**Comment by noplay** [comment] 2016-11-11 10:23
Yeah the problem seem more complex. I didn't reproduce it at my second test

**Comment by noplay** [comment] 2016-11-11 14:17
I think I fix the bug. A race condition when recreating the network.

Thanks a lot for the report

**Comment by noplay** [comment] 2016-11-11 15:52
I found the real issue. It's an ubridge bug the directory /tmp/netio is not created by ubridge. I'm fixing that.

**Comment by noplay** [comment] 2016-11-11 16:22
Fixed by a ubridge update (0.9.7)

**Closed by noplay** 2016-11-11 16:22 UTC
Labels: bug
