### ISSUE TITLE
GNS3 v1.4.2 doesn't close down the VM Client since upgrade on OSX

### ISSUE THREAD

**Issue by uktricky** [GNS3/gns3-gui#1056] opened 2016-02-19 13:43 UTC
As per title.

When I exited v1.4.1 it would close down he VM guest in VM Fusion since upgrade this feature no longer applies and the guest needs to be closed down manually.

R

**Comment by noplay** [comment] 2016-02-19 14:18
Hi,

Thanks for the report it's a duplicate of:
https://github.com/GNS3/gns3-server/issues/432

**Closed by noplay** 2016-02-19 14:18 UTC
Labels: bug, duplicate
