### ISSUE TITLE
1.5 : crash when cancel first config

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1347] opened 2016-07-02 10:10 UTC
Hi

On Linux with GNS3 1.5.1.dev1

I delete config of GNS3

I start gns3.
Into the wizard, i click on cancel.

GNS3 crash and gns3server continues to run

**Comment by noplay** [comment] 2016-07-04 09:01
I can't reproduce it on my Mac will try with a Linux box.

Can you start it with --debug and give us the traceback?

Thanks

**Comment by Raizo62** [comment] 2016-07-04 15:41
Finally, it is more complicated to do the crash.

I am connected on remote VM with MobaXterm ("ssh" with server X integrated)

gns3 is started on remote VM with using MobaXterm

And when i cancel, i have the segmentation error

[gns3.debug.txt](https://github.com/GNS3/gns3-gui/files/346567/gns3.debug.txt)

**Comment by noplay** [comment] 2016-07-04 16:21
Sound like a crash in Qt wich version of Qt are you using? You can see the version in the console at the bottom. 

I know that Qt has fixed lot of issues with remote display.

**Comment by noplay** [comment] 2016-07-04 16:21
Not reproduced with an ubuntu Xenial box.

**Comment by Raizo62** [comment] 2016-07-04 17:15
Python 3.4.2
Qt 5.3.2.

**Comment by noplay** [comment] 2016-07-04 17:33
The remote is headless? Perhaps it's related to:
https://bugreports.qt.io/browse/QTBUG-42985

**Comment by Raizo62** [comment] 2016-07-04 17:48
I don't know but X is started on the remote.
But the bug is not "important" if it is in QT, and only when we cancel the first configuration with remote X connection....

**Comment by noplay** [comment] 2016-07-05 08:01
I close it because we can't replicate so we can't easily fix it. I'm pretty sure it's somewhere in Qt/PyQt.

**Comment by noplay** [comment] 2016-07-05 08:01
Thanks for the report

**Closed by noplay** 2016-07-05 08:01 UTC
Labels: bug
