### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#208] opened 2015-03-15 21:53 UTC
https://app.getsentry.com/gns3/gns3-gui/group/57114554/

**Comment by noplay** [comment] 2015-03-16 21:23
Duplicate of #207  it's the same issue

**Comment by noplay** [comment] 2015-03-16 21:45
I add assert in the code in order to clarify the error in the future, I didn't found the issue.

**Closed** 2015-03-23 19:17 UTC
Labels: bug
