### ISSUE TITLE
REQ - Delete Projects from VM

### ISSUE THREAD

**Issue by uktricky** [GNS3/gns3-gui#1064] opened 2016-02-19 22:25 UTC
I have a number of "test" projects that I create when testing new versions of IOS/IOU and GNS3 releases that I know I am not going to reuse.  

So ideally a way to "delete" projects from Browser 
* Using the browser connectivity <IP>:8000:
* List all the projects with the "real name" and the Project ID
* Be able to highlight one to delete when cleaning up

Or
 
Potentially open the Project in GNS3 and then from the Tools menu have a "TRASH Project" option.  Would have confirmation options but then it would - perhaps with check boxes to confirm each of:
* Remove the files from the VM
* Remove the files from the Local Project Directory
* Extract "startup-config" and save locally against devices? Only if not deleting local directory?

**Comment by noplay** [comment] 2016-02-22 08:04
Jeremy it could be done via the controller and a web interface on the project api when we will have it.

**Comment by ehlers** [comment] 2016-02-22 08:39
Duplicate of https://github.com/GNS3/gns3-gui/issues/822?

**Comment by noplay** [comment] 2016-02-22 09:06
Yes duplicate

**Closed by noplay** 2016-02-22 09:06 UTC
Labels: duplicate, enhancement
