### ISSUE TITLE
Can not ping between IOU

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#1566] opened 2016-10-07 03:17 UTC
GNS3 2.0.0 alpha 1 and latest GNS3 VM with all latest updates via GNS3 VM interface.  Also used pip3 to be sure I had gns3-server and gns3-gui for version 2.0.0a1

Windows 10 Prof 64 bit latest update, VMWare workstation 12.  
Installed GNS3 but can only get IOS to function properly via local server (127.0.0.1) 
In GNS3 1.5.1 can run IOS, IOU, IOSXR, ASAv, etc. all from GNS3 VM
It seem the configuration specifics immediately post install have changed a bit.  Any chance of a detailed "How To" on www.gns3.com?

Been a while and it shows!  Thanks!

**Comment by noplay** [comment] 2016-10-07 06:42
Their is no real UI change should work like before. What is the issue only IOS work on GNS3 VM?

**Comment by jtorri** [comment] 2016-10-12 02:59
Using latest (as of several days ago) GNS3 VM I downloaded with GNS3 2.0.0 alpha 1 to run IOU.  Two IOUs cannot communicate, e.g., ping each other.  This does work in GNS3 1.5.1.  Two IOSs run from "local server" can communicate with each other.  Am I the only one seeing this?  Is is specific to running GNS3 2.0.0 alpha 1 on Windows?

**Comment by jtorri** [comment] 2016-10-15 00:48
Well, I am not helping.  Posting about this issue here and on gns3.com.  Will limit my possible bug post to here as I believe was requested a while back.

VMWare workstation 12 initially, now 12.5. Used the GNS3VM.ova file downloaded with GNS3 2.0.0 alpha 1 to "create" the GNS3 VM. Added a third NIC to the GNS3VM for bridged interface to local network.

eth0 192.168.41.0/24 (vmnet1 host only), eth1 192.168.110.0/24 (NAT), eth2 192.168.254.0/24 (vmnet0, bridged to local NIC). From the GNS3 VM can ping local network and internet, e.g., 8.8.8.8 but two IOU L3 objects as part of a project running on the GNS3VM cannot ping each other.

The specific IP of eth0 is 192.168.41.129/24.  When GNS3 2.0.0 installs it assigns the address of 127.0.0.1 to server preferences/main server/host binding.  Server preferences/remote server has no value assigned.  GNS3 Preferences are Enable the GNS3 VM/VM Name is the VMWare virtual machine created with the GNS3VM.ova.  When GNS3 2.0.0 starts the correct GNS3VM is started as well.

These NIC addresses are the same values that currently work with GNS3 version 1.5.1  However in GNS3 1.5.1 the host value in server preferences is 192.168.41.1.

Thanks!

**Comment by jtorri** [comment] 2016-10-15 01:31
IOS objects, unlike IOU objects, run from GNS3 VM can communicate with each other.

**Comment by noplay** [comment] 2016-10-16 19:48
OK I suspect we choose the wrong ip to bind the communication of a side of the communication. Thanks a lot for the details it's a give a lot of informations.

**Comment by noplay** [comment] 2016-10-16 21:37
After some test it seem it's bug when you have serial adapters

**Comment by noplay** [comment] 2016-10-16 21:48
The problem is the order of interfaces.

# 1.5
![capture d ecran 2016-10-16 a 23 43 27](https://cloud.githubusercontent.com/assets/345437/19421185/0988ec78-93fb-11e6-98a3-92f4b05cf4cf.png)

# 2.0
![capture d ecran 2016-10-16 a 23 47 35](https://cloud.githubusercontent.com/assets/345437/19421186/0ff58792-93fb-11e6-986a-67ac96f2c4c3.png)

**Comment by noplay** [comment] 2016-10-16 22:07
Thanks the bug is fixed on dev will be include in alpha 2

**Comment by grossmj** [comment] 2016-10-16 22:08
Wanted to test today but you got there first :+1:

**Closed by noplay** 2016-10-16 22:07 UTC
Labels: bug

**Comment by jtorri** [comment] 2016-10-16 22:34
When I configure the IOU objects to have 0 serial interfaces they can, as you suggest, ping each other.  Fast work!  As always, many thanks!

**Comment by noplay** [comment] 2016-10-17 06:51
Thanks for the report it was a great help for us
