### ISSUE TITLE
upload iou via webpage show 500 error

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-gui#1450] opened 2016-08-28 12:17 UTC
i tested it on GNS3vm 1.5.2 and my Lubuntu.
when upload iou via web, it will show 500 error, so until now I can only use winscp.
the webbrower is chrome chinese version , and also tested firefox.

![1](https://cloud.githubusercontent.com/assets/9411604/18033604/37cc62b0-6d5c-11e6-9fda-53343a60b011.jpg)

![image](https://cloud.githubusercontent.com/assets/9411604/18033608/48fccc32-6d5c-11e6-9c63-0d7ace8a6eee.png)
(8000 port is I specific for lubuntu)

![image](https://cloud.githubusercontent.com/assets/9411604/18033700/385081ec-6d5e-11e6-99e6-db99093b4275.png)

by the way , how to delete the temp file from gns3vm which upload failed?

**Comment by noplay** [comment] 2016-08-29 07:25
Thanks,

It's  a duplicate of https://github.com/GNS3/gns3-server/issues/647

Could you test with the last server code? I just fixed it.

**Closed by noplay** 2016-08-29 07:25 UTC
Labels: duplicate

**Comment by noplay** [comment] 2016-08-29 07:33
Also @superwolfboy could send me an email to julien@gns3.net I want to ask you something but with a private channel .Thanks for all your help
