### ISSUE TITLE
v2.1.7 error using a qemu pfsense image

### ISSUE THREAD

**Issue by Coubiac** [GNS3/gns3-gui#2517] opened 2018-06-12 15:42 UTC
Hello :)

i'm trying to import pfsense an i got this error:

`Error while creating node: Bad request http://192.168.65.128:3080/v2/compute/projects {
    "message": "Invalid JSON: Additional properties are not allowed ('variables' was unexpected) in schema: {\"properties\": {\"name\": {\"description\": \"Project name\", \"minLength\": 1, \"type\": [\"string\", \"null\"]}, \"auto_close\": {\"description\": \"Project auto close\", \"type\": \"boolean\"}, \"path\": {\"description\": \"Project directory\", \"minLength\": 1, \"type\": [\"string\", \"null\"]}, \"project_id\": {\"description\": \"Project UUID\", \"pattern\": \"^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$\", \"minLength\": 36, \"maxLength\": 36, \"type\": [\"string\", \"null\"]}, \"snap_to_grid\": {\"type\": \"boolean\", \"description\": \"Snap to grid on the drawing area\"}, \"show_layers\": {\"type\": \"boolean\", \"description\": \"Show layers on the drawing area\"}, \"scene_height\": {\"type\": \"integer\", \"description\": \"Height of the drawing area\"}, \"show_grid\": {\"type\": \"boolean\", \"description\": \"Show the grid on the drawing area\"}, \"show_interface_labels\": {\"type\": \"boolean\", \"description\": \"Show interface labels on the drawing area\"}, \"scene_width\": {\"type\": \"integer\", \"description\": \"Width of the drawing area\"}, \"zoom\": {\"type\": \"integer\", \"description\": \"Zoom of the drawing area\"}}, \"$schema\": \"http://json-schema.org/draft-04/schema#\", \"required\": [\"name\"], \"type\": \"object\", \"description\": \"Request validation to create a new Project instance\", \"additionalProperties\": false}",
    "method": "POST",
    "path": "/v2/compute/projects",
    "request": {
        "name": "test",
        "project_id": "674be0f0-b07d-47e4-9f5c-fd8517e0f96f",
        "variables": null
    },
    "status": 400
}
`
is there something I'm not doing right?

**Comment by grossmj** [comment] 2018-06-13 07:49
Duplicate of https://github.com/GNS3/gns3-server/issues/1340

**Closed by grossmj** 2018-06-13 07:49 UTC
Labels: Bug

**Comment by ziajka** [comment] 2018-06-13 15:37
Hi @Coubiac, are you using GNS3-VM? or remote additional compute?
Thank you for your help,
Dominik
