### ISSUE TITLE
Can't import VirtualBox VM list when any VM contains non-ascii character

### ISSUE THREAD

**Issue by mcallisterjp** [GNS3/gns3-gui#1422] opened 2016-08-17 15:28 UTC
I tried to import a gns3 VirtualBox VM using the New VirtualBox VM template window in Edit>Preferences. I got the following error:

VirtualBox has returned an error: VBoxManage.exe: error: Could not find a registered machine named 'Aalheiur Clone'
VBoxManage.exe: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee IUnknown
VBoxManage.exe: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 737 of file VBoxManageMisc.cpp

and the resulting VM list was empty. I have a VM called "Aðalheiður Clone" (not the one I wanted to import into gns3), and this problem goes away when I rename it to an ascii-only name.

Fully reproduceable.

**Comment by noplay** [comment] 2016-08-17 16:29
Thanks

**Comment by noplay** [comment] 2016-08-17 16:32
Just tested on OSX and don't have the issue perhaps specific to windows

**Comment by cioby23** [comment] 2016-09-15 17:01
Just made a test by creating a VM with non-ascii characters in the name on Linux and Windows platforms.
In Linux it works fine but in Windows crashes so this is Windows related. Using VirtualBox 5.1.4

**Comment by noplay** [comment] 2016-09-15 17:15
Thanks

**Comment by grossmj** [comment] 2016-09-21 00:43
I can reproduce the issue on Windows with a VirtualBox VM named "Aðalheiður". Looks like it originates from https://github.com/GNS3/gns3-server/blob/master/gns3server/modules/virtualbox/__init__.py#L114

stdout_data contains b'"A\xf0alhei\xf0ur" {633299db-381a-4c68-8b70-74d44f35084a}\r\n' and I get the following exception if I remove errors='ignore'

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 2: invalid continuation byte
```

I don't understand why Python cannot decode this in UTF-8.... This is Python version is 3.5.1 (64-bit) with utf-8 encoding. Why in 2016 we still get those issues?!

**Comment by noplay** [comment] 2016-09-21 07:24
It doesn't utf-8 for me.

But latin1:
http://www.codetable.net/hex/f0

This will work:
```python
 b"\xf0".decode("latin1")
```

If I correctly remember xf0 in utf8 is used for multibyte characters.

**Comment by grossmj** [comment] 2017-05-12 03:26
Using "unicode-escape" seems to work well however I am afraid of possible side effects...

```
>>> b'"A\xf0alhei\xf0ur" {633299db-381a-4c68-8b70-74d44f35084a}\r\n'.decode("unicode-escape")
'"Aðalheiður" {633299db-381a-4c68-8b70-74d44f35084a}\r\n'
```

**Comment by noplay** [comment] 2017-05-12 06:41
I agree, this could introduce trouble :(

**Comment by grossmj** [comment] 2017-05-12 06:55
What should we do, try utf8 first and try unicode-escape if this fail?

**Comment by noplay** [comment] 2017-05-12 07:01
How to detect it's failed due to that?

Le ven. 12 mai 2017 à 08:55, Jeremy Grossmann <notifications@github.com> a
écrit :

**Comment by grossmj** [comment] 2017-05-12 07:03
With the UnicodeDecodeError exception.

**Comment by noplay** [comment] 2017-05-12 07:07
Oh right

**Comment by grossmj** [comment] 2017-05-12 10:30
I've created VirtualBox named "Aðalheiður" and I could import/use it in GNS3. I suspect there was a bug in  VirtualBox with the returned VM name which contained escaped Unicode characters. This must has been fixed in a recent version.

Please re-open if there is still an issue.

**Closed by grossmj** 2017-05-12 10:30 UTC
Labels: Bug
