### ISSUE TITLE
Topology Images (Pictures) Disappearing from Projects

### ISSUE THREAD

**Issue by cyberpunk2350** [GNS3/gns3-gui#2694] opened 2019-02-01 01:11 UTC
I am running the GNS3 client on Win10 and am using the GNS3 VM (VMware Workstation 12).
I have been using the default configuration with the VM install (all devices are run from the VM, projects are saved on the local GNS3 folder.)

The problem I'm having is that the images/pictures I have been adding to the topologies of my projects are disappearing after a few days. They are still referenced in the .gns3 files but the files are no longer in the project folders (~\GNS3\projects\project-files\images).
I think this started happening (or at least i started noticing) in version 2.1.11.

Operating System: Win10 / GNS3 VM 2.1.12
GNS3 Software Version: GNS3 2.1.12

Related:
https://github.com/GNS3/gns3-server/issues/1514
https://www.gns3.com/community/discussion/topology-images-pictures-disappe

**Comment by grossmj** [comment] 2019-02-16 07:22
I suspect the problem is around this line of code: https://github.com/GNS3/gns3-server/blob/2.1/gns3server/controller/project.py#L738

**Comment by grossmj** [comment] 2019-02-19 09:12
Duplicate of https://github.com/GNS3/gns3-server/issues/1514

**Closed by grossmj** 2019-02-19 09:12 UTC
Labels: Duplicate
