### ISSUE TITLE
Error launching Gns3-gui under windows 10

### ISSUE THREAD

**Issue by LaurentBEDIEF** [GNS3/gns3-gui#3214] opened 2021-08-05 12:30 UTC
Version 2.2.23

Gns3-gui dont want to start under windows.

In console there is a error message :

PS C:\Program Files\GNS3> .\gns3.exe
Traceback (most recent call last):
  File "C:\Python36-x64\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Python36-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "gns3-gui/gns3/main.py", line 40, in <module>
  File "./gns3-gui\gns3\utils\get_resource.py", line 21, in <module>
  File "C:\Python36-x64\lib\site-packages\pkg_resources\__init__.py", line 74, in <module>
  File "C:\Python36-x64\lib\site-packages\pkg_resources\extern\__init__.py", line 52, in create_module
  File "C:\Python36-x64\lib\site-packages\pkg_resources\extern\__init__.py", line 48, in load_module
ImportError: The 'appdirs' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
PS C:\Program Files\GNS3>

thanks.

**Comment by grossmj** [comment] 2021-08-05 12:44
@LaurentBEDIEF Do you have the same issue if you try v2.2.22?

**Comment by LaurentBEDIEF** [comment] 2021-08-05 12:57
Non Jeremy, la v2.2.22 fonctionne  /  No v2.2.22 version works fine .

**Comment by GalbanMayer** [comment] 2021-08-05 16:47
I have the same problem, and the Vers. 2.2.5-2.2.22 upadates smoothly

**Comment by bolbie** [comment] 2021-08-05 17:37
Same issue on 2.2.23.
When I'm trying to open an application only the command line shows up for a second. 
Via PS or CMD: same error log as above.

OS: Win 10 20H2 Build 19042.1110
GNS3 GUI: 2.2.23
GNS3 VM: Vmware WS 16.1.2

I had to roll back the version to 2.22 - works fine. (Always make backups!)

**Comment by code8102** [comment] 2021-08-05 17:52
Hello guys,
same issue with my fresh update, just after installaton instead of running GNS3  it's the windows underneath is displayed : 
https://user-images.githubusercontent.com/63795903/127736440-3857b973-d8e7-45e5-8506-36841250ca11.jpg

**Comment by LaurentBEDIEF** [comment] 2021-08-05 17:59
> Hello guys,
> same issue with my fresh update, just after installaton instead of running GNS3 it's the windows underneath is displayed :
> https://user-images.githubusercontent.com/63795903/127736440-3857b973-d8e7-45e5-8506-36841250ca11.jpg
> 
> Update from 2.2.22 to 2.2.23.
> Windows 10 latest version.

Exact , just the first time we launch gns3-gui

**Comment by mahaboob100** [comment] 2021-08-05 23:27
Same issue here after updating gns3 to version 2.2.23.

**Comment by grossmj** [comment] 2021-08-06 01:33
This was a building error, please re-download and things should work this time.

Thanks!

**Comment by mmic289** [comment] 2021-08-06 20:00
I am having the same issue as  LaurentBEDIEF, having just downloaded (8-6-21 20:00 UTC) the 2.2.23 build from https://gns3.com/software/download

**Comment by NickJongens** [comment] 2021-08-07 08:33
Hi @grossmj, I'm having the same problem even after you've closed this issue. 
Just run this 10 minutes before commenting!

PS C:\Program Files\GNS3> .\gns3.exe
Traceback (most recent call last):
  File "C:\Python36-x64\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Python36-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "gns3-gui/gns3/main.py", line 40, in <module>
  File "./gns3-gui\gns3\utils\get_resource.py", line 21, in <module>
  File "C:\Python36-x64\lib\site-packages\pkg_resources\__init__.py", line 74, in <module>
  File "C:\Python36-x64\lib\site-packages\pkg_resources\extern\__init__.py", line 52, in create_module
  File "C:\Python36-x64\lib\site-packages\pkg_resources\extern\__init__.py", line 48, in load_module
ImportError: The 'appdirs' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
PS C:\Program Files\GNS3>

OS Version	10.0.19043 
Build 19043

Noticed my Azure GNS3 Server is running fine, but GNS3-2.2.2 cannot connect to the server. Can you please revisit?

**Comment by grossmj** [comment] 2021-08-07 10:34
Weird, I don't have issues running the latest GUI on a Windows.

![Screenshot from 2021-08-06 21-26-06](https://user-images.githubusercontent.com/4752614/128597314-27ebd591-7c4d-47c9-8c7f-cc5eceabc474.png)

**Comment by quackwag** [comment] 2021-08-07 14:48
Glad I found this issue. Version 2.2.23 doesn't load the GUI. Reverted to 2.2.22 and it fixed the GUI issue, but now experiencing the version mismatch as my controller is 2.2.23. Thanks.

**Comment by NickJongens** [comment] 2021-08-07 14:50
@grossmj did you require us to upload any logs etc? It appears to be a python issue specifically.

**Comment by code8102** [comment] 2021-08-07 15:07
> 
> 
> Glad I found this issue. Version 2.2.23 doesn't load the GUI. Reverted to 2.2.22 and it fixed the GUI issue, but now experiencing the version mismatch as my controller is 2.2.23. Thanks.

You have 2 choices to revert back the VM either by typing : pip3 install gns3-server==2.2.22
or 
https://imgur.com/a/UH78HQF

**Comment by GalbanMayer** [comment] 2021-08-07 15:08
It works now: 
1. save your GNS3 Config from the Roaming Directory
2. Deinstall GNS3 completly
3. Install GNS3 2.2.22 (maybe other versions are ok)
4. startup GNS3 it should now show the GUI
5. Close GUI
6. Install GNS3 2.2.23 over the existing 
7. copy your GNS3 Config back 
8. start GNS3 - now it is working (cross my fingers for you )

It seems the problem is within the home directory, On the same Machine with an other user it works also

Hope I  save your weekend

**Comment by quackwag** [comment] 2021-08-07 15:17
> 
> 
> It works now:
> 
>     1. save your GNS3 Config from the Roaming Directory
> 
>     2. Deinstall GNS3 completly
> 
>     3. Install GNS3 2.2.22 (maybe other versions are ok)
> 
>     4. startup GNS3 it should now show the GUI
> 
>     5. Close GUI
> 
>     6. Install GNS3 2.2.23 over the existing
> 
>     7. copy your GNS3 Config back
> 
>     8. start GNS3 - now it is working (cross my fingers for you )
> 
> 
> It seems the problem is within the home directory, On the same Machine with an other user it works also
> 
> Hope I save your weekend

Followed the provided instructions and still unable to load the 2.2.23 GUI.



> 
> 
> > Glad I found this issue. Version 2.2.23 doesn't load the GUI. Reverted to 2.2.22 and it fixed the GUI issue, but now experiencing the version mismatch as my controller is 2.2.23. Thanks.
> 
> You have 2 choices to revert back the VM either by typing : pip3 install gns3-server==2.2.22
> or
> ![revert](https://user-images.githubusercontent.com/41831937/128604914-7fb8509e-6862-4ed0-abe9-954e2c5d9c57.PNG)

Thank you, will use this as a workaround.

**Comment by NickJongens** [comment] 2021-08-08 08:48
Hi @quackwag, this solution above did not work for me. Same issue.
Can you provide steps for downgrading in a Ubuntu VM 20.04? I hope to run the 2.2.22 server, however this command doesn't seem to do anything:


This is what I've been running as per an Azure setup video:

cd /tmp
curl https://raw.githubusercontent.com/GNS3/gns3-server/master/scripts/remote-install.sh > gns3-remote-install.sh
sudo bash gns3-remote-install.sh --with-iou --with-i386-repository

https://www.youtube.com/watch?v=FfJXcoqTvrs

**Comment by RevoWdZ** [comment] 2021-08-08 08:57
Somehow I fixed this issue by installing gns3 2.2.22 GUI over the existing 2.2.23 GUI, then uninstalling 2.2.22 GUI completely and perform clean install of the newest GUI version. Very weird way to make working application I would say 👎

**Comment by NickJongens** [comment] 2021-08-08 09:24
Managed to get going with the following python36.zip - combination of 2.2.22 and 2.2.23 versions.

It appears to be an issue with something above/outside the 'gns3' or 'gns3-server' folders.

[python36.zip](https://github.com/GNS3/gns3-gui/files/6950482/python36.zip)

![image](https://user-images.githubusercontent.com/39074050/128627337-6cc5580c-e2a9-4a90-9fc7-4e63d64f3de9.png)

**Comment by grossmj** [comment] 2021-08-09 05:03
I've uploaded a new build. Hopefully this fixes the problem: https://github.com/GNS3/gns3-gui/releases/download/v2.2.23/GNS3-2.2.23-all-in-one.exe

**Comment by mathwww** [comment] 2021-08-09 05:49
Perhaps the issue is related to Python 3.6 version, I updated to 3.9 and now works just fine. Even GNS3 GUI telling me that the Python Version is "3.6.8" all aliases to "python" calls in my windows refer to "3.9.6". I don't think that this version being shown at the GUI is right, though all I did was update Python version.

**Comment by DN0000** [comment] 2021-08-09 09:47
> Perhaps the issue is related to Python 3.6 version, I updated to 3.9 and now works just fine. Even GNS3 GUI telling me that the Python Version is "3.6.8" all aliases to "python" calls in my windows refer to "3.9.6". I don't think that this version being shown at the GUI is right, though all I did was update Python version.

Can confirm I was experiencing this issue with the download published on the website, and that installing this build resolved it. Thanks!

**Comment by sfer22** [comment] 2021-08-09 18:01
> I've uploaded a new build. Hopefully this fixes the problem: https://github.com/GNS3/gns3-gui/releases/download/v2.2.23/GNS3-2.2.23-all-in-one.exe

This new build fixed the issue for me too! @grossmj Thank you!

**Comment by procisco** [comment] 2021-08-09 21:15
The new build worked for me also. Thanks so much!!

**Comment by grossmj** [comment] 2021-08-10 00:57
Perfect, thanks for the update guys. Looks like this is fixed :+1:

**Closed by grossmj** 2021-08-10 00:57 UTC
Labels: Bug
