### ISSUE TITLE
Is possible binding label with link

### ISSUE THREAD

**Issue by jacquen** [GNS3/gns3-gui#2459] opened 2018-03-28 08:15 UTC
Hi, Team

Currently link label shows seperate with link, it difficult to manage within large topology, you need move node and move label. If we can bind label with link, it will be good. 

Thanks

**Comment by cioby23** [comment] 2018-03-28 08:47
I saw that this kind of binding of the labels with links is used on EVE-NG.

![image](https://user-images.githubusercontent.com/7124193/38018518-c369350e-327d-11e8-9b5a-054e4e96a092.png)

**Comment by grossmj** [comment] 2020-07-06 05:24
Duplicate of https://github.com/GNS3/gns3-gui/issues/2953

**Closed by grossmj** 2020-07-06 05:24 UTC
Labels: Duplicate
