### ISSUE TITLE
QEMU failed to start error

### ISSUE THREAD

**Issue by leribe** [GNS3/gns3-gui#2698] opened 2019-02-04 13:42 UTC
Hi GNS3 Team,
Can you please help, with qemu, getting below error. gns3 version 2.1.12 on Linux, tested on a different Linux vm and getting same error.

Could not start QEMU console [Errno 111] Connect call failed ('127.0.0.1', 5022).
google did not help.

Thanks in-advance

**Comment by grossmj** [comment] 2019-02-17 15:22
Duplicate of https://github.com/GNS3/gns3-gui/issues/2712

**Closed by grossmj** 2019-02-17 15:22 UTC
Labels: Duplicate
