### ISSUE TITLE
Feature Request : Add text box for description on Qemu VMs for each appliance template

### ISSUE THREAD

**Issue by e1ext** [GNS3/gns3-gui#2540] opened 2018-07-17 04:12 UTC
Hello,

I would like to ask for feature request (dunno whether it is called feature or not :-) ).
I think it would be good to have a simple text box just to have description on each Qemu VMs appliance template just to save some kind of simple text information, it can be used to store like default username and password because sometimes Qemu appliance comes with default username or password or IP address.

Maybe it also would applicable too not for Qemu only, but also the other appliance types

Would it be possible to have that?

Thank you in advance :-)

**Comment by grossmj** [comment] 2018-10-02 14:33
Duplicate of https://github.com/GNS3/gns3-server/issues/1298

**Closed by grossmj** 2018-10-02 14:33 UTC
Labels: Duplicate, Enhancement
