### ISSUE TITLE
Built-in switch shows rename but another switch can't use old name.

### ISSUE THREAD

**Issue by CapnCheapo** [GNS3/gns3-gui#1573] opened 2016-10-09 18:28 UTC
Hi,

I believe I have found a bug in version 1.5.2.  

Drag built-in Ethernet switch to an empty topology.  Created as SW1.  
Change switch hostname to something else, for example "test".
Drag another switch (either built-in or IOU, IOSv, etc).  
Change new switch's hostname to SW1.  It will ignore the request.  Any other name works fine.

**Comment by noplay** [comment] 2016-10-19 15:56
Duplicate of #1460 and already fixed :) 

No worry about the duplicate it's normal and thanks for the report!

**Closed by noplay** 2016-10-19 15:56 UTC
Labels: bug
