### ISSUE TITLE
[Linux/1.4.0] Enhancement with Spice support

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-gui#952] opened 2016-01-22 17:50 UTC
VNC is a nice effort going forward, but it cannot automatically resize and scale the display when the window uses the full size of the screen; Spice can with a client such as virt-viewer.not mentioning the performances which are better.

In case you need some tips, here are some options virt-manager uses when launching a VM with spice support:
qemu-system-x86_64 -enable-kvm -name KVM-Ubuntu-Gnome-Server-15.10 -S -machine pc-i440fx-2.4,accel=kvm,usb=off,vmport=off -cpu host -m 8192 -realtime mlock=off -smp 2,maxcpus=4,sockets=4,cores=1,threads=1 -uuid a7c60316-5975-49e0-b520-17147e86879a -no-user-config -nodefaults -chardev socket,id=charmonitor,path=/var/lib/libvirt/qemu/domain-KVM-Ubuntu-Gnome-Server-15.10/monitor.sock,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=discard -no-hpet -no-shutdown -global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 -boot strict=on -device ich9-usb-ehci1,id=usb,bus=pci.0,addr=0x8.0x7 -device ich9-usb-uhci1,masterbus=usb.0,firstport=0,bus=pci.0,multifunction=on,addr=0x8 -device ich9-usb-uhci2,masterbus=usb.0,firstport=2,bus=pci.0,addr=0x8.0x1 -device ich9-usb-uhci3,masterbus=usb.0,firstport=4,bus=pci.0,addr=0x8.0x2 -device ahci,id=sata0,bus=pci.0,addr=0xc -device virtio-serial-pci,id=virtio-serial0,bus=pci.0,addr=0x7 -drive file=/media/actionmystique/SAMSUNG-Ext4-1/KVM-Qemu/VMs/KVM-Ubuntu-Gnome-Server-15.10.qcow2,format=qcow2,if=none,id=drive-virtio-disk0 -device virtio-blk-pci,scsi=off,bus=pci.0,addr=0x9,drive=drive-virtio-disk0,id=virtio-disk0,bootindex=1 -fsdev local,security_model=mapped,id=fsdev-fs0,path=/home/actionmystique -device virtio-9p-pci,id=fs0,fsdev=fsdev-fs0,mount_tag=actionmystique-MSI-GE60-Ubuntu,bus=pci.0,addr=0xb -netdev tap,fd=23,id=hostnet0,vhost=on,vhostfd=24 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:e4:80:a9,bus=pci.0,addr=0x3 -netdev tap,fd=25,id=hostnet1,vhost=on,vhostfd=26 -device virtio-net-pci,netdev=hostnet1,id=net1,mac=52:54:00:d6:29:0f,bus=pci.0,addr=0x4 -netdev tap,fd=27,id=hostnet2,vhost=on,vhostfd=28 -device virtio-net-pci,netdev=hostnet2,id=net2,mac=52:54:00:38:12:1c,bus=pci.0,addr=0x5 **-chardev pty,id=charserial0 -device isa-serial,chardev=charserial0,id=serial0 -chardev spicevmc,id=charchannel0,name=vdagent -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=com.redhat.spice.0 -device usb-tablet,id=input0 -spice port=5900,addr=127.0.0.1,disable-ticketing,seamless-migration=on -device qxl-vga,id=video0,ram_size=67108864,vram_size=67108864,vgamem_mb=16,bus=pci.0,addr=0x2** -device intel-hda,id=sound0,bus=pci.0,addr=0x6 -device hda-duplex,id=sound0-codec0,bus=sound0.0,cad=0 -chardev spicevmc,id=charredir0,name=usbredir -device usb-redir,chardev=charredir0,id=redir0 -chardev spicevmc,id=charredir1,name=usbredir -device usb-redir,chardev=charredir1,id=redir1 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0xa -msg timestamp=on 

I have bolded the options which may come in handy or need to be investigated.

**Comment by noplay** [comment] 2016-01-22 18:54
Duplicate of https://github.com/GNS3/gns3-server/issues/256 I close this ticket to continue discussion on the other one.

**Closed by noplay** 2016-01-22 18:54 UTC
Labels: duplicate
