### ISSUE TITLE
2.1 : REQ :  Predictable Network Interface Names of VirtualBox

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2299] opened 2017-10-18 13:13 UTC
Hi

Debian Stretch (and Ubuntu, and perhaps Fedora) uses predictable network interface name : enp0s3

But, I dont find how to use this format in GNS3 Interface. 

On my VM, i see theses names : 
- enp0s3
- enp0s8
- enp0s9
- enp0s10
- enp0s16
- enp0s17
- enp0s18
- enp0s19

I prefer eth, but enp becomes a standard.

**Comment by grossmj** [comment] 2017-10-19 10:06
Hi,

You should be able to change that in the template settings for your VirtualBox VM.

![name_format](https://user-images.githubusercontent.com/4752614/31765704-7e6615fa-b4ef-11e7-8180-cf1ac3ede0f7.png)

**Comment by Raizo62** [comment] 2017-10-19 10:59
Yes, but the problem is the hop between enp0s**3** and enp0s**8**, enp0s**10** and enp0s**16**

**Comment by grossmj** [comment] 2017-10-19 11:41
Correct. Resolving this issue https://github.com/GNS3/gns3-gui/issues/2201 will solve that.

**Comment by Raizo62** [comment] 2017-10-19 15:10
I have an idea for virtualbox (because the max number of network card is 8) : 
A option activate a menu with 8 labels : one for each network card.

Perhaps you can use the same with more network card.

**Comment by grossmj** [comment] 2018-03-25 05:35
Duplicate of #2361

**Closed by grossmj** 2018-03-25 05:35 UTC
Labels: Enhancement
