### ISSUE TITLE
2.0 rc2 do not upload image files automatically?

### ISSUE THREAD

**Issue by Motysupra** [GNS3/gns3-gui#1963] opened 2017-03-24 13:01 UTC
I am using 2.0 rc2 with remote vm in ESXi, and it do not upload image files automatially, outputs an error>"
Could not create IOS router: Error while setting up node: C:\Users\admin\GNS3\images\IOS\c2691-advipservicesk9-mz.124-15.T14.image is not allowed on this remote server. Please use only a filename in /opt/gns3/images/IOS."

1.5.3 was uploading just fine, but now I had to connect via sftp and upload them manually. It worked. Is automatic upload feature now missing?

**Comment by noplay** [comment] 2017-03-24 14:30
Could you share the content of your gns3_guif.conf?

You can find the location here:
http://docs.gns3.com/1f6uXq05vukccKdMCHhdki5MXFhV8vcwuGwiRvXMQvM0/index.html#h.am4xcfvu0dvc

**Comment by syndgr** [comment] 2017-03-24 23:57
I think this is a duplicate of #1925?

**Comment by syndgr** [comment] 2017-03-25 00:02
@Motysupra you could try a nightly build to see if this bug is already fixed: https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2017-03-24/2.0/

please backup your settings etc. in case you need to roll back!

**Comment by Motysupra** [comment] 2017-03-26 23:59
@syndgr I've installed 2017-03-24/2.0/ and yes, it uploads images automaticaly! 


GNS3 console says "QWindowsWindow::setMouseGrabEnabled: Not setting mouse grab for invisible window QWidgetWindow/'uiDeviceMenuWindow'" every few seconds with this build.

**Closed** 2017-03-26 23:59 UTC
Labels: bug
