### ISSUE TITLE
IOSvL2 to Cloud (bridge) does not pass traffic, but IOU L2/3 and IOSvL3 does

### ISSUE THREAD

**Issue by vader75** [GNS3/gns3-gui#1876] opened 2017-02-20 23:19 UTC
Running 2.0.0b4 on Windows 10
GNS3 VM after choosing upgrade from b3, is now set as 2.0.0dev9. I assume dev9 == b4

Topology (see screenshot) represent IOU L2/L3 and IOSvL2/3 connecting via Cloud device(s) to Eth1 on GNS3 VM, for local LAN connectivity test (192.168.0.0/24).

All device running on GNS3 VM (IOU and QEMU Cisco images).

Each device is given static IP in this range.

Testing shows that IOSvL2 is the only one having issues in connecting to cloud to ping default gateway 192.168.0.1

Not sure why, arp table has no 192.168.0.1 entry, I assume no connecting/passing traffic. Other 3 devices successfully pinging obviously have arp entry.

<img width="1913" alt="l2_test_l2iosv_vs iou_cloud" src="https://cloud.githubusercontent.com/assets/3232190/23144844/8f80e65a-f81e-11e6-91fc-c16504e081c2.png">

**Comment by jtorri** [comment] 2017-02-21 02:28
I believe this is the "same" configuration as you list above.  Windows 10 Prof x64.  The only difference I see is I am running the GNS3 VM.ova that came with GNS3 2.0.0b4. 
GNS3 management console.
Running GNS3 version 2.0.0b4 on Windows (64-bit) with Python 3.5.2 Qt 5.8.0 and PyQt 5.8.  
I am able to ping by local subnet connected via Cloud (eth2).  Curious.  I cannot explain why?

![iosv-l2-1](https://cloud.githubusercontent.com/assets/10285348/23148403/841baac2-f7b3-11e6-9bc8-bc8e85c52f25.jpg)
![iosv-2-1-ping](https://cloud.githubusercontent.com/assets/10285348/23148406/88278d48-f7b3-11e6-966c-8ee50f3709eb.jpg)

**Comment by grossmj** [comment] 2017-02-21 04:39
@vader75 

I would suspect some config issue. Best to track that is to start a Wireshark capture on the link to the cloud to actually see what is going in/out.

Let me know what you see.

Thanks.

**Comment by vader75** [comment] 2017-02-21 04:41
Hmmm. Not sure why GNS3 VM upgraded to dev9 instead of b4.

@grossmj I will normalise with downloading and installing the GNS3 VM b4 OVA as you suggested as it seems that @jtorri has it working.

If this does not help then we can go wireshark.

**Comment by vader75** [comment] 2017-02-21 06:10
Very strange behaviour.

GNS3 VM has the second interface (eth1) as bridge to local LAN.

If I connect IOSvL2 directly to cloud eth 1 (representing the GNS3 VM), the switch goes into meltdown presenting error CPU HOG, example:

Switch#
-Traceback= 1DBB7C8z 8DBFE5z 90522Ez 904F50z 904D5Dz 900F45z 901B7Bz 901B0Fz 8E76A0z 8E760Ez 7E4E93z 1B6824Ez 1B67CEBz 1B64126z 1B63FC1z 1B63515z - Process "CDP Protocol", CPU hog, PC 0x008FD5B5


If I connect ethernet (inbuilt) between cloud and IOSvL2, I can then ping LAN segment and no CPU HOG  errors
![weird](https://cloud.githubusercontent.com/assets/3232190/23152805/9cb10b18-f858-11e6-8e0c-6503e45bc3ec.PNG)

Driving me insane now...
.

**Comment by vader75** [comment] 2017-02-21 07:34
Tried the IOU L2 and no problems. The only thing I can think of is IOSvL2 image issue... switching in GNS3 is a nightmare.

**Comment by noplay** [comment] 2017-02-21 09:12
The switch probably filter package from network when IOU as trouble to
handle them

**Comment by vader75** [comment] 2017-02-21 10:07
I think you are right, its processing some traffic from network it cant properly understand. I guess given that these are all Cisco software versions, its gonna be hard to control them to be stable. This lies the issue of how efficient GNS3 will be for Cisco work, as I see both IOSvL2 and IOU L2 issues. 

While IOU may just CPU HOG, I see IOL segment faults, assuming its to do with processing specific traffic and possible traffic via them.

Maybe best approach are real switches, but that ruins the experience.

**Comment by noplay** [comment] 2017-02-21 10:45
When using the cloud your risk to inject a lot of traffic to your virtual network depending how noisy is your local network. If you don't have the ressource the virtual IOSv could have trouble to handle it.  

And their is probably limitation in IOSv to preventing you to use it in production.

**Comment by vader75** [comment] 2017-02-21 22:16
@noplay I think you are right again :-) 

I am just looking at the ways to avoid the crashes and issues. I am not sure if this is possible at all, but as I pointed out, individually, this is spending more time troubleshooting functionality/behaviour then learning while using GNS3, as I am not a programmer.

I guess my expectation is/was that limits should be there but not to produce crashes or functionality stop, maybe limit throughput or some of the features or similar.

Its not GNS3's fault and there is not guarantee of anything working, but holistically, it ruins the experience.

**Comment by grossmj** [comment] 2017-02-22 04:12
Have you done a Wireshark capture to see what kind of traffic you get?

**Comment by vader75** [comment] 2017-02-22 12:55
@grossmj - I have "looked" at the traffic via wireshark, and since its bridged to local LAN of my host PC, its everything the host (PC) sees (a lot) connected to local switch for home LAN (its TP Link managed switch). 

Reason normally I would do this is to have VLAN 1 in GNS3 IOL/IOSv for management of switches over LAN, makes things much easier to remotely manage topologies and ssh.

If traffic volume is a problem, i.e. IOL/IOSv can't handle the rate, perhaps its better to isolate it from "promiscuous" nature, which I tried to do by putting built in switch object between cloud and IOSv. Seems to help.

So @noplay could be right, type and volume of traffic could be causing issues, and perhaps Cisco images are programmed for subset of type and rate of traffic in LAB, similar to VIRL issues cisco has (and features).

Another indication is that IOL image would segment fault when large volume traffic would be put through them, but this is not very scientific approach.

If you have a specific test in mind to try to define the trigger (type and volume of traffic) and solution, would be happy to assist. Currently not sure where to start.

I would love to hear from other GNS3 members if they had similar issues and observations?

**Comment by noplay** [comment] 2017-02-22 13:26
IOL/IOU was made for internal usage at Cisco if they don't have the use case they don't fix the bugs :(

You can try to put openvswitch in the middle if you want to try more advanced switch:
http://docs.gns3.com/appliances/openvswitch.html

**Comment by vader75** [comment] 2017-02-22 13:32
thanks @noplay - i guess C'est la vie, time to move to open source.

**Comment by noplay** [comment] 2017-02-22 13:54
I close the issue because doesn't seem to be a problem in GNS3 but in Cisco images.

**Closed by noplay** 2017-02-22 13:54 UTC

**Comment by defxsec** [comment] 2023-08-13 23:00
Buenas, estoy tratando de reproducir el siguiente escenario.
![imagen](https://github.com/GNS3/gns3-gui/assets/109879632/e5810ec5-6866-4b56-9486-74b592753d38)

Cuando intento configurar los SW1, SW2 y SW3 se me bloquea las consolas.
![imagen](https://github.com/GNS3/gns3-gui/assets/109879632/7b091979-942b-44c5-b349-f35500722a72)

![imagen](https://github.com/GNS3/gns3-gui/assets/109879632/41824bac-b092-40f4-9dd1-9e7f903e973c)

Es como estaría colgado las consolas
