### ISSUE TITLE
CPU allocation problem with GNS3-GUI while working with GNS3-VM.

### ISSUE THREAD

**Issue by AngelFalse** [GNS3/gns3-gui#2324] opened 2017-11-04 11:53 UTC
I was running a simulation, while it seems a little slower than I expected, I opened the preference and found that only 2 cores of CPU are allocated to the GNS3-VM.
![default](https://user-images.githubusercontent.com/28922095/32404992-5a6c78f6-c197-11e7-8d5c-8b3f6ded5080.png)
I adjusted it to 4 to make it quicker, but failed when I realized that the VM is still only be able to use half of my processor power(Task Manager easily gave it out). And I also find it interesting that, while running a simulation, my first two cores of CPU is 100% utilized, other 2 cores stay free.
I decided to open the VMware workstation to find out, and the truth is that GNS3 cannot control the cores VM can utilize. I set the "vCPUs" to 2, to 4, to 8, to 16, the VM's settings told me its CPU property is misconfigured to use "half of the CPU", and simulate the VM running on a "4 core CPU". That's just BS.
![2](https://user-images.githubusercontent.com/28922095/32405111-b875c824-c199-11e7-8657-43da41a307cf.png)
I have been using VMware for about 10 years, and at least I know that "number of CPUs" and "number of cores per CPU" must be integers rather than double. Who is responsible for this part shall fix this immediately, if this is a joke, it is not funny.

**Comment by grossmj** [comment] 2017-11-04 11:56
We will investigate this and fix the problem soon. Thank you for bringing this to our attention.

**Comment by ziajka** [comment] 2017-11-06 14:27
Hi @AngelFalse ,

We found and issue with control over VMware cores. It's already solved and will be delivered with the next release (couple of days).

However we couldn't reproduce issue with "0.5 CPU". Would you be so kind to send us debug info to developers@gns3.net? In order to do that, please click on GNS3 GUI Help -> "Export debug information". Thank you for your help.

Cheers,
Dominik

**Comment by ziajka** [comment] 2017-11-07 11:31
Thank you @AngelFalse for sending files. We will look on that.

**Comment by ziajka** [comment] 2017-11-12 13:03
Hi @AngelFalse,

Issue with 0.5 CPU is on the VMware side. In configuration of your VM you have:

```
numvcpus = "2"
cpuid.corespersocket = "4"
```
VMware makes calculations 2 / 4 = 0.5 (ref. https://basraayman.com/2010/08/03/shorts-what-is-it-about-cpuid-corespersocket-on-vsphere/).

In GNS3 we control only "numvcpus". Somehow cpuid.corespersocket was set, but it wasn't by GNS3. 

If you need more help just let us know. For now I'm closing issue.

Cheers,
Dominik

**Closed by ziajka** 2017-11-12 13:03 UTC
Labels: Bug

**Comment by mike940** [comment] 2019-01-30 05:13
Hi @ziajka I seem to have the same problem i can't seem to run my labs more efficiently as i get this error on gns3:

"Error while saving settings: GNS3VM: You have allocated too many vCPUs for the GNS3 VM! (max available is 2 vCPUs)"

I am currently running the latest version of GNS3 version 2.1.12 and my pc supports 4 logical processors, can you please tell me what steps i should take to correct this problem and and if its the cpuid problem then how do I change the cpuid.corespersocket = 1 in my VMX file I am currently using vmware workstation 12 player. thanks
