### ISSUE TITLE
[Enhancement] Allow a node to be executed on a remote host after it has been inserted into a topology

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-gui#1504] opened 2016-09-09 13:48 UTC
The **brilliant feature allowing a node to be executed on a remote host** has to be defined at creation point or it isn't accessible:
![selection_004](https://cloud.githubusercontent.com/assets/13176858/18389053/57bf70b6-76a4-11e6-8709-a0e92b88a365.jpg)
It would be very helpful to be able to control which nodes have to executed remotely and which nodes have to be executed locally, 
- if we have the same node type within a given topology for instance.
- if we need to change that behavior after the topology has evolved.

**Comment by noplay** [comment] 2016-09-09 19:59
It's a duplicate of:
https://github.com/GNS3/gns3-server/issues/575

Sadly no ETA for this feature.

Moving stuff after drop is not easy because we need also to move the data and reconfigure link. Even if the node never started if you change the machine you could have trouble  because one server could have qemu in one location (/usr/local/bin) and the other server in another location (/usr/bin).

**Closed by noplay** 2016-09-09 19:59 UTC
