### ISSUE TITLE
Export node configs does not work for CSR1000v or IOSv

### ISSUE THREAD

**Issue by pcapdevila** [GNS3/gns3-gui#2762] opened 2019-04-06 09:45 UTC
I'm unable to export node configs for nodes like CSR1000v or IOSv

 - OS: Debian Stretch
 - GNS3 version 2.1.14 bare metal etc.

1. Go to Tools > Import/Export node configs
2. Select Export configs to a directory, OK
3. Select destination directory, Open
4. Nothing happens

**Comment by cioby23** [comment] 2019-04-06 12:19
This is not a bug it's not implemented yet. This is covered by the more generic request GNS3/gns3-gui#1095 which should allow export of configs from all Qemu appliances.The milestone is set for GNS3 version 2.3
You can close this as a duplicate.

**Comment by grossmj** [comment] 2019-04-06 12:42
Maybe we should show a warning or something to let users know that this is not supported? I have seen others being confused by this.

**Comment by grossmj** [comment] 2019-04-11 08:43
A warning is now shown when trying to export a config for a node type that is not supported.

**Closed by grossmj** 2019-04-11 08:43 UTC
Labels: Enhancement

**Comment by candlerb** [comment] 2020-04-15 11:36
Related: https://github.com/GNS3/gns3-server/issues/1315
