### ISSUE TITLE
Interfaces labeled incorrectly under certain conditions

### ISSUE THREAD

**Issue by CapnCheapo** [GNS3/gns3-gui#2562] opened 2018-08-09 20:49 UTC
2.1.8 on remote linux server
local client Darwin (64-bit) with Python 3.6.5 Qt 5.11.0 and PyQt 5.10.1.

Using an appliance type where there is a unique first port name (mgmt0, such as NXOS) the 2nd non-management link always displays incorrectly on the topology summary and interface labels, but is correct on the drop-down when linking items.

![screen shot 2018-08-09 at 3 47 31 pm 2](https://user-images.githubusercontent.com/22641788/43925022-bc5ef8de-9beb-11e8-9ccc-5d4a720b46b5.png)

**Comment by grossmj** [comment] 2018-08-13 08:54
This should be fixed now. Thanks for catching this!

**Closed by grossmj** 2018-08-13 08:54 UTC
Labels: Bug

**Comment by CapnCheapo** [comment] 2018-08-13 14:29
Thanks!  After 2.1.9 there is still a minor formatting issue in the topology summary (In this case, e1/4 displayed twice)

<img width="783" alt="screen shot 2018-08-13 at 9 27 07 am" src="https://user-images.githubusercontent.com/22641788/44037998-63fce762-9edb-11e8-88ee-7c461397f2b9.png">

**Comment by grossmj** [comment] 2018-08-21 11:51
I cannot reproduce the problem. Have you created this lab from scratch or loaded an existing project?

**Comment by CapnCheapo** [comment] 2018-08-21 13:49
That was from an existing project, but seems to be even worse on a new one:

<img width="1009" alt="screen shot 2018-08-21 at 8 48 00 am" src="https://user-images.githubusercontent.com/22641788/44405505-03bbab00-a51f-11e8-9df3-a4f937eac642.png">

**Comment by grossmj** [comment] 2018-08-21 13:50
What are the network settings of your template? (port name format etc.)

**Comment by CapnCheapo** [comment] 2018-08-21 14:10
10 adapters, first port name mgmt0, name format Ethernet1/{port1}, segment size 0, base mac empty, type e1000.

**Comment by cioby23** [comment] 2018-08-25 09:56
I just did a test with the above settings mentioned by @CapnCheapo and I could not reproduce de issue. (Python 3.7, Archlinux, local server, GNS3 2.1.10dev2)
![image](https://user-images.githubusercontent.com/7124193/44617112-e90e6c80-a865-11e8-8958-7248394879e6.png)
![image](https://user-images.githubusercontent.com/7124193/44617115-fc213c80-a865-11e8-8cd6-fe5905ddd6f4.png)

**Comment by CapnCheapo** [comment] 2018-08-27 15:53
Server is linux, GUI is MacOS.  Not sure if this makes any difference...

**Comment by grossmj** [comment] 2018-08-27 16:14
@CapnCheapo Have you both the GUI and server on the same dev version?

**Comment by grossmj** [comment] 2018-09-19 20:43
@CapnCheapo version 2.1.10 is out, can you try with it?

Thanks!

**Comment by CapnCheapo** [comment] 2018-09-20 13:54
Apologies for the delay.  This appears to be working correctly now!
