### ISSUE TITLE
"Recent project" selection not working in 2.2.10

### ISSUE THREAD

**Issue by vint66** [GNS3/gns3-gui#3007] opened 2020-06-26 17:40 UTC
v2.2.10

"recent project" selection does not work.

**Comment by cioby23** [comment] 2020-06-26 19:16
Please provide some more information like operating system, server deployment type (local or remote) and if possible some screenshots.
I have checked this on version 2.2.10 running locally on Linux and it works fine.
https://imgur.com/F0C3bAa

**Comment by jnatschev** [comment] 2020-06-27 01:01
yes. i too have the same issue using macos 10.15.5, gns3 2.2.10. i am working around it by cancelling the initial project window and selecting an option from the "File" menu.

There are a number of ways, that i can see, to solve this:
1. remove the "recent projects" button and select "open a project from disk" or select a project from the "projects library" tab
2. fix the "recent projects" button
3. introduce a check box under, say settings -> general -> miscellaneous to enable/disable the "project" window at startup. i like this option. this could be deemed an "enhancement"

**Comment by b-ehlers** [comment] 2020-06-27 17:48
I checked this with the official GNS3-2.2.10.dmg for macOS 10.13.6 and in fact it doesn't work.

When clicking the "Recent project" button the list of recent project appears, but I can't use the mouse to select an item. Instead a warning tone can be heard as if this project list is unselectable.

![open_project](https://user-images.githubusercontent.com/49040325/85928427-2c482500-b8ad-11ea-9754-2871ba21fd9d.png)

I noticed this issue only with the official GNS3 application (GNS3 version 2.2.10 on Darwin (64-bit) with Python 3.6.5 Qt 5.11.0 and PyQt 5.10.1). My GNS3 installation by "pip3 install" works without any issues, I've tested GNS3 2.2.10 with Python 3.6.5 and PyQt5 5.10.1, 5.11.2 and 5.13.2 from PyPI.

**Comment by vint66** [comment] 2020-06-27 17:51
GUI installed on MacOS 10.15.5 via official .dmg image.
Server is custom remote setup on Ubuntu 18.04.

Basically issue the same as @b-ehlers showed on pic above.
Started after 2.2.10.

**Comment by b-ehlers** [comment] 2020-06-27 19:22
Tested with the official 2.2.8 and 2.2.9 DMG, both are working well, they don't show this issue.

**Comment by grossmj** [comment] 2020-07-09 06:09
This is really strange since we haven't touched anything regarding the recent projects menu between version 2.2.9 and version 2.2.10. Let's try again when version 2.2.11 is out and investigate more if it still doesn't work.

**Comment by jnatschev** [comment] 2020-07-09 11:53
i can confirm that selecting a project after clicking on the "Recent projects..." button from the resultant drop list is still not working with gns3-gui 2.2.11. my os is macos.

**Comment by grossmj** [comment] 2020-07-09 11:54
Thanks for confirming. I was expecting this.

**Comment by vint66** [comment] 2020-07-09 17:40
Same issue with 2.2.11

**Comment by grossmj** [comment] 2020-07-30 05:41
Seems to be an issue with Qt. It will be fixed in version 2.3 when we upgrade to a recent version of Qt: https://github.com/GNS3/gns3-gui/issues/3020

**Comment by cioby23** [comment] 2020-07-30 06:38
I'm using Qt 5.15 for some time and I guess that's why I did not experience any issues regarding the Recent Project selection.

**Comment by jnatschev** [comment] 2020-07-30 08:09
i loaded gns3-gui with gns3-server, both version 2.2.12dev1, as python -m gns3server and python -m gns3, and was able to select a project from the "Recent projects..." button drop-down list successfully. However, i did receive the message:
Error transferring http://admin@192.168.255.1:3080/v2/projects/load - server replied: Forbidden (192.168.255.1:3080)

I reckon this is unrelated.

**Comment by candlerb** [comment] 2020-10-03 09:58
I have the same problem as reported here, using gns3 2.2.14 under macOS 10.14.6

If I select "recent projects" then the list pops up: however, clicking on any of these just sounds the bell, and nothing else happens (no selection is made, the list remains visible).

![image](https://user-images.githubusercontent.com/44789/94988728-49a12500-0567-11eb-8c0f-8c7f949f6ac6.png)

**Comment by grossmj** [comment] 2020-10-10 09:38
I couldn't upgrade PyQt/Qt to a more recent version because of build issues on macOS.

**Comment by candlerb** [comment] 2021-08-28 15:57
It looks like the PyQt5 version change in [v2.2.24](https://github.com/GNS3/gns3-gui/releases/tag/v2.2.24) has fixed this for macOS, yay :-)  So I think this can be closed.

**Comment by grossmj** [comment] 2021-09-08 09:10
We use Qt 5.15.4 on both macOS and Windows now (https://github.com/GNS3/gns3-gui/issues/3020) but the bug is still here on my side.

**Comment by grossmj** [comment] 2021-09-09 05:09
Still the same issue on macOS :tired_face:

**Comment by grossmj** [comment] 2021-09-09 11:52
Fixed

**Closed by grossmj** 2021-09-09 11:52 UTC
Labels: Bug
