### ISSUE TITLE
[1.5] After "Stop capture" the server summary status goes red

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1520] opened 2016-09-18 13:52 UTC
GNS3 version 1.5.3dev1 on Darwin (64-bit) with Python 3.5.2 Qt 5.6.0.

When I stop the capture on a device running in a remote VM (GNS3 VM), the status LED in the server summary window goes to red, no error message in the logs. Still everything is running fine and on the next action the LED goes to green again. So it seems to be only a display problem. I haven't seen this with a local VM.

The GUI debug log:

```
2016-09-18 15:38:42 DEBUG project.py:385 Event received: {'action': 'ping', 'event': {'cpu_usage_percent': 17.8, 'memory_usage_percent': 5.2}}
2016-09-18 15:38:43 DEBUG vm.py:365 R2 is starting a packet capture on FastEthernet0/0: {'data_link_type': 'DLT_EN10MB', 'capture_file_name': 'R2_FastEthernet0-0_to_R1_FastEthernet0-0.pcap'}
2016-09-18 15:38:43 DEBUG http_client.py:576 POST http://192.168.1.99:3080/v1/projects/277d0cba-8078-416f-8d6c-1292c0da82d7/dynamips/vms/0c6ab9cd-b49e-4f4f-a996-652406f57021/adapters/0/ports/0/start_capture {'data_link_type': 'DLT_EN10MB', 'capture_file_name': 'R2_FastEthernet0-0_to_R1_FastEthernet0-0.pcap'}
2016-09-18 15:38:43 DEBUG http_client.py:711 Decoding response from http://192.168.1.99:3080/v1/projects/277d0cba-8078-416f-8d6c-1292c0da82d7/dynamips/vms/0c6ab9cd-b49e-4f4f-a996-652406f57021/adapters/0/ports/0/start_capture response 200
2016-09-18 15:38:43 DEBUG http_client.py:718 {
    "pcap_file_path": "/opt/gns3/projects/277d0cba-8078-416f-8d6c-1292c0da82d7/project-files/captures/R2_FastEthernet0-0_to_R1_FastEthernet0-0.pcap"
}
2016-09-18 15:38:43 INFO port.py:501 Saving packet capture to /var/folders/qy/g6blgc5n7y93pzg61zyt7cmr0000gn/T/tmp0lbq6ujt
2016-09-18 15:38:43 DEBUG http_client.py:576 GET http://192.168.1.99:3080/v1/files/stream {'location': '/opt/gns3/projects/277d0cba-8078-416f-8d6c-1292c0da82d7/project-files/captures/R2_FastEthernet0-0_to_R1_FastEthernet0-0.pcap'}
2016-09-18 15:38:43 INFO packet_capture.py:63 R2 has successfully started capturing packets on FastEthernet0/0
2016-09-18 15:38:47 DEBUG project.py:385 Event received: {'action': 'ping', 'event': {'cpu_usage_percent': 1.2, 'memory_usage_percent': 5.2}}
2016-09-18 15:38:52 DEBUG project.py:385 Event received: {'action': 'ping', 'event': {'cpu_usage_percent': 1.2, 'memory_usage_percent': 5.3}}
2016-09-18 15:38:57 DEBUG project.py:385 Event received: {'action': 'ping', 'event': {'cpu_usage_percent': 1.4, 'memory_usage_percent': 5.2}}
2016-09-18 15:39:00 DEBUG vm.py:396 R2 is stopping a packet capture on FastEthernet0/0
2016-09-18 15:39:00 DEBUG http_client.py:576 POST http://192.168.1.99:3080/v1/projects/277d0cba-8078-416f-8d6c-1292c0da82d7/dynamips/vms/0c6ab9cd-b49e-4f4f-a996-652406f57021/adapters/0/ports/0/stop_capture {}
2016-09-18 15:39:00 DEBUG http_client.py:711 Decoding response from http://192.168.1.99:3080/v1/projects/277d0cba-8078-416f-8d6c-1292c0da82d7/dynamips/vms/0c6ab9cd-b49e-4f4f-a996-652406f57021/adapters/0/ports/0/stop_capture response 204
2016-09-18 15:39:00 DEBUG http_client.py:718
2016-09-18 15:39:00 INFO http_client.py:680 Response error: Operation canceled (error: 5)
2016-09-18 15:39:00 INFO http_client.py:271 Connection to http://192.168.1.99:3080 closed
2016-09-18 15:39:00 INFO packet_capture.py:95 R2 has successfully stopped capturing packets on FastEthernet0/0
2016-09-18 15:39:02 DEBUG project.py:385 Event received: {'action': 'ping', 'event': {'cpu_usage_percent': 1.3, 'memory_usage_percent': 5.3}}
QTextCursor::setPosition: Position '41' out of range
2016-09-18 15:39:07 DEBUG project.py:385 Event received: {'action': 'ping', 'event': {'cpu_usage_percent': 0.8, 'memory_usage_percent': 5.2}}
2016-09-18 15:39:12 DEBUG project.py:385 Event received: {'action': 'ping', 'event': {'cpu_usage_percent': 0.9, 'memory_usage_percent': 5.2}}
2016-09-18 15:39:17 DEBUG project.py:385 Event received: {'action': 'ping', 'event': {'cpu_usage_percent': 0.8, 'memory_usage_percent': 5.2}}
```

**Comment by noplay** [comment] 2016-09-18 19:09
I think it doesn't affect 2.0 due to rework of the way we start capture.

But need to be investiguate for 1.5.

**Comment by noplay** [comment] 2016-09-21 16:30
Hmm I don't reproduce the issue

**Comment by ehlers** [comment] 2016-09-21 18:04
I have no problems reproducing that:
- start with an empty project
- move 2 routers into the project, tested with IOS (in the VM), IOU and docker
- connect the routers
- start both routers
- start capture
- stop capture

But the routers have to run a a remote server, the local server doesn't show that issue.

I have installed the latest 1.5.3dev1, the GUI runs on  on Darwin (64-bit) with Python 3.5.2 Qt 5.6.0, the server in a debian stretch VM with python 3.5.2.

**Comment by noplay** [comment] 2016-09-21 20:36
The remote is on local network?

**Comment by ehlers** [comment] 2016-09-21 20:55
The remote is a VM on my local computer, eth0 of the VM is bridged to my LAN. So my computer (192.168.1.10/24) is in the same network as the VM (192.168.1.99/24)

**Comment by ehlers** [comment] 2016-09-21 21:17
Perhaps i created confusion with the term "remote". I don't mean a GNS3 server running remotely, it's just a non-local GNS3 server, in my case running in a GNS3 VM.

So I don't have this issue, when running dynamips router in my local GNS3 server. But I have this issue, when I capture data from router, that are running in my GNS3 VM.

**Comment by ehlers** [comment] 2016-10-19 12:00
Maybe we can close this issue. It's only a minor flaw in the display of the server status and Julien can't reproduce it.

**Comment by grossmj** [comment] 2017-02-21 09:06
We want to focus on 2.0. I am closing this.

**Comment by ehlers** [comment] 2017-03-15 09:52
The issue is, that packet_capture.py/stopCapture() (on a stream_capture request) aborts the file stream of the pcap file, which results in a QtNetwork.QNetworkReply.OperationCanceledError in http_client.py/_processResponse(), which in turn closes the connection to the remote server. So the server summary status is correct, the connection to the remote server is down.

As a workaround I turned off the error reporting of the pcap file stream. I'm not too happy with that, as other problems during the pcap transfer will not be reported. But I found no other easy way to suppress the closing of the server connection.
```
diff --git a/gns3/packet_capture.py b/gns3/packet_capture.py
index 8d37d15a..20b4acfc 100644
--- a/gns3/packet_capture.py
+++ b/gns3/packet_capture.py
@@ -58,7 +58,8 @@ class PacketCapture:
                             body={"location": file_path},
                             context={"pcap_file": temp_capture_file_path, "vm": vm},
                             downloadProgressCallback=self._processDownloadPcapProgress,
-                            showProgress=False)
+                            showProgress=False,
+                            ignoreErrors=True)

         log.info("{} has successfully started capturing packets on {}".format(vm.name(), port.name()))
         vm.updated_signal.emit()
```

**Comment by ehlers** [comment] 2017-03-15 09:58
I'm not sure, if this applies to 2.0, I tested only on 1.5.3.

**Comment by noplay** [comment] 2017-03-15 09:58
I will check but I think this could happen also on 2.0

**Comment by noplay** [comment] 2017-03-16 13:38
Now we ignore it in 2.0

**Closed by noplay** 2017-03-16 13:38 UTC
Labels: bug
