### ISSUE TITLE
GNS3 1.4.4 can`t connect local address!

### ISSUE THREAD

**Issue by qianxideyu** [GNS3/gns3-gui#1086] opened 2016-02-25 09:10 UTC
In windows10 platform, I opened gns3 client, I turned it off, then on again, it can not connect to a local address, I found that the system processes have not quit gns3 process, I closed gns3 process, the problem is solved！
![qq 20160225171252](https://cloud.githubusercontent.com/assets/15842207/13314995/1f10e4ae-dbe3-11e5-87e8-36f3dc8f847a.jpg)
![gns bug](https://cloud.githubusercontent.com/assets/15842207/13314916/a781cdb8-dbe2-11e5-9f3c-b84da65f2ab3.jpg)

**Comment by noplay** [comment] 2016-02-25 12:45
It's just after an upgrade?

**Comment by danieldemers** [comment] 2016-02-25 14:29
I have had this issue on all 1.4.x versions. 1 in 5 times it will connect properly to the local server...even if it says it fails I can still use real IOS versions etc...it just acts like it fails.

**Comment by qianxideyu** [comment] 2016-02-26 04:40
no

**Comment by noplay** [comment] 2016-02-26 08:57
Which process remain? gns3.exe or gns3server.exe?

**Comment by noplay** [comment] 2016-02-29 08:05
Duplicate of #1088

**Closed by noplay** 2016-02-29 08:05 UTC
Labels: bug
