### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#207] opened 2015-03-15 21:52 UTC
https://app.getsentry.com/gns3/gns3-gui/group/58225887/

```
Stacktrace (appel le plus récent en dernier) : 

  File "c:\users\gns3\documents\gns3 build for windows\gns3-gui\gns3\main_window.py", line 441, in openProjectActionSlot
  File "c:\users\gns3\documents\gns3 build for windows\gns3-gui\gns3\main_window.py", line 466, in _loadPath
  File "c:\users\gns3\documents\gns3 build for windows\gns3-gui\gns3\main_window.py", line 1114, in checkForUnsavedChanges
  File "c:\users\gns3\documents\gns3 build for windows\gns3-gui\gns3\project.py", line 143, in topologyFile
```

**Comment by noplay** [comment] 2015-03-16 21:23
Duplicate of #208 it's the same issue

**Closed by noplay** 2015-03-16 21:23 UTC
Labels: bug, duplicate
