### ISSUE TITLE
Upgrade PyQt5 version

### ISSUE THREAD

**Issue by jhonnyx82** [GNS3/gns3-gui#2778] opened 2019-04-26 08:00 UTC
**Describe the bug**
Please provide a clear and detailed description of what the bug is.

**GNS3 version and operating system (please complete the following information):**
 - OS: GUI on Windows 10 and Server on Linux Debian 9 bare server 
 - GNS3 version 2.1.16
 - bare metal local server Linux KVM

**To Reproduce**
1. open a project
2. right click on any resource, even any device templates
3. contextual menu will disappear almost immediately unless right mouse button is kept pressed

**Additional context**
This started with version 2.1.16

**Comment by grossmj** [comment] 2019-05-16 08:57
Maybe this is due to PyQt/Qt upgrade. There is a new PyQt5 version that has been recently released https://pypi.org/project/PyQt5/#history maybe this will fix this problem.

**Comment by grossmj** [comment] 2019-05-17 03:43
I couldn't reproduce the problem. Let's see if the PyQt/Qt upgrade will fix this.

**Comment by grossmj** [comment] 2019-05-18 06:33
@jhonnyx82 can you give a try with version 2.1.17? Thanks!

**Comment by jhonnyx82** [comment] 2019-05-18 08:48
Will do today Jeremy and will keep you posted

**Comment by grossmj** [comment] 2019-05-19 09:54
Also reported on https://gns3.com/community/discussion/right-clicking-device-immediatel

**Comment by grossmj** [comment] 2019-05-19 10:01
According to users:

> 2.1.15 was Working OK
2.1.16 Right Click Changed , have to keep Mouse button depressed to Select Lower MEnu Items
2.1.17 Still have to keep Right Mouse Depressed to Select Lower Items on Context menu.

The only see this change between 2.1.15 and 2.1.16 which could be related to that error: https://github.com/GNS3/gns3-gui/commit/f97d3041b8069e082cbcf5ea2540143046efc8b4#diff-894e35f2985e1074271488e16cb5e626

**Comment by grossmj** [comment] 2019-05-20 04:59
I confirm I can reproduce the problem on Windows 10

**Comment by grossmj** [comment] 2019-05-20 05:15
This dev version fixes the problem: https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2019-05-20/2.1/GNS3-2.1.2019-05-20-all-in-one.exe/download

**Comment by grossmj** [comment] 2019-05-20 06:59
Looks like this confirms that the bug is in Qt since version 5.12.1

https://bugreports.qt.io/browse/QTBUG-74057
https://bugreports.qt.io/browse/QTBUG-74075

**Comment by grossmj** [comment] 2019-05-20 09:59
This is fixed by downgrading to Qt 5.12.0, let's keep this issue opened to monitor when the bug is fixed in Qt so we can again upgrade to the latest Qt 5.12.x version.

**Comment by ralikhani110** [comment] 2019-05-23 08:21
After upgrading to 2.1.18, the problem has been resolved.

**Comment by grossmj** [comment] 2019-05-23 08:21
Thanks for the confirmation :+1:

**Comment by grossmj** [comment] 2020-01-22 09:54
I have upgrade to Qt version 5.14.1 on GNS3 2.3 branch. Let's see if everything is ok in the next nightly build.

**Comment by grossmj** [comment] 2020-01-25 10:11
GNS3 2.2 branch has been updated too. I didn't notice any issue.

**Closed by grossmj** 2020-01-25 10:11 UTC
Labels: Bug
