### ISSUE TITLE
[REQ] Lines drawing extension with curves

### ISSUE THREAD

**Issue by jhonnyx82** [GNS3/gns3-gui#2608] opened 2018-10-18 11:44 UTC
Hi Everyone,

A "simple" request here on the graphical side, I would need to draw curves on connecting links lines to distinguish between two connections between the same nodes

![image](https://user-images.githubusercontent.com/26431888/47152073-e2d3c400-d2db-11e8-9d24-f263867dec01.png)

**Comment by grossmj** [comment] 2018-10-27 13:20
I believe this is a duplicate of https://github.com/GNS3/gns3-gui/issues/2303. Thanks for posting anyway :+1:

**Closed by grossmj** 2018-10-27 13:20 UTC
Labels: Duplicate
