### ISSUE TITLE
Exporting Portable Projects with Base IOU Images

### ISSUE THREAD

**Issue by WarpRat** [GNS3/gns3-gui#2439] opened 2018-02-23 21:38 UTC
When exporting a portable project with IOU images and selecting include base images, the IOU images aren't included in the portable project. The permissions and ownership of the image files and directory seem to be correct (i.e. 755 & gns3:gns3), although I also tried setting the permissions of the images directory and everything in it to 777 for testing with no success.

I haven't been able to export the debug information from the gui as I'm using a remote server running Ubuntu 16.04. I did read through all the logs I could find on the server and nothing jumped out at me. I've attempted this from a gns3-gui running on Ubuntu 17.10, 17.04, and MacOS 10.13 all using the same remote server.

I was able to open the portable project and manually insert the IOU images in the proper file structure and successfully load the project in another GNS3 gui, but it's an inelegant solution if you need to often create portable projects.

I also noticed that if I attempt to export a portable project with base images and it includes IOU images, the README.txt will be blank. If the project has a mix of QEMU IOSv images and IOU images, only the IOSv images will be in the portable project but the README.txt will show up properly.

This seems similar to issue #1928 but I did not receive any warning.

Please let me know if there is any more information I can provide. Thank you.

**Comment by grossmj** [comment] 2018-03-07 17:16
Fixed by https://github.com/GNS3/gns3-server/commit/22db13d2bf07a184f0df2feabb064451686b86c7

@WarpRat please test when we release version 2.1.4 soon and let us know if everything works as intended on your side.

Thanks!

**Comment by grossmj** [comment] 2018-03-14 11:35
This is fixed in version 2.1.4

**Closed by grossmj** 2018-03-14 11:35 UTC
Labels: Bug, Waiting for more information

**Comment by WarpRat** [comment] 2018-03-15 01:17
Just confirmed that it works as expected. Thank you so much.
