### ISSUE TITLE
GNS3 2.0.0 non linked base machine

### ISSUE THREAD

**Issue by nrafia** [GNS3/gns3-gui#1646] opened 2016-11-05 17:11 UTC
I have a machine which i used as non linked base machine, indifferent projects. As this is a common server, which is home for logging and providing ftp/ntp services. I have tried to use this machine in a new project and got message that this machine is already part of another project and machine was not able to start.
I believe, much better option will be just warn the user and let machine power on. 
If this restriction is there, then for each monitoring/logging option each project need its own machine, not much feasible.

**Comment by noplay** [comment] 2016-11-06 19:56
Actually in 2.0 the limitation is you can't use the same machine in two running project.

What do you think @grossmj ? For me using the same VMware VM or VirtualBox VM in two projects could result in conflicts for the control of the VM (erasing adapters of the other VM for example), and from a network point of view I don't know what exactly will happen (we will probably leak packet from a topology to the other topology).

**Comment by nrafia** [comment] 2016-11-07 13:54
I can see reasoning behind restriction if machine is called in two different running projects. I suggest to introduce a separate node type called community node. Configuration of community node can be only changed from its specific properties independent of projects. Change in properties of community node should replicate in all projects.
In my case I was running only one project. And it was not allowed to insert machine in it.

**Comment by noplay** [comment] 2016-11-07 14:07
If you have only one project open and you can't add the node it sound like a bug.

What is your workflow how do you create / switch project?

**Comment by nrafia** [comment] 2016-11-07 17:27
I have opened a project which includes a device as non linked base image. And closed the project.Then I opened a blank project and dragged same device from device list and got error message. I have revert back to 1.5 so cannot regenerate it. I m using VM gns3.
2.0 has made me to re generate my f5 licenses so I have to revert back to 1.5

**Comment by jtorri** [comment] 2016-11-11 02:13
Perhaps this is similiar.  Windows 10 prof x64.  GNS3 2.0.2016-11-10.  VMWare workstation 12.5.1
Open a project ("Project A") with a vmware virtual machine, two IOU "routers", and one cloud.  Never start "Project A".
Best I can tell there is no option to "close" a project.  So with "Project A" open I open "Project B" and get the following error message.  Both "Project A" and "Project B" have Windows7Ultimatex64 as virtual machine in their topology.

"Sorry a node without the linked clone setting enabled can only be used once on your server. C:\VirtualMachines\VMWareWorkstation10\Windows 7 Ultimate x64\Windows 7 Ultimate x64.vmx is already used by Windows7Ultimatex64"

**Comment by noplay** [comment] 2016-11-17 10:03
When you open a project the previous project is close. 

But actually the problem is:
* Client is connected to project A
* Client open project B
* Server answer project B is open
* Client disconnect from project A
* Server auto close project A because now 0 client are connected to A

The server is right to throw an error. At a point in time two different project talk to the exact same VM.

We need to make sure the client disconnect before starting to open or create project on server.

**Comment by noplay** [comment] 2016-11-17 10:46
Another problem making thing more complex.

The client could lost connection for a few seconds we don't auto close until this timeout to avoid problems. This mean just closing the connection on client is not enough.  Also the close is made in background it could take a long time if the project need to free a lot of ressources (stop VMware ...)

**Comment by noplay** [comment] 2016-11-17 11:27
I just implement a workaround. 

When we detect this error we retry during 30 seconds if the node is in another project. 5 seconds if the node is in the same project.

Thanks for the reports

**Closed by noplay** 2016-11-17 11:27 UTC
Labels: bug
