### ISSUE TITLE
No VMnet interface available between vmnet2 and vmnet255 - GNS3 and Windows7 VM on VMware Fusion

### ISSUE THREAD

**Issue by niyidrums** [GNS3/gns3-gui#3177] opened 2021-05-10 18:24 UTC
Hi,

I'm trying to connect a windows 7 VM installed on VMware Fusion 12 running on macOS with an existing topology on GNS3. I have configured the VMnet interfaces to use from within GNS3 (see snapshots). I have also allowed GNS3 to override non custom VMware adapter, however, I cannot start the device. 

The  error - "No VMnet interface available between vmnet2 and vmnet255. Go to preferences VMware / Network / Configure to add more interfaces." - pops up every time I try to start the device. I've deleted the VMnet and reconfigured again, but still the same.

Appreciate anyones help on this, probably I'm missing something.

Laptop: macOS Big Sur Version 11.3.1
GNS3 Version: GNS3 2.2.20
VM Host: VMware Fusion Player Version 12.1.1 (17801503)
VM device to add: Windows 7

Thanks.

Below is link to the community with snapshots.

https://gns3.com/community/featured/no-vmnet-interface-available-between-vmnet2-and-vmnet255-gns3-and-windows7-vm-on-vmware-fusion

**Comment by grossmj** [comment] 2021-05-16 12:42
Duplicate of https://github.com/GNS3/gns3-gui/issues/3176

**Closed by grossmj** 2021-05-16 12:42 UTC
Labels: Duplicate
