### ISSUE TITLE
Placing the docks back in its original window, is nearly impossible. [GNS 2.2.31] [GNOME 42] [Fedora 36]

### ISSUE THREAD

**Issue by PranavBhattarai** [GNS3/gns3-gui#3317] opened 2022-04-17 09:37 UTC
If I remember correctly, I don't think the situation was this worse in the prior release but surprisingly I also find this post:
https://gns3.com/community/support/help-how-to-set-topology-summary

Looks like this redocking was a genuine problem and very hard to solve. _But I didn't face this issue before. It was easy to merge windows back into one place._
Having multiple floating Independent dock windows are **not** a problem but not having control over them _(brings them back to their original state)_ is bad. 

Firefox, IntelliJ, VSCode, Chromium, etc all allow users to separate a tab from the original window but they also allow users to re-dock the tab into its original window. GNS3 complicates the re-docking scenario and can annoy users to a certain limit. It's not impossible to redock them (**server summary** and **topology summary**) back to GNS3, but the process is tiresome and involves how lucky you really are.

GNS3 window should **RECOGNIZE** that the user is trying to re-dock some window back in its original window.  Sadly it doesn't.

Meanwhile, I have to use GNOME's **always on top** shortkey and use GNS3 like this:

![Painful to go through](https://user-images.githubusercontent.com/32763112/163708856-60b379ff-a117-4f10-8ca3-c8df22175df7.png)

Please fix this **drag-n-drop** issue. Make redocking the windows, a simple straightforward step.

**Comment by b-ehlers** [comment] 2022-04-17 15:36
It's interesting, that my experience is completely different. I'm using GNS3 v2.2.31 on Debian 11 with XFCE 4.16 and Qt 5.15.2.

I have no issues to drag back an undocked window to the main GNS3 window. I click on the title bar of the undocked window and drag it to the main window. As soon the mouse cursor enters the main window, a light blue area appears in the main window, which shows where the undocked window will be located when I release the mouse button.

![gui_detached_attach_right](https://user-images.githubusercontent.com/49040325/163721053-73d220b7-e5e0-4d3b-9f3c-7baf0054d15f.png)

Alternatively I can use the second left button on the top right of the docked window decoration. I works as dock/undock. Using it on a docked window will undock it, using it on an undocked window with re-dock it.

I haven't configured anything to get this behaviour, it just works that way after installing GNS3.

**Comment by josephmhiggins** [comment] 2022-04-17 17:20
yeah. a problem like this exists in securecrt.
it has taken me over an hour to redock the docks on multiple occassions.
it is very frustrating.
a similar situation existed years ago in gns3 when they came out with 4K monitors - which I had one.
it destroyed all my projects.
someway, somehow i discovered "zoom reset" in the gui.
i take [PranavBhattarai](https://github.com/PranavBhattarai) at his word when he says the docks can be really hard to redock.
View
........Docks
.................Reset Docks
may be an option.

**Comment by grossmj** [comment] 2022-04-18 10:53
Well, docks are handled by Qt so it is possible to get different behaviors depending on the installed Qt version.

**Comment by PranavBhattarai** [comment] 2022-04-18 11:13
> I'm using GNS3 v2.2.31 on Debian 11 with XFCE 4.16 and Qt 5.15.2. I have no issues to drag back an undocked window to the main GNS3 window

@b-ehlers same here. I also didn't have this issue in Fedora 35 with GNOME 41 if I remember it correctly. It was working fine. This is a new problem, especially on F36 with the new GNOME 42. As you can see in the gif below:

![Screencast from 04-18-2022 04 37 14 PM](https://user-images.githubusercontent.com/32763112/163799495-b2d6780c-678f-4200-a6ca-1eaf521aaf6f.gif)

Instead of redocking, the window splits right and left as if there is no other window in the background.

> i take [PranavBhattarai](https://github.com/PranavBhattarai) at his word when he says the docks can be really hard to redock.
 View
........Docks
.................Reset Docks
may be an option.

@josephmhiggins I really fall for that imaginary option. But even if that option doesn't exist, @grossmj we should have such **reset option** inside the dock's menu. It's not a bad idea. 

![image](https://user-images.githubusercontent.com/32763112/163799955-e71a9716-c135-41d0-bdb0-1d30ca361bf0.png)

In future releases, let's say, redocking & docking become very smooth, but a RESET option can be helpful to bring back the dock in its **default** original state, without having to reset entire settings.

**Comment by grossmj** [comment] 2022-04-18 11:14
I will try to add the reset option for the next release.

**Comment by PranavBhattarai** [comment] 2022-04-18 11:39
Thank you.

_(By the way, the "Reset option" is always a welcome to have. Also "smooth redocking" experience. Those two are two different things but related to 1 issue. So, please don't close this issue after achieving the "reset option" only. We also need "smooth redocking". I hope I'm making sense here.)_

**Comment by grossmj** [comment] 2022-04-20 08:54
I have added a reset option that will be included in the next release. Let's see if it helps...

**Comment by PranavBhattarai** [comment] 2022-04-21 08:54
That's good to know. And yes, it does help solve one part of the issue, next is the smoother user's placement of docks.

**Comment by PranavBhattarai** [comment] 2022-05-27 10:53
Update:
```
⟹  dnf history userinstalled | grep -i gns
gns3-gui-2.2.32-1.fc36.noarch
gns3-server-2.2.32-2.fc36.noarch
```
2.2.32 release was very helpful @grossmj. Thanks, man. 

`Improvements`
1. I now can **reset the docks** if I tend to give up on docks placement/design.
2. I now can **_somehow_** design the docks. If I drop too early, it creates a buggy situation*. But if I drop an inappropriate place (i.e right-sidebar or left-sidebar), then voila, I have successfully managed to design the way I want.


`What "buggy situation" happens when/if I don't drop docks on the right-side or left site?!`
- Well, previously, when docks weren't pushed toward a particular section (right/left/bottom), it used to become an **independent window**, which has its own identity/properties (like title bar & minimize/maximize option), but now, it looks like this:

![image](https://user-images.githubusercontent.com/32763112/170685152-e5581371-c4b2-4c83-985b-04d3f8275190.png)
No way to move that floating window, neither there is a way to close this pop-up window, nothing.

`So how do you get out of such a situation?!`
1. Close the GNS3
2. Open GNS3
3. Don't option any project. Click on "Reset the dock"
4. Redesign the dock the way you want, but be careful to NOT drop the docks in the center/chest area of the GNS3 main window. Drop the docks either in right, left, or bottom.

fi

**Comment by grossmj** [comment] 2022-06-08 16:16
Unfortunately, I cannot reproduce the issue. Maybe changing the Qt libs version would help? I use Qt 5.15.2 and PyQt 5.15.4

![Screenshot from 2022-06-09 00-14-53](https://user-images.githubusercontent.com/4752614/172666384-0ef7f95a-7f55-439d-b361-52faa8ba24cf.png)

**Comment by PranavBhattarai** [comment] 2022-06-10 04:30
I just check the package version on my side. It looks like this:
```
 ⟹  pip3 list | grep -i qt
PyQt5               5.15.6
PyQt5-sip           12.9.0
PyQtWebEngine       5.15.4
```
And after a couple of research, I **think** I have **Qt 5.15.3** installed in my system because it looks like this:
```
  ⟹  repoquery --installed | grep -i qt
adwaita-qt5-0:1.4.1-3.fc36.x86_64
dbusmenu-qt5-0:0.9.3-0.28.20160218.fc36.x86_64
gstreamer1-plugins-good-qt-0:1.20.0-1.fc36.x86_64
libaccounts-qt5-0:1.16-5.fc36.x86_64
libadwaita-qt5-0:1.4.1-3.fc36.x86_64
phonon-qt5-0:4.11.1-9.fc36.x86_64
phonon-qt5-backend-gstreamer-2:4.10.0-7.fc36.x86_64
polkit-qt5-1-0:0.114.0-3.fc36.x86_64
poppler-qt5-0:22.01.0-3.fc36.x86_64
python-qt5-rpm-macros-0:5.15.6-3.fc36.noarch
python3-pyqt5-sip-0:12.9.0-3.fc36.x86_64
python3-qt5-0:5.15.6-3.fc36.x86_64
python3-qt5-base-0:5.15.6-3.fc36.x86_64
python3-qt5-webengine-0:5.15.4-2.fc36.x86_64
qt-settings-0:36.0-1.fc36.noarch
qt5-qtbase-0:5.15.3-2.fc36.x86_64
qt5-qtbase-common-0:5.15.3-2.fc36.noarch
qt5-qtbase-gui-0:5.15.3-2.fc36.x86_64
qt5-qtconnectivity-0:5.15.3-1.fc36.x86_64
qt5-qtdeclarative-0:5.15.3-2.fc36.x86_64
qt5-qtgraphicaleffects-0:5.15.3-1.fc36.x86_64
qt5-qtimageformats-0:5.15.3-1.fc36.x86_64
qt5-qtlocation-0:5.15.3-1.fc36.x86_64
qt5-qtmultimedia-0:5.15.3-1.fc36.x86_64
qt5-qtquickcontrols-0:5.15.3-1.fc36.x86_64
qt5-qtquickcontrols2-0:5.15.3-1.fc36.x86_64
qt5-qtsensors-0:5.15.3-1.fc36.x86_64
qt5-qtserialport-0:5.15.3-1.fc36.x86_64
qt5-qtspeech-0:5.15.3-1.fc36.x86_64
qt5-qtspeech-speechd-0:5.15.3-1.fc36.x86_64
qt5-qtsvg-0:5.15.3-1.fc36.x86_64
qt5-qttools-common-0:5.15.3-1.fc36.noarch
qt5-qttools-libs-designer-0:5.15.3-1.fc36.x86_64
qt5-qttools-libs-help-0:5.15.3-1.fc36.x86_64
qt5-qtwayland-0:5.15.3-2.fc36.x86_64
qt5-qtwebchannel-0:5.15.3-1.fc36.x86_64
qt5-qtwebengine-0:5.15.8-5.fc36.x86_64
qt5-qtwebkit-0:5.212.0-0.63.alpha4.fc36.x86_64
qt5-qtwebsockets-0:5.15.3-1.fc36.x86_64
qt5-qtx11extras-0:5.15.3-1.fc36.x86_64
qt5-qtxmlpatterns-0:5.15.3-1.fc36.x86_64
qt5-srpm-macros-0:5.15.3-1.fc36.noarch
~
 ```
 I think I'm head of the two package versions you mentioned. Do I _really_ need to downgrade them?!
 Note, that the still is pretty much STILL reproducable. I just checked. Let me know what you think @grossmj

**Comment by PranavBhattarai** [comment] 2022-06-23 05:18
@grossmj 
Sorry to ask you this, but this is still labeled as "waiting for information".
Is there something I need to add more?

**Comment by grossmj** [comment] 2022-06-23 08:39
> Is there something I need to add more?

No all good, thanks 👍

**Comment by grossmj** [comment] 2022-10-12 14:33
Regarding the last problem, I am suspecting a Qt bug on F36 with the new GNOME 42. Unfortunately, I don't think we can do anything about it.

**Closed by grossmj** 2022-10-12 14:33 UTC
Labels: Bug

**Comment by PranavBhattarai** [comment] 2022-10-13 03:12
F37 is releasing in few days. Maybe this is solved by then. Anyway, closing the issue looks good to me.
