### ISSUE TITLE
Project folder structure with main server

### ISSUE THREAD

**Issue by Dale-Li** [GNS3/gns3-gui#3174] opened 2021-04-30 14:46 UTC
Is it possible to add a folder structure for the projects saved on the main VM?

so that we can choose "save as" on to different subdirectory.

**Comment by grossmj** [comment] 2021-05-06 05:40
I am not sure I understand. Do you have an example and/or screenshots? Thanks.

**Comment by Dale-Li** [comment] 2021-05-06 11:50
Hello,
It's just like a folder and sub folder. For example, I want store all my CCNA projects in one folder called CCNA, and CCNP projects in another folder. Etc.

Currently, when I go to open project, all the projects are listed without folder structure.
Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Dale-Li** [comment] 2021-05-06 13:58
Hello,
This is the one I wish to have,
When “Save as”, we can create folders. So that I can manage my Project in different folder,
And also good to have the ability to rename project and folders.

Thank you

Dale Q. Li

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by cristian-ciobanu** [comment] 2021-05-06 20:41
I guess this issue is similar or duplicate of this one https://github.com/GNS3/gns3-gui/issues/2233

**Comment by Dale-Li** [comment] 2021-05-06 20:43
Yes, absolutely…

Seems it’s a request a long time ago.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by grossmj** [comment] 2021-05-16 12:49
Duplicate of https://github.com/GNS3/gns3-gui/issues/2233

**Closed by grossmj** 2021-05-16 12:49 UTC
Labels: Duplicate, Enhancement
