### ISSUE TITLE
VPCS does not save his default name

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2381] opened 2018-01-08 16:04 UTC
Hi

I use vpcs 0.6.2

I put on GNS3 a VPCS device : his default name is "VPCS-1"
I start it
His name is : VPCS-1
On OS : cat projects/untitled/project-files/vpcs/794eb714-30c7-41eb-b711-b4f33c91ee21/startup.vpc
`set pcname VPCS-1`

I save his config : save
On OS : cat projects/untitled/project-files/vpcs/794eb714-30c7-41eb-b711-b4f33c91ee21/startup.vpc
The file is empty

If i restart this device, his name is "VPCS"

**Comment by grossmj** [comment] 2018-01-09 10:37
I can reproduce it.

**Comment by grossmj** [comment] 2018-01-09 11:06
This is due to a bug in VPCS. The workaround is to use a very short name (under 5 characters apparently). 

* Use the default VPCS template to create a node and rename it to PC-1 for instance.
* Create a VPCS template in the preferences and use a default name format like PC{0} (the default).

**Comment by Raizo62** [comment] 2018-01-09 14:54
I believe that is 6 characters. 
But i believe that i have see that vpcs wants to save "VPCS\-1"  (7 characters) (but i am not sure)

You cannot change the default name to PC  instead VPCS ?

**Comment by grossmj** [comment] 2018-01-09 16:40
> You cannot change the default name to PC instead VPCS ?

This is what I intend to do.

**Comment by grossmj** [comment] 2018-01-09 16:42
Fixed by https://github.com/GNS3/gns3-server/commit/5f14f8eb46ec9c931a2df9f2b7e00e3b2dea66f7

**Closed by grossmj** 2018-01-09 16:42 UTC
Labels: Bug

**Comment by Raizo62** [comment] 2018-01-16 18:58
I have push on github/VPCS 0.6 a patch to this error (and others). Do you have see it ?
Do you want  that i apply also this patch on VPCS 0.8 ?
