### ISSUE TITLE
[feature request] - cloud which include another topology

### ISSUE THREAD

**Issue by anubisg1** [GNS3/gns3-gui#22] opened 2014-04-28 12:16 UTC
It would be great if we could intergrate a "cloud" feature...

imagine for example, mpls vpns. CE routers connected trough the ISP cloud.
We could have a Main topology where the we would have CE --- CLOUD -- CE 

once we click on the cloud, we would basically zoom into it , and access the cloud itself as topology, where for example we could find the ISP routers connected.

i'm not sure if i was able to explain myself ...

**Comment by noplay** [comment] 2016-09-29 12:03
Duplicate of https://github.com/GNS3/gns3-server/issues/517

**Closed by noplay** 2016-09-29 12:03 UTC
Labels: duplicate, enhancement
