### ISSUE TITLE
gns3 window looses focus with wayland

### ISSUE THREAD

**Issue by jdbrouwer** [GNS3/gns3-gui#1795] opened 2017-01-18 09:58 UTC
system: linux 4.9 (fedora 25)
Display server: wayland (gns3 runs in Xwayland mode) 

- open gns3
- open a new project and add a new router
- double click on said router after it started to open a terminal console
- switch back your window focus to the main gns3 window
- switch to the created terminal window by using any of the following methods (alt + tab, using the super key and selecting the window, or moving to it with the mouse).

- now its impossible to select any of the elements in the main gns3 window (interface buttons for example). It is possible to select the border and maximize / minimize the window however.

i have used different terminal programs, (terminator and gnome-terminal), which seem be unaffected by the issue. I also tried running it in normal X mode (without using wayland) and that seems to still have the same issue.

**Comment by noplay** [comment] 2017-01-18 16:16
What is your windows manager? Sound like an issue with Qt and the windows manager

**Comment by jdbrouwer** [comment] 2017-01-18 16:19
i am using gnome3. (so in terms of window managers, that would just be the default mutter). 
is there anything else i could do to get more information from the window manager itself? (running gns3-gui in a terminal gives no useful output about window status)

**Comment by noplay** [comment] 2017-01-18 16:26
How GNS3 is installed? Via the package from fedora?

**Comment by jdbrouwer** [comment] 2017-01-18 16:31
its installed via the copr/gns3 repository. (which is the only repository that contains gns3 for fedora as far as i am aware). 

url to repo: https://copr.fedorainfracloud.org/coprs/athmane/gns3/

the version of gns3 im running is the following:  GNS 1.5.2 
QT version: 5.7.1

**Comment by noplay** [comment] 2017-01-18 17:09
You should try to report the issue to the author of package, it seem to be a problem with Fedora or a package on fedora. The issue can't be reproduce on other OS or Linux distribution.

But I suspect the issue will be complicated to isolate, because even if Fedora is not the most use distribution in the community we have people using and they will have report a big issue like this.

Do you have a 4K screen? I know that a lot of bugs with 4k or dual screen setup and Qt on some Linux distributions.

**Comment by q2dg** [comment] 2017-02-10 22:56
I'm using Fedora 25 (stock Gnome3 desktop) and I have the same issue too: after opening an (in my case, vpcs) console, it's impossible to select any item (buttons, right-click menu, etc) from main window with the mouse pointer (keyboard shortcuts still works). 

I'm not using 4k screen.

I've installed GNS3 from official repositories (1.5.2 version).

If I login within a X session, this problem disappears.

Thanks a lot

**Comment by q2dg** [comment] 2017-02-13 08:11
Sure!
I get: "This application failed to start because it could not find or load the Qt platform plugin "wayland-egl"
in "". Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, xcb. Reinstalling the application may fix this problem."
Thanks

**Comment by q2dg** [comment] 2017-02-13 08:13
Sorry, for completeness: if I run show version I get "Running GNS3 version 1.5.2 on Linux (64-bit) with Python 3.5.2 Qt 5.7.1."

**Comment by noplay** [comment] 2017-02-13 08:15
Strange it's a part of debugging wayland on the fedora wiki:
https://fedoraproject.org/wiki/How_to_debug_Wayland_problems

Perhaps you need t o install:
https://apps.fedoraproject.org/packages/qt5-qtwayland

**Comment by q2dg** [comment] 2017-02-13 08:26
Yes, you're right!

But running GNS3 like this results in a weird behavior: I can't drag&drop any network device to central area and/or when I move mouse pointer over network device list it doesn't show right devices -or none at all-.

**Comment by noplay** [comment] 2017-02-13 09:50
I will mark as won't fix, because it's not something we can fix the bug is located somewhere in Qt or lower layer. And the fact that changing backend fix the issue mean the bug is not in GNS3 code.

My conclusion:
* Fedora + Qt + Wayland using XWayland is currently buggy but it's close to be working
* Fedora + Qt + Wayland using Qt wayland support is not working for the moment. We need to wait Qt 5.8 for a proper support probably in Fedora 26.

If you want progress in current fedora version you should contact package author perhaps it could isolate the issue and report it to the correct location.  

Fedora is the first major distribution making the switch to wayland. I'm not suprised that you have such bugs :(

**Closed by noplay** 2017-02-13 09:50 UTC
Labels: bug, wontfix
