### ISSUE TITLE
Mac OS Big Sur  gns3 2.2.16 won’t launch just hang 

### ISSUE THREAD

**Issue by benali125** [GNS3/gns3-gui#3093] opened 2020-11-14 02:50 UTC
**Before you start**
Please open an issue only if you suspect there is a bug or any problem with GNS3. Go to https://gns3.com/community for any other questions or for requesting help with GNS3.

You may also post this issue directly on the GNS3 server repository if you know the bug comes from the server: https://github.com/GNS3/gns3-server/issues/new

**Describe the bug**
Please provide a clear and detailed description of what the bug is.

**GNS3 version and operating system (please complete the following information):**
 - OS: [e.g. Windows, Linux or macOS]
 - GNS3 version [e.g. 2.1.14]
 - Any use of the GNS3 VM or remote server (ESXi, bare metal etc.)

**To Reproduce**

**Screenshots or videos**
If applicable, add screenshots (e.g. of the topology and/or error message) or links to videos to help explain the problem. This will help us a lot to quickly find the bug and fix it.

**Additional context**

**Comment by cristian-ciobanu** [comment] 2020-11-14 22:43
This is a duplicate of the following issue https://github.com/GNS3/gns3-gui/issues/3037. You can close this one and continue to check the progress on the existing issue.

**Closed** 2020-11-14 22:47 UTC
Labels: Bug
