### ISSUE TITLE
Gns3 2.2.16 

### ISSUE THREAD

**Issue by benali125** [GNS3/gns3-gui#3087] opened 2020-11-07 19:00 UTC
OS Catalina won’t play nice with gns3 from 2.2.14 release till now 
At first can’t drag appliances 
Then the after upgrading to the 2.2.15 was the docker ce problem 
Now with latest release it seems that there is a problem with library !!!

Dyld Error Message:
  Library not loaded: @executable_path/Python
  Referenced from: /Applications/GNS3.app/Contents/MacOS/gns3

**Comment by grossmj** [comment] 2020-11-29 05:34
Do you confirm v2.2.13 works on Catalina?

**Comment by grossmj** [comment] 2020-12-02 10:01
I don't have any issues on macOS Catalina with 2.2.16 and nobody else complained about it. Are you running some kind of security software that may block or interfere with GNS3?

**Comment by benali125** [comment] 2020-12-02 14:04
I’ve used gns3 for so many years never had issues with ,the problem started with 2.2.14 and later can’t drag appliances 
After switching to Mac OS Big Sur the gns3 app won’t even starts just keeps bouncing 
To answer your question I m not running any security software on my Mac 
In gns3 community discussion there is so threads about différents issues with Mac Catalina from gns3 2.2.14 and later the latest stable and working good was 2.2.13

**Comment by ksinghnote** [comment] 2020-12-04 11:39
Had similar issue then i have deleted the GNS3 and reinstalled it and was able to drag appliances. Mac Big Sur GNS3 2.2.17, but running into different Issue where Cisco IOSvL2# unable to console output but IOU# is working fine.

**Comment by turtlewax** [comment] 2021-04-04 17:32
I'm almost positive this macOS drag problem is a Qt 5.15.1 bug.  Please see my GNS3 community post here for a quick workaround that doesn't involve reinstalling GNS3:

https://www.gns3.com/community/featured/gns3-macos-drag-and-drop-problem-can-devs-please-update-qt-to-5-15-2

**Comment by grossmj** [comment] 2021-04-05 10:11
Duplicate of https://github.com/GNS3/gns3-gui/issues/3152

**Closed by grossmj** 2021-04-05 10:11 UTC
Labels: Bug, Duplicate
