### ISSUE TITLE
Remote server only, import appliance hangs at 99%

### ISSUE THREAD

**Issue by kingfetty** [GNS3/gns3-gui#1915] opened 2017-03-10 17:18 UTC
Server Version: 2.0.rc1
Client Version: 2.0.rc1
Server System: VM imported to ESXi server
Client System: Windows 10

Symptom:  When importing a gns3a the client goes through the wizzard but hanges with a window "Please Wait:  Waiting for http://192.168.1.17:3080".  If you close the box it reappears and starts over and hangs again.  You can kill the entire GNS3 client and start it fresh and the dialog will be gone, however the appliance is not listed in the client.  

If you inspect the GNS3 server images directory, the appliance image did in fact get uploaded to the server.  

Troubleshooting steps done:  Wipe %appdata%\GNS3 on the client computer and recreate everything fresh from the wizard.    I've enabled debug 2 in an attempt to gather any information that would identify the cause.  However, the Please Wait dialog makes it impossible to access the console window and read any of the logs.  On some occasions the appliance is created on the client after killing the process, but the window still hangs at 99% and refuses to go away.

Please let me know if you need any more information to debug this issue.

**Comment by kingfetty** [comment] 2017-03-10 17:21
I've managed to resize the console window enough to gather some information about what's going on.   I notice the host field in the server packets is still showing 127.0.0.1 and not the actual server address.  This appears to be that maybe it's referencing the wrong variable name or a variable is not being saved properly.

**Comment by kingfetty** [comment] 2017-03-10 17:22
None of the ini files appear to have a reference to 127.0.0.1 in them, this must be an internal variable issue.

**Comment by kingfetty** [comment] 2017-03-10 17:31
It appears the 127.0.0.1 is coming from the JSON reply of the GNS3 server:

Event received: {'action': 'ping', 'event': {'cpu_usage_percent': 100.0, 'memory_usage_percent': 4.7}}
Event received: {'action': 'ping', 'event': {'cpu_usage_percent': 100.0, 'memory_usage_percent': 4.7}}
GET http://192.168.1.17:3080/v2/computes {}
GET http://192.168.1.17:3080/v2/computes {}
Decoding response from http://192.168.1.17:3080/v2/computes response 200
Decoding response from http://192.168.1.17:3080/v2/computes response 200
[
    {
        "capabilities": {
            "node_types": [
                "cloud",
                "ethernet_hub",
                "ethernet_switch",
                "nat",
                "vpcs",
                "virtualbox",
                "dynamips",
                "frame_relay_switch",
                "atm_switch",
                "qemu",
                "vmware",
                "docker",
                "iou"
            ],
            "platform": "linux",
            "version": "2.0.0rc1"
        },
        "compute_id": "local",
        "connected": true,
        "cpu_usage_percent": 0.2,
        "host": "127.0.0.1",
        "memory_usage_percent": 4.7,
        "name": "Main server",
        "port": 3080,
        "protocol": "http",
        "user": null
    }
]
[
    {
        "capabilities": {
            "node_types": [
                "cloud",
                "ethernet_hub",
                "ethernet_switch",
                "nat",
                "vpcs",
                "virtualbox",
                "dynamips",
                "frame_relay_switch",
                "atm_switch",
                "qemu",
                "vmware",
                "docker",
                "iou"
            ],
            "platform": "linux",
            "version": "2.0.0rc1"
        },
        "compute_id": "local",
        "connected": true,
        "cpu_usage_percent": 0.2,
        "host": "127.0.0.1",
        "memory_usage_percent": 4.7,
        "name": "Main server",
        "port": 3080,
        "protocol": "http",
        "user": null
    }
]

**Comment by kingfetty** [comment] 2017-03-10 17:35
I have manged to gather the entire debug session data and uploaded it to:

https://pastebin.com/3xFcKi95

**Comment by syndgr** [comment] 2017-03-10 23:46
I am also seeing this issue but with 2.0.0rc2. Same set up, I am using a remote main server.

I have referenced this particular bug along with another issue here: https://www.gns3.com/qa/remote-main-server-bug-2-0-0rc2

**Comment by noplay** [comment] 2017-03-13 09:02
What is the size of images you are uploading?

**Comment by syndgr** [comment] 2017-03-13 10:53
It appears as though the image does get uploaded to the remote main server when using "Import appliance". I am experimenting with NETem (image is 25Mb).

Steps that I take to always reproduce the issue:

1. Load GNS3 GUI and select my "Remote" profile. This uses a remote main server.
2. File > Import appliance.
3. Select NETem gns3a file.
4. Run through import wizard.
5. Image will start to upload and does complete (can see image and the md5sum file under /opt/gns3/images/QEMU).
6. GNS3 GUI indicates the appliance was installed but the "Please wait" diaglog now shows forever:
![image](https://cloud.githubusercontent.com/assets/20760738/23851350/149b50d4-07db-11e7-9fac-bc5c9f8f452c.png)
7. Can click close (X) on the please wait dialog but it immediately returns. Even after closing the import wizard:
![image](https://cloud.githubusercontent.com/assets/20760738/23851381/38b9ffec-07db-11e7-97f2-abb0d72d659c.png)

Note that each time I click close (X) on the please wait dialog and it re-opens, it gets to 100% twice and on the 3rd time starts to hang around 50%, then 66% etc. and after a long time will get to 99% but will never complete.

**Comment by kingfetty** [comment] 2017-03-13 12:08
The image size does not matter, I've experienced the issue 100% of the time with every image size. from 25MB to Gigs.  As stated before, the image does in fact get uploaded, you can ssh into the server and do an ls and see them physically there.

**Comment by noplay** [comment] 2017-03-13 19:24
Do you cancel the progress dialog when it's running? Before the file is 100% sent to the server. It the only I found to replicate the trouble.

Note that Qt progress is not good when we upload it's often grow fast and slow down at the end.

**Comment by syndgr** [comment] 2017-03-13 20:15
@noplay the image gets uploaded to the remote main server 100%.

I can reproduce the issue on macOS as well as on Windows.

No QEMU images on remote main server:
![image](https://cloud.githubusercontent.com/assets/20760738/23872763/723fa112-0827-11e7-9ba6-67fd20b7e43c.png)

Start appliance import:
![image](https://cloud.githubusercontent.com/assets/20760738/23872988/5b063eba-0828-11e7-9500-92a53b96ea6c.png)

Remote main server to run appliance:
![image](https://cloud.githubusercontent.com/assets/20760738/23873006/6ee62d78-0828-11e7-9b97-bec1e4311103.png)

Appliance files downloaded and ready to install:
![image](https://cloud.githubusercontent.com/assets/20760738/23873032/8a7c49e6-0828-11e7-8d55-6e89dc0af0cb.png)

Image gets uploaded. **This completes**:
![image](https://cloud.githubusercontent.com/assets/20760738/23873053/a01a6ada-0828-11e7-80a5-a2d85027ce4e.png)

And we confirm this on remote main server:
![image](https://cloud.githubusercontent.com/assets/20760738/23873068/ad15731a-0828-11e7-84ef-b4bfdc358023.png)

GUI tells us that the appliance has been installed. **But this is when the "Please wait" dialog now appears**:
![image](https://cloud.githubusercontent.com/assets/20760738/23873117/d52ee6b0-0828-11e7-9345-82906e5570ed.png)

This "Please wait" dialog never completes.

After about 5 minutes, it has progressed to 98%:
![image](https://cloud.githubusercontent.com/assets/20760738/23873189/0378ea8e-0829-11e7-8f0c-a121ee731c02.png)

If I now press Escape or press X to close the dialog, it just re-appears every time. Sometimes I see this:
![image](https://cloud.githubusercontent.com/assets/20760738/23873238/3dcb8f52-0829-11e7-8fb1-203e66004d6b.png)

But this always completes and again I get the please wait:
![image](https://cloud.githubusercontent.com/assets/20760738/23873262/5809bb14-0829-11e7-8c46-f5948c3c3812.png)

I can keep pressing Escape to close the dialog and quickly press buttons but it just keeps re-appearing:
![image](https://cloud.githubusercontent.com/assets/20760738/23873305/8099f972-0829-11e7-88e7-4f859512a225.png)

The only way to stop "Please wait" dialog is to quit GNS3 GUI.

@kingfetty Please confirm that this is what you're seeing too. It sounds like it is.

@noplay I hope the screenshots are useful!

**Comment by kingfetty** [comment] 2017-03-14 03:16
The issue occurs 100% of the time with no canceling.  I have let it sit at 99% for hours to see if it would ever complete and it did not.

Things to note:

Running client in remote main mode only
Server is on an esxi host with the RC1 ESXi image released (not an upgrade of an old image)
Server has dedicated static IP
Authentication is disabled ( have tried to enable, but there's another bug there)
VM has been granted 8gig ram and 4 processor cores
Disk has been tried as thin and thick provisioned both have the issue.

I have not tried with an old VM image that has been upgraded to see if the issue occurs then.  I will download and old Beta image and attempt this to see if anything changes.

**Comment by kingfetty** [comment] 2017-03-14 03:49
Update:

I downloaded the Beta 4 esxi image and uploaded it to my hypervisor. But left the client @ RC2.  I did not have this issue previously on the Beta4 version.  The issue persists if I have the RC2 client installed, indicating the issue is a GNS3 Client.

Also to note, If I turn on local server with remote server added as well, when I upload to the remote server the progress bar indicates 127.0.0.1 and still hangs at 99%

**Comment by kingfetty** [comment] 2017-03-14 03:59
I have uninstalled the client and installed Beta4 and all works fine.  This is an issue that was introduced with RC1

**Comment by noplay** [comment] 2017-03-14 16:08
Could you try this build:
https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2017-03-14/2.0/GNS3-2.0.2017-03-14-all-in-one.exe/download

I'm not able to reproduce the issue on the machines available for the test :(

**Comment by syndgr** [comment] 2017-03-14 17:05
@noplay Unfortunately the nightly build that includes commit 7fdf42b442c9e9542a318dd97c2e0258acedcee7 has made no difference for me.

**Comment by noplay** [comment] 2017-03-14 17:07
Do you have an antivirus running?

**Comment by syndgr** [comment] 2017-03-14 17:10
On my Windows machine, yes.

But this is reproducable on my macOS machine as well, which has no AV running.

**Comment by noplay** [comment] 2017-03-14 17:13
And the connection to the ESXi is direct? No proxy in the middle?

**Comment by noplay** [comment] 2017-03-14 17:23
Could you test this build on OSX:
https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2017-03-14/2.0/GNS3-2.0.0dev11.dmg/download

**Comment by syndgr** [comment] 2017-03-14 17:41
Correct. No proxy.

I have run Wireshark on my Windows machine to take a capture just before the "Please wait" happens to try to see what is happening but it is not very conclusive. All I see are the usual periodic GET requests for /v2/computes:

`GET /v2/computes HTTP/1.1
Authorization: Basic Z25zMzpnbnMz
User-Agent: GNS3 QT Client v2.0.0dev11
Content-Type: application/json
Content-Length: 2
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
Accept-Language: en-GB,*
Host: 192.168.228.110:3080

{}HTTP/1.1 200 OK
Server: Python/3.4 GNS3/2.0.0rc2
X-Route: /v2/computes
Connection: close
Content-Type: application/json
Content-Length: 787
Date: Tue, 14 Mar 2017 17:10:11 GMT

[
    {
        "capabilities": {
            "node_types": [
                "cloud",
                "ethernet_hub",
                "ethernet_switch",
                "nat",
                "vpcs",
                "virtualbox",
                "dynamips",
                "frame_relay_switch",
                "atm_switch",
                "qemu",
                "vmware",
                "docker",
                "iou"
            ],
            "platform": "linux",
            "version": "2.0.0rc2"
        },
        "compute_id": "local",
        "connected": true,
        "cpu_usage_percent": 0.1,
        "host": "127.0.0.1",
        "memory_usage_percent": 2.0,
        "name": "Main server",
        "port": 3080,
        "protocol": "http",
        "user": "gns3"
    }
]`

I will try the OSX build and let you know what happens.

**Comment by syndgr** [comment] 2017-03-14 18:13
I ran gns3.exe with --debug and redirected stdout to nul so I could see stderr better.

Firstly, when I go to File > Import appliance and open a .gns3a file, the following is seen:

```
Windows fatal exception: code 1073807370

Current thread 0x00001070 (most recent call first):
  File "./gns3-gui\gns3\qt\__init__.py", line 81 in getOpenFileName
  File "./gns3-gui\gns3\main_window.py", line 355 in openApplianceActionSlot
  File "./gns3-gui\gns3\qt\__init__.py", line 240 in func_wrapper
  File "gns3-gui/gns3/main.py", line 289 in main
  File "gns3-gui/gns3/main.py", line 307 in <module>
  File "C:\Python36-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24 in <module>
  File "<frozen importlib._bootstrap>", line 616 in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 646 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 950 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 961 in _find_and_load
  File "C:\Python36-x64\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12 in <module>
  File "<frozen importlib._bootstrap>", line 616 in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 646 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 950 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 961 in _find_and_load
Windows fatal exception: code 1073807366

Current thread 0x00001070 (most recent call first):
  File "./gns3-gui\gns3\qt\__init__.py", line 81 in getOpenFileName
  File "./gns3-gui\gns3\main_window.py", line 355 in openApplianceActionSlot
  File "./gns3-gui\gns3\qt\__init__.py", line 240 in func_wrapper
  File "gns3-gui/gns3/main.py", line 289 in main
  File "gns3-gui/gns3/main.py", line 307 in <module>
  File "C:\Python36-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24 in <module>
  File "<frozen importlib._bootstrap>", line 616 in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 646 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 950 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 961 in _find_and_load
  File "C:\Python36-x64\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12 in <module>
  File "<frozen importlib._bootstrap>", line 616 in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 646 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 950 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 961 in _find_and_load
```

I think the above is most likely a seperate issue to the "Please wait" issue we're talking about here.

But then every time I trigger the "Please wait" dialog, the following is seen:

```
QObject: Cannot create children for a parent that is in a different thread.
(Parent is HTTPClient(0x1a5f9543b50), parent's thread is QThread(0x1a5f3b9d940), current thread is QThread(0x1a5faaeeca0)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QNetworkAccessManager(0x1a5f9543f40), parent's thread is QThread(0x1a5f3b9d940), current thread is QThread(0x1a5faaeeca0)
```

**Comment by kingfetty** [comment] 2017-03-14 20:53
Confirmed the build you posted does not remedy the issue for me either.  I would suggest reviewing the commits betwwen Beta 4 and RC1 for GNS3-gui

**Comment by syndgr** [comment] 2017-03-15 13:37
I've cloned gns3-gui so that I can play around with this. Not that I am very well versed in Python but I'm willing to learn... :)

So I have https://github.com/GNS3/gns3-gui/commit/5038a72610c71d07e79639c67bc8b158150d2129 in my local working repo and Qt 5.7.1 still does not resolve this :(

![image](https://cloud.githubusercontent.com/assets/20760738/23950738/edd2ac90-0983-11e7-999e-19f838b225ad.png)

From what I can tell, this issue appears to be with the following in appliance_wizard.py:

```python
        worker = WaitForLambdaWorker(lambda: config.save(), allowed_exceptions=[ConfigException, OSError])
        progress_dialog = ProgressDialog(worker, "Add appliance", "Install the appliance...", None, busy=True, parent=self)
        progress_dialog.show()
        if progress_dialog.exec_():
            QtWidgets.QMessageBox.information(self.parent(), "Add appliance", "{} installed!".format(appliance_configuration["name"]))
            return True
```

It seems as though this call to ProgressDialog() causes:

```
QObject: Cannot create children for a parent that is in a different thread.
(Parent is HTTPClient(0x133b5b50), parent's thread is QThread(0xacd2b0), current thread is QThread(0x14599cd8)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QNetworkAccessManager(0x133b5990), parent's thread is QThread(0xacd2b0), current thread is QThread(0x14599cd8)
```

If in progress_dialog.py I comment out:

```
self._worker.moveToThread(self._thread)
```

This issue is resolved.

But I'm not sure what other consequence this has right now.

**Comment by noplay** [comment] 2017-03-15 14:28
Could you try the last commit? It should raise an error if the progress dialog is not created from the correct thread. This will help us to locate the culprit code.

**Comment by syndgr** [comment] 2017-03-15 15:06
The following is now assert'd in the GUI console pane:

```
QObject: Cannot create children for a parent that is in a different thread.
(Parent is HTTPClient(0x145924a8), parent's thread is QThread(0x3aa8a40), current thread is QThread(0x1532df18)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QNetworkAccessManager(0x14592528), parent's thread is QThread(0x3aa8a40), current thread is QThread(0x1532df18)
```

**Comment by syndgr** [comment] 2017-03-15 15:09
![2017-03-15_15h03_02](https://cloud.githubusercontent.com/assets/20760738/23955260/50e8fc46-0991-11e7-9352-c7011a12fc37.png)

**Comment by noplay** [comment] 2017-03-15 15:12
Hmm but no stacktrace

**Comment by syndgr** [comment] 2017-03-15 15:27
Correct. No stack trace.

It looks as though it was commit https://github.com/GNS3/gns3-gui/commit/3e8208a117d58d2097d129785c5b9f15a380ae12#diff-671af026d82b98e43611a9a47123ef59 that broke this.

Before this commit it works. After this commit this issue is triggered.

**Comment by noplay** [comment] 2017-03-15 15:27
@syndgr you are running GNS3 on Windows 32 bit?

**Comment by syndgr** [comment] 2017-03-15 15:34
@noplay No, 64-bit Windows but remember I can also reproduce this on OSX.

Regarding my other comment (commit https://github.com/GNS3/gns3-gui/commit/3e8208a117d58d2097d129785c5b9f15a380ae12), if I comment out `self._cleanup()` in accept() of progress_dialog.py, therefore undoing commit https://github.com/GNS3/gns3-gui/commit/3e8208a117d58d2097d129785c5b9f15a380ae12 for progress_dialog.py, this issue goes away. Although I have not tested it under OSX yet.

**Comment by noplay** [comment] 2017-03-15 15:35
Ok but look like the python installed is a 32 bit edition we see that in the console.

**Comment by noplay** [comment] 2017-03-15 15:59
Can you test the branch fix_hang?

**Comment by syndgr** [comment] 2017-03-15 16:11
@noplay Good spot, sir! :) I've uninstalled Python 3.6.0 32-bit and installed Python 3.6.0 64-bit in my dev environment. I've also configured my dev environment again (e.g. `pip install -r requirements.txt & pip install -r win-requirements.txt`).

I've switched to brand fix_hang but the issue is still there.

![image](https://cloud.githubusercontent.com/assets/20760738/23958444/0df0b4ca-099a-11e7-914b-20385a3294e9.png)

**Comment by noplay** [comment] 2017-03-15 17:53
And it's the only action that trigger the error in the console? When
working on a topology it's work fine?

**Comment by syndgr** [comment] 2017-03-15 18:30
At this stage I would say yes, that is correct. It is only the appliance import that seems to trigger this.

I will continue to test, especially now that I see fixes for #1923, #1924, #1925, #1926, #1927 which were causing problems for me with my set up.

FYI, I have created a dev environment under OSX now so I can test the fix_hang branch on both Windows and OSX. Right now, fix_hang branch is showing the same issue still under OSX and Windows.

I will update when I have done more testing to see if the assert is only triggered when using appliance import...

**Comment by kingfetty** [comment] 2017-03-16 04:56
I've been doing some debugging and logging to a file over here to see if I can figure out what's going on.  The client appears to be looping "http://192.168.1.17:3080/v2/settings" and looking for the template that was just uploaded.  Since the template is not appearing in the list it's just doing it over and over again.  The question then is why is it not in the list?  I suspect it's not properly being uploaded to the server.  

If I run server beta4 and client RC1/2 the issue exists
If I run server RC1/2 and  client beta 4 the issue doesn't exist

I suspect something in the upload code is preventing the server side configuration from being created.

**Comment by kingfetty** [comment] 2017-03-16 05:15
So it appears config.save is running an HTTP POST in order to send the config to the server.  This HTTP POST is what's triggering  the "Cannot create children for a parent that is in a different thread" from the HTTPClient object.

**Comment by noplay** [comment] 2017-03-16 08:20
Thank you!

**Comment by noplay** [comment] 2017-03-16 11:20
Can you try the fix_hang2 branch

**Comment by syndgr** [comment] 2017-03-16 11:33
That works. Tested it several times now with different QEMU images (ranging from 25Mb to 1.2Gb). Works as expected. assert is not triggered.

Let me know if there are some specific tests you'd like me to run.

**Comment by noplay** [comment] 2017-03-16 11:36
Thanks a lot !

**Closed by noplay** 2017-03-16 11:36 UTC
Labels: bug

**Comment by kingfetty** [comment] 2017-03-16 13:22
Confirmed working for me as well.  Also confirmed configuration is actually on the server.

**Comment by noplay** [comment] 2017-03-16 13:26
Thanks for the update.
