### ISSUE TITLE
[bug 1.4.0rc1] console port range used

### ISSUE THREAD

**Issue by Technologov** [GNS3/gns3-gui#846] opened 2015-12-02 08:41 UTC
Host: Win 7, GNS3 v1.4.0-rc1. Local server.
 
After installing on a fresh system, and adding an IOS image, I get error "console range is reserved for VNC".
See screenshot.

![console-port-used](https://cloud.githubusercontent.com/assets/1480628/11526156/385cf0b4-98e1-11e5-8019-9d9701106b50.png)

 
-Technologov

**Comment by noplay** [comment] 2015-12-02 11:24
Duplicate of #839 
Thanks for the report

**Closed by noplay** 2015-12-02 11:24 UTC
Labels: bug, duplicate
