### ISSUE TITLE
[2.0] : Req/Idea : open bad project

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1890] opened 2017-02-25 11:50 UTC
Hi

Sorry, i don't find the issue where we talked about GNS3 which doesn't open projects with errors.
In this case, we can't backup the corrects files or remove bad devices.
it seems to me that you want only good projects to export.

An idea : add an option to GNS3 (--withoutfailure, for example). With this option, GNS3 opens project, even with error, but you can't start devices, or add new device. You can only move or delete device/link.

But, i don't know if this is hard to add this to your architecture.

**Comment by noplay** [comment] 2017-02-27 08:08
The problem if you open a corrupt project we will remove from the topology the non working stuff and with auto save this will be immediately save on disk.  Actually their is no easy way to allow you to patch the topology.

Perhaps solving error need to be a dedicated interface with few options (remove a node, change an interface for the cloud).

**Comment by Raizo62** [comment] 2017-02-27 12:44
I think that the dedicated interface asks more works than a boolean who disable functionality.

With this mode, you can edit the topology to copy-paste the configs of IOS.
You can also delete the bad devices and to reload after the project with GNS3 without the option, then you can upgrade your topology

To have a little of the topology is better than to have nothing.

I don't see how you can export bad projet.

If you don't want lose your project, you can do a backup before, especially that you must start by to add an option to command line of gns3 to have this functionality.

**Comment by noplay** [comment] 2017-02-27 16:11
Supporting half topology mean all part of GNS3 need to support it, it's far away to be simple. And that mean also that anything interacting with a GNS3 topology need to support it (third parties client).

Actually the only real trouble preventing you to open a topology is when you have a missing compute node.

For example you use the GNS3 VM and now the VM is no longer available. This also mean we have missing datas (configuration file, backing disk).

We should not display the topology it's too common that user break the VM, they will ignore the error message and complaints that they have lost the configuration of their devices or their devices disappear.  In this case you are not suppose to fix the topology you need to fix the installation.

**Comment by Raizo62** [comment] 2017-02-27 18:48
There are also when you have the bad reference of linked clone.

I think the idea is a good solution with newbies ; if they want to modify, then they must start GNS3 with the parameter ; they can only delete device and they cannot start the VMs. They must stop GNS3 and restart GNS3 without the parameter. it is not easy.

But, yes, it is perhaps hard for GNS3  to open a bad project without save it . How to connect good device to bad device. You must create fake device to replace. And when we stop GNS3, if the bad device exists again, you must replace it by the originate.

**Comment by noplay** [comment] 2017-02-28 09:53
You mean you deleted the base VirtualBox machine?

**Comment by Raizo62** [comment] 2017-02-28 14:08
Yes, for example.
But most often, i recompile the VM Raizo, then the reference changes, then i cannot open old backup.
Or i don't have the used VM : For example, i talked you of a bug in project of another teacher, who used a big nagios VM. You couldn't open the lab because you don't have the VM nagios

**Comment by grossmj** [comment] 2023-01-31 02:17
Duplicate of https://github.com/GNS3/gns3-server/issues/1902

**Closed by grossmj** 2023-01-31 02:17 UTC
Labels: Enhancement
