### ISSUE TITLE
feature request : Layers Dock

### ISSUE THREAD

**Issue by saviodsouza** [GNS3/gns3-gui#3115] opened 2021-01-07 07:01 UTC
Clicking view - show layers. only shows the layers of devices.
If it is converted into a dock like the others it can explore more options like
- Hide / show devices on that layer. (right click menu option for each layer)
- Rename layers ( HQ, BranchOffice1, BranchOffice2, Network, Servers, Desktops, etc)
- Start / Stop devices on a layer. (right click menu option for each layer).

when you work on a large project with lots of devices. you can't start all devices at the same time. Right now you need to start each one manually. By putting different devices on each layer, managing them can be easy..

Regards,
sd

**Comment by b-ehlers** [comment] 2021-01-07 10:09
Looks like a duplicate of https://github.com/GNS3/gns3-gui/issues/2647

**Closed** 2021-01-10 07:08 UTC
Labels: Duplicate, Enhancement
