### ISSUE TITLE
Move nodes to another server

### ISSUE THREAD

**Issue by dmfigol** [GNS3/gns3-gui#1953] opened 2017-03-21 09:21 UTC
This is an enhancement request.
Currently there isn't a good way to move an existing node to another server. Most likely a user will need to add a new node from scratch/appliance.
It would be great if there was an ability to move an existing node to another server.
Let's take IOL node for example.
When I edit a node I would like to see a button "change server", when I click on it, I can specify one of my servers (local/remote) and the image will be transferred from the current server to the new server and settings will be updated. If the image can't be transferred, prompt a user to supply an image once again.

**Comment by noplay** [comment] 2017-03-21 09:27
Cool be great, complex to develop but great

**Comment by grossmj** [comment] 2017-07-13 09:56
Duplicate of https://github.com/GNS3/gns3-server/issues/575

**Closed by grossmj** 2017-07-13 09:56 UTC
Labels: Duplicate, Enhancement
