### ISSUE TITLE
Notes feature request

### ISSUE THREAD

**Issue by vint66** [GNS3/gns3-gui#2593] opened 2018-09-20 16:49 UTC
Hi GNS3 team,

Would be nice to have option to add NOTEs to VM templates in GNS3 GUI. So, we can use it by adding comments about specific VM, username/password etc.

**Comment by grossmj** [comment] 2018-10-02 14:35
Duplicate of https://github.com/GNS3/gns3-server/issues/1298

**Closed by grossmj** 2018-10-02 14:35 UTC
Labels: Duplicate, Enhancement
