### ISSUE TITLE
Duplicate nodes

### ISSUE THREAD

**Issue by dmfigol** [GNS3/gns3-gui#1954] opened 2017-03-21 09:30 UTC
This is an enhancement request.
Every so often I add essentially the same node but different software version. For example, new CSR/IOL version.
It would be great if there was an ability to duplicate an existing node with a wizard prompting for an image/server (very much like creating a new node) so that the only thing I need to do is provide a new image/server name. I don't want to create a new node from scratch, because I can use some custom settings for the node (RAM/ports/base-config). It is especially painful for custom (non-appliance) QEMU VMs.
It can be the 4th button "Duplicate" among "New", "Edit", "Delete" in the nodes list.

**Comment by noplay** [comment] 2017-03-21 09:32
Duplicate of: https://github.com/GNS3/gns3-gui/issues/1065

It's not easy especially with problem like mac address, ssh key initialization...

**Comment by noplay** [comment] 2017-03-21 09:47
Sorry I miss read the initial thread.

Personnaly I don't see a real benefits compare to the complexity added to the application. It's really quick to follow the wizard for recreating a new appliance.

What I see is the need of a new flow for creating an appliance in order to skip three input: RAM, CPU (and default is correct in most cases) and adapters. Did I miss something?

**Comment by dmfigol** [comment] 2017-03-21 10:10
1. Not all nodes are imported using appliance
2. For nodes like IOL, I always manually change RAM/number of interfaces/hostname/base config. 
3. For QEMU nodes not from appliance I will use more or less the same template (qemu binary, qemu options)
4. Almost always I change hostname format.

**Comment by noplay** [comment] 2017-03-21 10:27
Do you create often new template like that?

**Comment by dmfigol** [comment] 2017-03-21 10:30
No, but I use IOL much more than QEMU VMs. And for IOL it is a little bit annoying to change settings every time I have a new version.

**Comment by noplay** [comment] 2017-03-21 10:54
I move that in To Be Defined milestone. Not sure if one day we will add it.

I'm not big fan of the idea because i'ts add one more way to create an appliance template.

**Comment by grossmj** [comment] 2017-08-07 06:07
This has been implemented in version 2.1

**Closed by grossmj** 2017-08-07 06:07 UTC
Labels: Enhancement
