### ISSUE TITLE
Error transferring http://admin@localhost:3080/v2/projects/load - server replied: Forbidden (localhost:3080)

### ISSUE THREAD

**Issue by aryapramudika** [GNS3/gns3-gui#3159] opened 2021-04-01 09:09 UTC
Hello, I can't open my recent project 

Log Error:

> => Error transferring http://admin@localhost:3080/v2/projects/load - server replied: Forbidden (localhost:3080)
> Error transferring http://admin@localhost:3080/v2/projects/load - server replied: Forbidden (localhost:3080)

in systemctl status gns3-server@arya

> Apr 01 15:54:11 arch gns3server[354]: 2021-04-01 15:54:11 INFO web_log.py:206 ::1 [01/Apr/2021:08:54:11 +0000] "POST /v2/compute/projects/de6dbd19-e92f-48f2-965b-e3f5d1ed989e/nat/nodes/a9d06a86-db5c-4ac2-93ec-7e83d959068a/stop HTTP/1.1" 204 224 "-" "Python/3.9 aioht>
> Apr 01 15:54:11 arch gns3server[354]: 2021-04-01 15:54:11 INFO web_log.py:206 127.0.0.1 [01/Apr/2021:08:54:11 +0000] "POST /v2/compute/projects/de6dbd19-e92f-48f2-965b-e3f5d1ed989e/vpcs/nodes/e10b3be5-1e2e-47bc-96e8-33aef0b9818c/stop HTTP/1.1" 204 225 "-" "Python/3.>
> Apr 01 15:54:12 arch gns3server[354]: 2021-04-01 15:54:12 INFO base_node.py:331 VPCS: 'PC1' [e10b3be5-1e2e-47bc-96e8-33aef0b9818c]: is closing
> Apr 01 15:54:12 arch gns3server[354]: 2021-04-01 15:54:12 INFO base_node.py:331 Builtin: 'NAT1' [a9d06a86-db5c-4ac2-93ec-7e83d959068a]: is closing
> Apr 01 15:54:12 arch gns3server[354]: 2021-04-01 15:54:12 INFO base_node.py:669 Stopping uBridge hypervisor localhost:42611
> Apr 01 15:54:12 arch gns3server[354]: 2021-04-01 15:54:12 INFO hypervisor.py:208 Stopping uBridge process PID=2470
> Apr 01 15:54:12 arch gns3server[354]: 2021-04-01 15:54:12 INFO cloud.py:248 Cloud "NAT1" [a9d06a86-db5c-4ac2-93ec-7e83d959068a] has been closed
> Apr 01 15:54:12 arch gns3server[354]: 2021-04-01 15:54:12 INFO project.py:361 Project de6dbd19-e92f-48f2-965b-e3f5d1ed989e with path '/home/arya/GNS3/projects/Test' closed
> Apr 01 15:54:12 arch gns3server[354]: 2021-04-01 15:54:12 INFO web_log.py:206 ::1 [01/Apr/2021:08:54:12 +0000] "POST /v2/compute/projects/de6dbd19-e92f-48f2-965b-e3f5d1ed989e/close HTTP/1.1" 204 205 "-" "Python/3.9 aiohttp/3.7.3"
> Apr 01 15:54:49 arch gns3server[354]: 2021-04-01 15:54:49 INFO web_log.py:206 ::1 [01/Apr/2021:08:54:49 +0000] "GET /v2/computes HTTP/1.1" 200 1018 "-" "GNS3 QT Client v2.2.19"

GNS3 Version
2.2.19 installed from AUR
OS : Arch Linux 

I follow this solved issue but not work
https://github.com/GNS3/gns3-gui/issues/2083

file permission and owner

![image](https://user-images.githubusercontent.com/61450033/113270332-8c1fa080-9303-11eb-9ce7-4ae9024b28c4.png)

please, help me

**Comment by ichsanputr** [comment] 2021-04-06 13:32
nice

**Comment by grossmj** [comment] 2021-05-06 05:53
What params are used to start the gns3server process?

**Comment by grossmj** [comment] 2021-06-03 10:07
Duplicate of https://github.com/GNS3/gns3-gui/issues/2871

**Closed by grossmj** 2021-06-03 10:07 UTC
Labels: Duplicate
