### ISSUE TITLE
"wait for http://localhost:3080", all the time,I cant open my project.

### ISSUE THREAD

**Issue by yu-xxhhxx** [GNS3/gns3-gui#3112] opened 2020-12-17 06:51 UTC
**Before you start**
Please open an issue only if you suspect there is a bug or any problem with GNS3. Go to https://gns3.com/community for any other questions or for requesting help with GNS3.

You may also post this issue directly on the GNS3 server repository if you know the bug comes from the server: https://github.com/GNS3/gns3-server/issues/new

**Describe the bug**
Please provide a clear and detailed description of what the bug is.
I create a new project,and save it.then I open this project,a window alert show: Please wait,Waitting for http://localhost:3080,and it has been loading.
**GNS3 version and operating system (please complete the following information):**
 - OS: Windows 10 1909
 - GNS3 version 2.2.17
 - Any use of the GNS3 VM or remote server (ESXi, bare metal etc.)

**To Reproduce**
1. Open GNS3
2. Create a new blank project
3. Build a simple network
4. Save project as...
5. Open GNS3,open project
6. See error

**Screenshots or videos**
If applicable, add screenshots (e.g. of the topology and/or error message) or links to videos to help explain the problem. This will help us a lot to quickly find the bug and fix it.
![image](https://user-images.githubusercontent.com/51101525/102453065-7351ee80-4076-11eb-9e5a-888399974eff.png)

**Additional context**
I am new to use GNS3.

**Comment by yu-xxhhxx** [comment] 2020-12-17 06:55
One more thing, I saved the project on disk D instead of the default path: disk C.

**Comment by yu-xxhhxx** [comment] 2020-12-17 07:12
Just now I reopen my project,the error is Dynamips error when running command 'nio create_udp udp-c2d07021-1373-4af7-a2e1-c2ccef5a2f18 10010,then I detect my 10010 port,NVDIA Web Helper.exe occupied my port,so I change my gns3's port to 13000-20000.Restart GNS3,then the waiting progress bar stops at 92%.

**Comment by yu-xxhhxx** [comment] 2020-12-17 07:13
![20201217151309](https://user-images.githubusercontent.com/51101525/102455362-74851a80-407a-11eb-9fbf-10309a7f802d.png)

**Comment by grossmj** [comment] 2021-06-03 10:05
Duplicate of https://github.com/GNS3/gns3-gui/issues/2834

We have plans to use asyncio with Qt to improve the situation.

**Closed by grossmj** 2021-06-03 10:05 UTC
Labels: Bug, Duplicate

**Comment by Amine212** [comment] 2022-01-11 14:44
The image c3640-ik9o3s-mz.124-25b.image is missing

**Comment by Totodatacoucou** [comment] 2023-11-10 09:36
la même probleme avec localhost 3080
<img width="843" alt="localhost 3080" src="https://github.com/GNS3/gns3-gui/assets/125027683/047b10ad-6aa2-4d52-bda4-762aeb060d6c">

**Comment by DogguG** [comment] 2024-11-07 13:22
did you fixed it ?
