### ISSUE TITLE
Option to suspend the communication via a link from the gui

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#1294] opened 2016-06-08 13:28 UTC
as far as I can understand you have tunnels connecting various types of device interfaces
allow the user to disable a link (stop the communication via a tunnel) and reflect the status of the link by the color of that link (make it red let's say)

**Comment by noplay** [comment] 2016-06-08 14:50
Duplicate of #1295

**Closed by noplay** 2016-06-08 14:50 UTC
Labels: duplicate
