### ISSUE TITLE
VMWare 6.0 Virtual Network Issue

### ISSUE THREAD

**Issue by skreitler** [GNS3/gns3-gui#2757] opened 2019-04-02 17:38 UTC
I have an issue with 2.2.0 and my vmware ESXi.  When it has one NIC, it shows as Eth0, but if I add more NICs, then it moves to Eth1.  Anyway to have it remain as Eth0?

**Comment by grossmj** [comment] 2019-04-03 06:53
To understand correctly, you have imported the GNS3 VM version 2.2.0a3 into ESXi and if you start it with more than one NIC, the eth0 interface becomes eth1, is this right? Please include some screenshots if you can. Thanks.

**Comment by skreitler** [comment] 2019-04-03 13:39
You are correct.  Please see screenshots
<img width="784" alt="GNS3VM Settings 2 NIC" src="https://user-images.githubusercontent.com/49206867/55483301-4df82500-55f4-11e9-95b5-f3f5332f545c.png">
<img width="1136" alt="GNS3VM ifconfig 2 NIC" src="https://user-images.githubusercontent.com/49206867/55483304-4df82500-55f4-11e9-9671-c852cb738641.png">
<img width="1136" alt="GNS3VM ifconfig 1 NIC" src="https://user-images.githubusercontent.com/49206867/55483305-4df82500-55f4-11e9-8ae4-3089cad396d1.png">
<img width="783" alt="GNS3VM Settings 1 NIC" src="https://user-images.githubusercontent.com/49206867/55483306-4df82500-55f4-11e9-82af-28bcc4cadd8f.png">

**Comment by grossmj** [comment] 2019-04-09 16:52
I couldn't reproduce the problem, have you configured a static IP address for the first interface?

![network_config_1](https://user-images.githubusercontent.com/4752614/55819145-584d7e00-5b22-11e9-8331-6a08054f8caa.png)

![network_config_2](https://user-images.githubusercontent.com/4752614/55819144-57b4e780-5b22-11e9-869d-f7be24ac1fe3.png)

**Comment by skreitler** [comment] 2019-04-09 17:34
Yes I have.

**Comment by skreitler** [comment] 2019-04-09 21:59
I created a new vm on 2.2.0a4 and it works fine. Added a nic and all is well.

**Comment by grossmj** [comment] 2019-04-10 04:57
Strange but I am going to close this then.

**Closed by grossmj** 2019-04-10 04:57 UTC
