### ISSUE TITLE
Hyper-V VM 2.2.16 status stuck at VM is starting

### ISSUE THREAD

**Issue by rcmpgi** [GNS3/gns3-gui#3100] opened 2020-11-24 14:45 UTC
Same problem as this but the fixes for 2.2.15 do not work for 2.2.16, see the later comments here:
https://github.com/GNS3/gns3-gui/issues/3058
Opening this bug report as that one has been closed but the issue persists in the next version of GNS3.

**GNS3 version and operating system (please complete the following information):**
 - OS: Windows 10
 - GNS3 version 2.2.16
 - GNS3 Hyper-V VM version 2.2.16

**To Reproduce**
Start GNS3, configure Hyper-V VM, GNS3 starts VM, VM itself starts correctly but GNS3 status in Server Summary window just stays on:
GNS3 VM is starting

**Comment by no-good-usernames-left** [comment] 2020-11-25 20:24
Can confirm issue, GNS3 does not give you any way to manage/troubleshoot/reliably reconnect to the VM

Also, the powershell script to create the Hyper-V VM doesn't work... 

Manually created VM, booted, and it appears to be working fine, but GNS3 is still stuck on VM is starting

**Comment by grossmj** [comment] 2020-11-30 01:33
Do you have screenshots please? thanks :+1:

**Comment by rcmpgi** [comment] 2020-11-30 08:28
To save posting effectively the same thing again, see the screenshot from victoreebel from bug #3058 
https://github.com/GNS3/gns3-gui/issues/3058#issuecomment-730356347

**Comment by no-good-usernames-left** [comment] 2020-11-30 14:21
I think I know what the problem is after messing around with the VMware version and having the same issue as Hyper-V

First, the Hyper-V powershell script doesn't work, it does not create the VM like it's supposed to...
So I just imported the disks and launched with a single NIC facing my LAN

The GNS3 docs and application error handling don't disclose the need for a local/host-only network between GNS3 and the VM to ensure proper operation

If we had the option to send GNS3 over the LAN to the VM, or manually type in the IP address, 90% of us newbies to this world would have been able to get going much faster on this platform...

Anyways, that host-only network default is 10.10.10.0/24
I have a Server VLAN with the _same_ subnet, so the two worlds did collide, and it did not work. 

Once fixed the host-only network and changed the subnet in VMware, I finally got it up and running.

**Comment by grossmj** [comment] 2020-12-02 08:52
> First, the Hyper-V powershell script doesn't work, it does not create the VM like it's supposed to...

It works fine here. Select the script and run with PowerShell.

![Screenshot from 2020-12-02 19-08-57](https://user-images.githubusercontent.com/4752614/100849250-33193a80-34d2-11eb-890c-b8d6ec332cb8.png)

Then answer Y to the question.

![Screenshot from 2020-12-02 19-09-22](https://user-images.githubusercontent.com/4752614/100849262-37ddee80-34d2-11eb-8f45-2bb12f95f618.png)

Finally, you should see the VM in Hyper-V.

![Screenshot from 2020-12-02 19-10-12](https://user-images.githubusercontent.com/4752614/100849270-3c0a0c00-34d2-11eb-82e1-19cdf4f47e85.png)

Has Hyper-V a standard way to distribute VMs / appliances? (like import OVA in VMware and VirtualBox).

> To save posting effectively the same thing again, see the screenshot from victoreebel from bug #3058
#3058 (comment)

There is a missing package in the GNS3 VM. In the VM menu, select shell and type the following command:

`sudo apt update && sudo apt install --yes linux-cloud-tools-common && update-initramfs -u`

This will be fixed in version 2.2.17

**Comment by no-good-usernames-left** [comment] 2020-12-02 20:41
I was using Server 2019 and the blue PS window launches for a few seconds and then closes without creating the VM... 

Also, the GNS3 app and VM need to throw an error message when the VM does not have a local/host only NIC or there's a collision with the 10.10.10.X subnet...

**Comment by rcmpgi** [comment] 2020-12-03 09:07
Sadly, I got this:
![image](https://user-images.githubusercontent.com/51117322/100987152-0bfc5080-3546-11eb-946a-cf4c65b5358d.png)

Running the command to view the log shows:
![image](https://user-images.githubusercontent.com/51117322/100987286-3948fe80-3546-11eb-8ec6-15a50dbcd73c.png)

However, despite that (and after a reboot of the VM (not sure if that was necessary, did it anyway) it is now showing OK in the GNS3 GUI:
![image](https://user-images.githubusercontent.com/51117322/100987781-db68e680-3546-11eb-8627-ed4d11e16180.png)

Thank you 👍

**Comment by grossmj** [comment] 2020-12-03 09:30
@rcmpgi perfect, thanks for the feedback.

**Closed** 2021-01-16 01:59 UTC
Labels: Bug
