### ISSUE TITLE
GNS3 2.2.0a2 import appliance not working continues

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#2738] opened 2019-03-15 01:21 UTC
This is a essentially a repeat of issue 2707 but new version of GNS3
GNS3 2.2.0a2, Windows 10 Prof x64, VM Workstation Pro 14.1.5 build-10950780 and the GNS3 workstation VM provided with GNS3 2.2.0a2 (assigned 16gig RAM)

Using appliance templates to import ASAv, IOSv and IOSvL2 images. It appears all goes well but when I try to use them in a project the files cannot be found. The folder in the VM /opt/gns3 has the appropriate folders (IOS and QEMU) but both folders are empty. This process worked fine in GNS3 2.1.14.
If I add the images manually they are uploaded and appear in /opt/gns3/images/Qemu 
but when I use the images in a project, e.g., an IOSv image the follow error occurs when I start the IOSv:
QEMU process has stopped, return code: 1
(I am omitting the following long description of the image)
Execution log:
Could not access KVM kernel module: Permission denied
qemu-system-x86_64: failed to initialize KVM: Permission denied
Could not start Telnet QEMU console [Errno 111] Connect call failed ('127.0.0.1', 5001)

Here's other odd behavior:
The VMware VM settings as I configured them:
![GNS2 2 0a2VMsettings-2](https://user-images.githubusercontent.com/10285348/54401609-b495bd00-469e-11e9-8408-e2e4852f5437.png)
The same VMware VM settings after the GNS3 application has run and been closed:
![GNS2 2 0a2VMsettings](https://user-images.githubusercontent.com/10285348/54401656-e9097900-469e-11e9-93d3-89923c041290.png)
I can find no setting in any of the application specific INI files that would cause this.

**Comment by grossmj** [comment] 2019-03-15 06:08
For some reasons, the rights on /dev/kvm seems to be wrong. Please, try to log in to the GNS3 VM and issue the following commands in a shell:

```
sudo chown root:kvm /dev/kvm
sudo chmod 660 /dev/kvm
```

Then restart the VM. Thanks :)

**Comment by jtorri** [comment] 2019-03-15 17:50
Did as you suggested.  Here is before running commands to change owner and permissions.
![Beforemod](https://user-images.githubusercontent.com/10285348/54451191-a9876f00-4728-11e9-9e58-82c8e69115aa.png)
And now after running commands:
![Aftermod](https://user-images.githubusercontent.com/10285348/54451226-b60bc780-4728-11e9-8097-4760e67ab288.png)
However, the same errors (permission problems with kvm) occurred when I then ran GNS3 application.
And, to add more strangeness, the settings on kvm were back to those before I ran the commands:
![Beforemod](https://user-images.githubusercontent.com/10285348/54451289-ebb0b080-4728-11e9-8c91-7bf842f9e8e6.png)
Also, the number of processors and the number of cores per processor on the GNS3 VM is continuing to be reset each time I run the GNS3 application.
It really does seem to me the GNS3 application is making changes to the GNS3 VM when the GNS3 application starts.
Hope this makes sense since it makes no sense to me.  Thanks!

**Comment by jtorri** [comment] 2019-03-15 18:18
Could these lines in gns3_server.log have any effect?
2019-03-15 14:05:30 INFO vmware_gns3_vm.py:147 Update GNS3 VM settings
2019-03-15 14:05:30 INFO vmware_gns3_vm.py:84 GNS3 VM vCPU count set to 4 and RAM amount set to 12288
I pretty sure something is modifying the GNS3 VM .vmx files, specifically the value of
cpuid.corespersocket

Thanks!

**Comment by grossmj** [comment] 2019-03-16 09:04
@jtorri 

For some reasons the /dev/kvm permissions were reset after a reboot. I have fixed that in https://github.com/GNS3/gns3-vm/commit/47a18f1877e5cd8b5ff08807c969d02559723f0a

> Also, the number of processors and the number of cores per processor on the GNS3 VM is continuing to be reset each time I run the GNS3 application.

This is indeed changed set by the GNS3 server everything it starts the GNS3 VM. This is configured there:

![gns3_vm_preferences](https://user-images.githubusercontent.com/4752614/54473024-c5604300-4804-11e9-87a1-bc5eb3baf67b.png)

Maybe we should have an option to allow or not GNS3 to set the CPU/RAM for the GNS3 VM?

**Comment by grossmj** [comment] 2019-03-16 09:05
> Using appliance templates to import ASAv, IOSv and IOSvL2 images. It appears all goes well but when I try to use them in a project the files cannot be found.

I am going to investigate this now.

**Comment by grossmj** [comment] 2019-03-16 11:50
@jtorri do you see any indication that the image upload is started from the GUI? (i.e. a message). For large image you should see a progress dialog while to image is being uploaded.

**Comment by grossmj** [comment] 2019-03-16 12:21
@jtorri good news, I can reproduce the problem. This is going to be much easier to fix the problem.

**Comment by jtorri** [comment] 2019-03-17 02:26
The GNS3 VM Preferences allows setting the total number vCPUs.  That is not the issue.  The GNS3 application is resetting the following:  A VMWare workstation VM has a "Processors" setting.  Under that setting one can set "Number of processors", "Number of cores per processors". These two are the values being reset by, I believe", the GNS3 application.  I set them to 1 processor and 4 cores per processor.  When the GNS3 application starts it resets both values to 2.  The total processor cores is a value determined by VMWare by multiply number of processors X number of cores per processors.  In this instance that value is 4, the same value set in the GNS3 VM Preferences vCPU setting.  Make sense?

**Comment by jtorri** [comment] 2019-03-17 03:21
"For some reasons the /dev/kvm permissions were reset after a reboot. I have fixed that in GNS3/gns3-vm@47a18f1"
Installed  GNS3-2.2.2019-03-17-all-in-one.exe .  Then tried to update GNS3 VM via menu option in order the GNS3 version match the GNS3 VM version. Ran "Update the GNS3 VM". It failed with error message "/tmp/update.sh: line 1: 404:: command not found".  
As always I am likely missing something obvious.  Thanks!

**Comment by grossmj** [comment] 2019-03-17 13:43
>  Then tried to update GNS3 VM via menu option in order the GNS3 version match the GNS3 VM version. Ran "Update the GNS3 VM". It failed with error message "/tmp/update.sh: line 1: 404:: command not found".

We have made changes to the VM script. You should be able to restore the VM by selecting the "Restore" option in the VM menu. PS: we are going to release alpha 3 soon.

**Comment by jtorri** [comment] 2019-03-17 18:47
Well, now I am able to upgrade GNS3 VM 2.2.0a2 to 2.2.0dev7. Why? Perhaps a good night's sleep? Believe it best I just wait for GNS3 2.2.0a3 rather than generate more confusion.  Thanks again!

**Comment by jtorri** [comment] 2019-03-18 02:24
Using GNS3-2.2.2019-03-17-all-in-one.exe and GNS3 VM 2.2.0dev7 all the basic stuff seems to work except for import of appliance works except it does not upload the selected image file.  This can be done by editing the template in GNS3 application.  When the image file is selected in the template file the image file is uploaded to the GNS3 VM.

**Comment by grossmj** [comment] 2019-03-18 11:15
I have fixed the VMware vcpu problem in https://github.com/GNS3/gns3-server/commit/8e8985c69f621ec63a6029468cc29475bc785849

All other issues you reported should be fixed now. Let's see how everything goes with alpha 3.

Thanks again :)

**Closed by grossmj** 2019-03-18 11:15 UTC
Labels: Bug
