### ISSUE TITLE
SSH console type for Cloud object.

### ISSUE THREAD

**Issue by vint66** [GNS3/gns3-gui#3064] opened 2020-10-05 15:56 UTC
Hi GNS3 team,

Is it possible to add SSH remote_console_type for cloud object?
This could be extremely useful for hybrid setups with connection to real devices (specifically to *nix servers).

**Comment by b-ehlers** [comment] 2020-10-06 07:14
Might be a duplicate of https://github.com/GNS3/gns3-gui/issues/2840

**Closed** 2020-10-06 07:16 UTC
Labels: Duplicate, Enhancement
