### ISSUE TITLE
bug? : layer of rectangle and lock item

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2513] opened 2018-06-09 10:49 UTC
Hi

- (To debug, i enable "show layers")
- I put on the topology a rectangle. His layer is 0
- I change the layer of this rectangle to 2
- I click on the button "lock all items"
- The layer of the rectangle becomes -1
- (If i click again on "lock all items", it becomes 0)

Is it a bug or a choose ?

**Comment by grossmj** [comment] 2018-06-09 11:50
The problem is we don't save the original z value of the rectangle. All what "lock all items" do it to set the layer to -1 when locking and 0 when unlocking.

**Comment by Raizo62** [comment] 2018-06-09 19:11
it is not a good implementation.... :-(
If you have not the choose, perhaps you can use the formula : -(z+1) when locking ?

**Comment by grossmj** [comment] 2018-06-10 07:47
The problem is to go back to the original z value when unlocking.

**Comment by Raizo62** [comment] 2018-06-11 17:57
If you choose the formula : -(z+1) when locking, to unlock you use the same :
z=4
lock : z=-(4+1)=-5
unlock : z=-(-5+1)=4

But, can you not add a new boolean variable to lock/unlock ?

**Comment by grossmj** [comment] 2018-06-12 07:17
The simplest for us is to use the formula. I am going to implement that soon.

**Comment by grossmj** [comment] 2018-06-13 09:32
Should be fixed now. Please double check and let me know if everything works as expected.

Thanks! :)

**Comment by Raizo62** [comment] 2018-06-14 12:08
Sorry, i can't test before.

I believe that i have found a bug : 
- a device is in the default layer 0
- I use "lower one layer" : z value becomes -1 then lock. It is not my wish

I think that, if i want to lower a layer of 0, you must increase of 1 all other device. (but if the other device is lock, you must increase of -1)

**Comment by Raizo62** [comment] 2018-06-14 15:42
an other bug with the same idea : 
- I have a device with layer of 4
- I lock : his layer becomes -5
- I raise one layer : his layer becomes -4 , but it should be -6

**Comment by Raizo62** [comment] 2018-06-25 06:20
Question : should we be able to change the layer of locked device ?

**Comment by grossmj** [comment] 2018-08-08 07:36
> I think that, if i want to lower a layer of 0, you must increase of 1 all the others devices. (but if the other device is lock, you must increase of -1)

I have changed the default layer for newly created nodes to 1 and 2 for all other drawing. This should solve the problem.

> I lock : his layer becomes -5, I raise one layer : his layer becomes -4 , but it should be -6

Well, for me this is totally normal, you raise from -5 (-5 + 1 = -4). If you want -6 you have to lower one layer.

**Comment by Raizo62** [comment] 2018-09-09 10:38
Sorry, i don't see your answer before now (?)

>> I lock : his layer becomes -5, I raise one layer : his layer becomes -4 , but it should be -6
>
> Well, for me this is totally normal, you raise from -5 (-5 + 1 = -4). If you want -6 you have to lower one layer.

I think not : I don't want '-6', i want to raise the device, and i don't know that you use the layer to lock device
- The  device is in 4. I raise it [ 4+1 ], it must have 5

But if i use lock in the middle : 
- The device is in 4. i lock the device [ -(4+1)=-5 ] , raise the device [-5 +1=-4], unlock the device [-(-4+1)=3] , the layer of the device is 3. It is not good

If you add -1 if the layer is < 0
- The device is in 4. i lock the device [ -(4+1)=-5 ] , raise the device [-5 -1=-6], unlock the device [-(-6+1)=5] , the layer of the device is 5. It is good

**Comment by grossmj** [comment] 2018-11-19 08:01
> The device is in 4. i lock the device [ -(4+1)=-5 ] , raise the device [-5 +1=-4], unlock the device [-(-4+1)=3] , the layer of the device is 3. It is not good

Maybe we shouldn't use layers to lock a node... how can we restore the original layer (4) if you change the layer once the node has been locked?

> The device is in 4. i lock the device [ -(4+1)=-5 ] , raise the device [-5 -1=-6], unlock the device [-(-6+1)=5] , the layer of the device is 5. It is good

I still think that raising a layer should be +1, not -1. I think this is how most software that use layers work and I am afraid this would confuse users if we change this.

**Comment by Raizo62** [comment] 2018-11-19 09:20
You're right: if a device is locked, a user should not be able to change layers.
Perhaps you must not allowed to change a layer of a locked device ?

**Comment by grossmj** [comment] 2018-11-20 08:16
> Perhaps you must not allowed to change a layer of a locked device ?

Ok I have done that. I don't think there will be any side effect. Please comment back if there is still an issue.

Thanks!

**Closed by grossmj** 2018-11-20 08:16 UTC
Labels: Bug
