### ISSUE TITLE
 Error while listing vms: GNS3VM: Could not list VMware VMs: VMware is not installed (vmware or vmplayer executable could not be found in $PATH)

### ISSUE THREAD

**Issue by Adrihhh** [GNS3/gns3-gui#3310] opened 2022-03-25 14:53 UTC
Hi there, I'm new to GNS3 and still learning.

I was following this guide extemenetworks posted to work with EXOS ( https://github.com/extremenetworks/Virtual_EXOS/blob/master/GNS3_EXOS-VM_Guide.md ), and I ran into a problem. 

I managed to download their template, VMware (I have the 16.2.3 version, Pro), and import the GNS3-VM OVA succesfully. It's the 2.2.31 version, same as my GNS3. VM is up and running, got through the Setup Wizard just fine, and my GNS3 looks like this.

![image](https://user-images.githubusercontent.com/100367109/160143723-d2ee0256-3752-4e3e-adfd-c7e8fc2ce976.png)

One of their steps is importing the EXOS VM appliance, but their guide indicate me to "Install the appliance on the GNS3 VM (recommended)", and it's grayed out.

While investigating in the GNS3 settings, in Preferences, GNS3 VM, the "Enable the GNS3 VM" option wasn't checked (the Virtualization engine is properly selected, it says VMware), and in Settings, VM name is blank, and when trying to refresh it's when I get the error :

 Error while listing vms: GNS3VM: Could not list VMware VMs: VMware is not installed (vmware or vmplayer executable could not be found in $PATH)

I'm on Windows 10 Pro 21H2.

**Comment by josephmhiggins** [comment] 2022-03-25 19:49
1. Close this ticket and deescalate to the gns3 community at gns3.com because:
    a. the gns3 community handles all the labor intensive problems that do not require much knowledge because there are thousands of gns3 community members, and
    b. github.com/GNS3, e.g. the several gns3 developers handle all the problems that require great knowledge or are extremely specialized and no one in the gns3 community has that knowledge or specialization
2. Please open up the gns3.com ticket after reading:
    a. https://gns3.com/code-of-conduct-amp-gns3-faq, and
    b. and following "What is the best way to get assistance with my question?"


In the future, keep in mind:

1. This is not a bug - only experts should be declaring something a Bug, and
2. "What is the best way to get assistance with my question?" is remiss in that
    item 2 should say: "Host operating system and version"
    item 7 does not exist and should say: "Hypervisor name and version."
3. You **can NOT copy and paste pictures at gns3.com** like you copy and pasted your topology in this post on github.com. You must hit the "Upload File" (or maybe it is named "Attach File") button (I think at the top right of the page when you create the post on gns3.com).

**Closed** 2022-03-25 19:56 UTC
Labels: Bug

**Comment by jeesna** [comment] 2024-09-20 09:18
me too 

and i use Mac bookpro m2pro 
Mac os sequoia 15.1
i try to rearch but have no for apple silicone .

**Comment by grossmj** [comment] 2024-09-20 11:41
Make sure VMware Fusion is installed in `/Applications`
