### ISSUE TITLE
Node list view not updated when adding or deleting node template

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#2529] opened 2018-06-26 16:05 UTC
GNS3 version 2.1.8 on Darwin (64-bit) with Python 3.6.5 Qt 5.9.3 and PyQt 5.9.2.

Similar issue as https://github.com/GNS3/gns3-gui/issues/2356

When adding or deleting a node template in the preferences (no matter what type), the node list view is not updated, after leaving the preferences. When I then re-enter the preferences and leave them (no matter if I use OK or Cancel) the node list view gets updated. Another way is stopping, then starting the GNS3 GUI.

This happens with my GNS3 installation, that is in daily use and that uses a lot of features. To create a reproducible setup I cleared my GNS3 configuration (after making a backup) and started with a fresh setup, using only a local server (no GNS3VM or remote server). To my surprise I couldn't reproduce that issue, everything work as expected. After some more testing I found, that this issue arises only, when using several node templates. On my system tested with 20 templates the issue is showing sometimes, with 30 templates it shows almost everytime.

I'm attaching my [gns3_controller.conf.txt](https://github.com/GNS3/gns3-gui/files/2137902/gns3_controller.conf.txt) and [gns3_gui.conf.txt](https://github.com/GNS3/gns3-gui/files/2137904/gns3_gui.conf.txt). I created them starting from a clean state with just a local server by adding 30 dynamips router templates. Depending on your system you may need to add further templates.

**Comment by grossmj** [comment] 2018-08-07 13:15
I could not reproduce this issue, however I expect it will be fixed when redesigning appliance handling https://github.com/GNS3/gns3-gui/issues/2490

**Comment by ehlers** [comment] 2018-08-07 14:28
What about closing it? It's not a common issue and putting a lot of effort into that, when the appliance handling is changed in 2.2 is a waste of time.

**Comment by grossmj** [comment] 2018-08-07 14:30
@ehlers I agree, let's close this.

**Closed by grossmj** 2018-08-07 14:30 UTC
Labels: Bug
