### ISSUE TITLE
macos 10.14 mojave have problems with delays and crashes？

### ISSUE THREAD

**Issue by kiritowch** [GNS3/gns3-gui#2596] opened 2018-09-26 08:28 UTC
Does anyone have problems with delays and crashes on gns3, my system is macos 10.14 mojave? Error reporting is related to QT GUI, can you help solve it? My GNS3 version is 2.1.0. Is it effective to upgrade to the latest version?

**Comment by grossmj** [comment] 2018-09-26 08:45
> Is it effective to upgrade to the latest version? 

Yes, please upgrade. it will most likely solve the problem.

**Comment by kiritowch** [comment] 2018-09-26 09:06
> > Is it effective to upgrade to the latest version?
> 
> Yes, please upgrade. it will most likely solve the problem.

I found that it was not improved, it would be lagging when the mouse was clicked or dragged. Please confirm whether the problem exists, I don't know if it is just me, thank you very much！

**Comment by grossmj** [comment] 2018-10-02 09:53
Please provide more details and maybe screenshots to describe the problem. Thanks!

**Comment by josephillips85** [comment] 2018-10-05 05:42
Hi 
i can confirm this issue too mostly when try to open consoles the computer got Freeze complety for few seconds 
Also i found a workaround 

open terminal and open gns3 from there and the issue don't happend
to confirm my theory please open this command on terminal @kiritowch 
 
`open /Applications/GNS3.app/Contents/MacOS/gns3`

is something related with tccd

Failed to copy signing info for 641, responsible for file:///Applications/GNS3.app/Contents/MacOS/gns3: #-67062: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)"

**Comment by grossmj** [comment] 2018-11-19 10:51
Unfortunately we do not have access to macOS Mojave at the moment.

**Comment by josephillips85** [comment] 2019-01-17 07:59
HI Jeremy 
I can confirm that running the application from source code in console don't cause any issue on Mojave    
Just like the 2.1.11 version 

Looks like the problem is in the compiling for Application 
Where i can get the process to convert this application to .app ?

Thanks

**Comment by grossmj** [comment] 2019-02-19 08:42
The problem seems to be that our Application is not code signed with a certificate. (see https://github.com/inket/update_xcode_plugins/issues/51). I tried to sign our app with a self-signed certificate but couldn't succeed. Honestly, Apple does not make it easy and code signing on macOS seems to be some king of dark magic.

**Comment by grossmj** [comment] 2019-03-04 09:27
After going through many hoops, we have successful code signed our macOS app :) For now this is only done for version 2.2 (currently in alpha stage). We may consider doing it for version 2.1.15 if we release it.

**Comment by josephillips85** [comment] 2019-03-04 17:08
@grossmj  nice to hear that.

still the workaround still work until is the fix is released.  :)

**Comment by grossmj** [comment] 2019-03-05 09:51
We have added code signing support on our 2.1 branch. This means the App will be signed when we release version 2.1.15.

I am going to close this for now. Please comment back or create an new issue if you find there is still a problem. Thanks.

**Closed by grossmj** 2019-03-05 09:51 UTC
Labels: Enhancement
