### ISSUE TITLE
Add support for Wireshark V2.x (on Mac OS X)

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#830] opened 2015-11-18 20:42 UTC
On Mac OS X Wireshark 2.x uses a different path to the binary than in V1.x

1.x: /Applications/Wireshark.app/Contents/Resources/bin/wireshark
2.x: /Applications/Wireshark.app/Contents/MacOS/Wireshark

I suggest to create separate preconfigured packet reader commands for Wireshark V1.x and V2.x on Mac OS X

**Comment by ehlers** [comment] 2015-11-26 09:21
Just as a side note: The command line option ```-o gui.window_title:``` is ignored on 2.0. I haven't found another way to modify the window title. So 2.0 users must live with the default window title.

**Comment by noplay** [comment] 2015-11-30 06:50
I think we will need to open a bug on:
https://bugs.wireshark.org/bugzilla/

For the windows title

**Comment by ehlers** [comment] 2015-11-30 08:58
Created bug 11814 - gui.window_title not working on qt version (2.0) on wireshark bugzilla: https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=11814

**Comment by noplay** [comment] 2015-11-30 11:35
Thanks they also marked it as a duplicate of :
https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=11691

**Comment by noplay** [comment] 2015-11-30 13:38
I put the 2.0 as default version for OSX because if you are an OSX user you should really upgrade to avoid using X11

**Closed** 2015-11-30 13:38 UTC
Labels: bug

**Comment by grossmj** [comment] 2015-11-30 21:03
Sounds good. Something to be careful when merging on unstable is that the ```-o gui.window_title:``` param is no longer work in Wireshark 2.0. Maybe there is another way?

**Comment by noplay** [comment] 2015-12-01 08:22
It's not working but not crashing we can keep it, and wait for wireshark team to fix it

**Comment by ehlers** [comment] 2015-12-15 11:26
The wireshark team is working on the gui.window_title issue:
Wireshark Change 12650 -  Qt: Add support of gui.window_title
https://code.wireshark.org/review/#/c/12650/

**Comment by noplay** [comment] 2015-12-15 15:59
Cool

**Comment by ehlers** [comment] 2016-02-27 08:39
Wireshark v2.0.2 is just released. It adds the missing gui.window_title functionality into the v2 release, here a screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/896406/13371998/5d39d36e-dd35-11e5-8ae8-48374a036c10.png)

**Comment by noplay** [comment] 2016-03-01 08:20
Nice!

**Comment by tjctw** [comment] 2016-04-21 06:06
Hi, I just want to report that while using GNS1.4.5 on MACOSX 10.11 with wireshark 2.0.2.
I found that the default cmd caused error as follows.
```Error:` R1: Could not start the packet capture reader: [Errno 2] No such file or directory: ```
```/Applications/Wireshark.app/Contents/Resources/bin/wireshark': None```

but after set and apply  "Wireshark Live Traffic Capture" then everything is working good.
should we fix this?:)

**Comment by noplay** [comment] 2016-04-21 07:07
If it's a previous install of GNS3 "it's normal" we saved the path of
Wireshark 1 in settings and when you upgrade to 2.0 the path change :(
Reapply the settings put the correct path (you will see in the settings
that you have an options for wireshark 1.X or 2.0 in the settings).

**Comment by tjctw** [comment] 2016-04-21 09:02
Got it! Thanks for the reply, this reminds me that I had installed GNS3 a long time ago ;)
