### ISSUE TITLE
[Linux/2.0.3] CRITICAL __init__.py:202 POST /projects/x/qemu/nodes/y/adapters/5/ports/0/nio not found

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-gui#2186] opened 2017-07-26 14:47 UTC
GNS3 GUI & server 2.0.3
 
The project has been correctly saved with 2.0.3 when exiting GNS3.
When I try to reopen the same project, I get the error message:
![gui error](https://user-images.githubusercontent.com/13176858/28626894-88bb1788-7220-11e7-95a2-fb1cf04a18b2.jpg)

The log shows:
```
...
2017-07-26 16:12:05 INFO link.py:65 adding link from IOSv_Spine_11 GigE1 to ASAv1 GigE1
2017-07-26 16:12:05 INFO link.py:65 adding link from AnsibleHost tap2 to IOSv_L2_Mgt Gi0/0
2017-07-26 16:12:05 INFO link.py:65 adding link from IOSv_L2_Mgt Gi1/2 to IOSv_Leaf_16 GigE0
2017-07-26 16:12:05 INFO link.py:65 adding link from IOSv_L2_Mgt Gi1/3 to ASAv1 GigE0
2017-07-26 16:15:53 CRITICAL __init__.py:202 POST /projects/d3f1b32d-60af-4481-b8d7-66a875013666/qemu/nodes/36d860b9-ae53-451b-a51e-49c0b4c003c6/adapters/5/ports/0/nio not found
```
The .gns3 shows:
```
        "links": [
            {
                "link_id": "bb1174ed-6fe4-47ca-939c-24eea135ce7c",
                "nodes": [
                    {
                        "adapter_number": 5,
                        "label": {
                            "rotation": 0,
                            "style": "font-size: 10; font-style: Verdana",
                            "text": "5/0",
                            "x": -10,
                            "y": -10
                        },
                        "node_id": "36d860b9-ae53-451b-a51e-49c0b4c003c6",
                        "port_number": 0
                    },
...
            {
                "compute_id": "local",
                "console": 2017,
                "console_type": "telnet",
                "first_port_name": null,
                "height": 56,
                "label": {
                    "rotation": 0,
                    "style": "font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;",
                    "text": "XEv_Spine_11",
                    "x": -21,
                    "y": -25
                },
                "name": "XEv_Spine_11",
                "node_id": "36d860b9-ae53-451b-a51e-49c0b4c003c6",
                "node_type": "qemu",
                "port_name_format": "GigE{0}",
                "port_segment_size": 0,
                "properties": {
                    "acpi_shutdown": false,
                    "adapter_type": "virtio-net-pci",
                    "adapters": 8,
                    "bios_image": "",
                    "bios_image_md5sum": null,
                    "boot_priority": "c",
                    "cdrom_image": "",
                    "cdrom_image_md5sum": null,
                    "cpu_throttling": 0,
                    "cpus": 1,
                    "hda_disk_image": "CSR-1000v-16.5.1.qcow2",
                    "hda_disk_image_md5sum": "86fa38762ddef1b861b80c38c529b7d0",
                    "hda_disk_interface": "virtio",
                    "hdb_disk_image": "",
                    "hdb_disk_image_md5sum": null,
                    "hdb_disk_interface": "ide",
                    "hdc_disk_image": "",
                    "hdc_disk_image_md5sum": null,
                    "hdc_disk_interface": "ide",
                    "hdd_disk_image": "",
                    "hdd_disk_image_md5sum": null,
                    "hdd_disk_interface": "ide",
                    "initrd": "",
                    "initrd_md5sum": null,
                    "kernel_command_line": "",
                    "kernel_image": "",
                    "kernel_image_md5sum": null,
                    "legacy_networking": false,
                    "mac_address": "00:00:ab:03:c6:00",
                    "options": "-nographic -enable-kvm -cpu host",
                    "platform": "x86_64",
                    "process_priority": "normal",
                    "qemu_path": "/usr/bin/qemu-system-x86_64",
                    "ram": 4096,
                    "usage": ""
                },
                "symbol": ":/symbols/iosv_virl.svg",
                "width": 66,
                "x": -141,
                "y": -48,
                "z": 1
            },
```

This project is a result of:
- cloning another project
- modifying the project id in the new .gns3 file
- deleting 2 nodes
- replacing them with 2 other types of nodes: CSR-1000v, which is the type shown above
- replacing all previous links of previous nodes with the same with the 2 new nodes

**Comment by noplay** [comment] 2017-07-26 14:49
Why did you need that?
* modifying the project id in the new .gns3 file 

You didn't use the save as feature?

**Comment by jean-christophe-manciot** [comment] 2017-07-26 15:07
You're right, it would have been a better option.

**Comment by noplay** [comment] 2017-07-26 15:09
I think it could explain the issue because other uuid was not uniques

**Comment by jean-christophe-manciot** [comment] 2017-07-26 15:10
What other UUIDs?

**Comment by jean-christophe-manciot** [comment] 2017-07-26 15:11
The only thing that changed was the project ID.

**Comment by jean-christophe-manciot** [comment] 2017-07-26 15:14
What does the error message mean exactly?

**Comment by noplay** [comment] 2017-07-26 15:15
The uuid of each node. The error mean we didn't found the network adapter

**Comment by jean-christophe-manciot** [comment] 2017-07-26 15:20
The links have been deleted and recreated after the cloning: I don't see how the cloning has something to do with this issue. 
Also, I was able to edit and modify the topology within GNS3 after the cloning: how can a network adapter suddenly disappear after the topology was correctly saved?

**Comment by jean-christophe-manciot** [comment] 2017-07-26 15:23
Also, the properties of the node show 8 adapters as listed above: how can the network adapter n° 5 disappear?

**Comment by noplay** [comment] 2017-07-26 15:37
It's possible that we keep reference based on node uuid and not the combo project + node. And we get confuse. Or we have been lost because the you didn't change the uuid on the link to something unique.

It's the best explanation I have.

**Comment by jean-christophe-manciot** [comment] 2017-07-26 15:42
you didn't change the uuid on the link to something unique

I did not manually change any UUID except the project's.
All other changes have been made by GNS3 in the gns3 file.

**Comment by noplay** [comment] 2017-07-26 15:48
Yeah it's what I say. The fact you didn't replace the other uuid could have create issue. Save as change all the UUID not just the project.

**Comment by jean-christophe-manciot** [comment] 2017-07-26 17:27
I have found the reason for this issue: the **new gns3-ubridge 0.9.12**!
If I downgrade to 0.9.11, I can read the same project without any error!

**Comment by jean-christophe-manciot** [comment] 2017-07-26 17:28
Could you move this thread to gns3-ubridge issues please?

**Comment by noplay** [comment] 2017-07-27 09:20
Do you replicate the same issue with a project cloned using save as?

I don't know why changing the ubridge version has fixed your issues.  But having non unique UUID will create a lot of problems. I checked and if you use two project with the same node UUID you will break the network links because we pass the node UUID to ubridge as a unique key.

This the expected behavior of ubridge. If you don't replicate using save as we should close the issue and consider the project file was corrupted due to invalid UUID.

**Comment by jean-christophe-manciot** [comment] 2017-07-27 09:31
OK, so this means that if I "save as" any project, all UUIDs should be changed to unique values, right?

**Comment by noplay** [comment] 2017-07-27 09:31
Right, and path will be also modified

**Comment by jean-christophe-manciot** [comment] 2017-07-27 09:34
So, a valid workaround is to "save as" each cloned project and we should be good.

**Comment by noplay** [comment] 2017-07-27 09:34
Yes.

**Comment by noplay** [comment] 2017-07-27 09:43
Don't hesitate to comment. We will reopen the issue if you still have the problem using save as

**Closed by noplay** 2017-07-27 09:43 UTC
Labels: Bug, Waiting for more information
