### ISSUE TITLE
AttributeError: module 'os' has no attribute 'listxattr'

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#2010] opened 2017-05-02 15:11 UTC
https://sentry.io/gns3/gns3-gui/issues/264817547/

```
AttributeError: module 'os' has no attribute 'listxattr'
  File "gns3/main_window.py", line 1029, in startupLoading
    self._setupWizardActionSlot()
  File "gns3/main_window.py", line 779, in _setupWizardActionSlot
    LocalServer.instance().localServerAutoStartIfRequire()
  File "gns3/local_server.py", line 338, in localServerAutoStartIfRequire
    if not self.initLocalServer():
  File "gns3/local_server.py", line 365, in initLocalServer
    self._checkUbridgePermissions()
  File "gns3/local_server.py", line 161, in _checkUbridgePermissions
    if "security.capability" in os.listxattr(path):

AttributeError: module 'os' has no attribute 'listxattr'
```

**Comment by noplay** [comment] 2017-05-02 15:12
This need to be investiguate. But it seem with a grsecurity kernel the call is missing.

**Comment by grossmj** [comment] 2017-05-02 16:15
Maybe we should handle that exception and just write a warning in the logs?

**Comment by noplay** [comment] 2017-05-02 17:53
Yes seem to be the best option

**Comment by fcolista** [comment] 2017-05-03 08:03
This seems to be a sort of regression for Python 3.6, which takes for granted that all the world uses GLIBC.
It's described here in a very old post:
https://hg.python.org/cpython/rev/33f7044b5682

In Alpine (which uses musl) we fixed with this patch, if this might help:


`
diff --git a/Modules/posixmodule.c b/Modules/posixmodule.c
index 8f8ba25..72b92da 100644
--- a/Modules/posixmodule.c
+++ b/Modules/posixmodule.c
@@ -103,8 +103,9 @@ corresponding Unix manual entries for more information on calls.");
 #undef HAVE_SCHED_SETAFFINITY
 #endif
 
-#if defined(HAVE_SYS_XATTR_H) && defined(__GLIBC__) && !defined(__FreeBSD_kernel__) && !defined(__GNU__)
+#if defined(HAVE_SYS_XATTR_H) && defined(__linux__) && !defined(__FreeBSD_kernel__) && !defined(__GNU__)
 #define USE_XATTRS
+#include <linux/limits.h>
 #endif
 
 #ifdef USE_XATTRS
`

.: Francesco Colista
.: Alpine Linux

**Comment by noplay** [comment] 2017-05-03 08:27
Thanks for the info

**Closed** 2017-05-09 10:20 UTC
Labels: Bug, Pull request opened
