### ISSUE TITLE
Delete a project

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#1174] opened 2016-04-08 16:44 UTC
Bet this one has been answered long ago but here goes.  GNS3 1.4.5 running on Win 10 all projects run on GNS3 VM VMware Workstation 11.  Is it possible to fully delete a GNS3 project from within the GNS3 app?

**Comment by grossmj** [comment] 2016-04-08 23:33
It is on our roadmap for 2.0 :)

**Comment by ehlers** [comment] 2016-05-05 06:59
Duplicate of https://github.com/GNS3/gns3-gui/issues/822 ?

**Comment by noplay** [comment] 2016-05-09 07:46
Yes I close the duplicate

**Closed** 2016-05-09 07:46 UTC
Labels: enhancement
