### ISSUE TITLE
Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() 

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1341] opened 2016-06-30 07:09 UTC
Error reported by @gcasella 
/usr/lib/python3.5/site-packages/raven-5.21.0-py3.5.egg/raven/conf/remote.py:67: UserWarning: Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.
warnings.warn('Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.')

**Comment by noplay** [comment] 2016-06-30 07:10
I think it's an issue with recent raven version.

**Comment by nopower0** [comment] 2017-07-04 02:55
I still get this warning with the latest raven (6.1.0).

My DSN has "sync+" prefix to make sure the event can be sent successfully in a subprocess.

**Comment by AJNOURI** [comment] 2018-01-15 08:49
Looks like the issue is still present in v2.1.2 (Win10)

-----------

From the community forum:
https://gns3.com/discussions/gns3-2-1-2-upgrade-error-windows

> I've received the follow error after update to gns3 2.1.2.
> GNS3 error 
> => Error while getting compute list: Connection refused
> Local server process has stopped
> C:\Program Files\GNS3\python36.zip\raven\conf\remote.py:90: UserWarning: Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.

 
![image](https://user-images.githubusercontent.com/1716020/34934058-5a749926-f9d9-11e7-8f79-15dc603248ae.png)

**Comment by grossmj** [comment] 2018-01-15 09:57
Fixed in https://github.com/GNS3/gns3-gui/commit/a114d9ace7b2a32c2036288a520b2982815419e4 and https://github.com/GNS3/gns3-server/commit/30e8949985e60495cba9232f59da2b4f6fff807b

**Closed by grossmj** 2018-01-15 09:57 UTC
Labels: Bug
