### ISSUE TITLE
bug : 2.2 : "bad" symbol with template

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2671] opened 2019-01-14 19:33 UTC
Hi

I use the button "new template" and add the template "DNS" (with docker). I use the defaults values

The symbol of the device is linux_guest.svg, but i see classic.svg.

I must restart GNS3 to see the good symbol.

(I don't open a new issue, but i think the dialog box to create a new template too big : with LiveRaizo in VirtualBox with a screen of 1600x900, this dialog box is bigger than GNS3)

**Comment by grossmj** [comment] 2019-01-16 12:32
> I use the button "new template" and add the template "DNS" (with docker). I use the defaults values. The symbol of the device is linux_guest.svg, but i see classic.svg.

I couldn't reproduce the problem. Can you post a screenshot please?

Thanks!

**Comment by Raizo62** [comment] 2019-01-16 12:52
I believe that the bug occurs when i do it in VirtualBox (LiveRaizo is started in VirtualBox).

When i do it on a real PC, i have the good image which is "dockerguest_svg".

This late afternoon, i will retry in VirtualBox and i do a screenshot.

**Comment by Raizo62** [comment] 2019-01-16 13:12
Here a screenshot on a real PC. But, docker is configured to start when we use it : this may create a delay ?
![2019-01-16-153330_1280x1024_scrot](https://user-images.githubusercontent.com/7449584/51251087-b857dc80-1998-11e9-9e6d-8931a390fb08.png)

**Comment by grossmj** [comment] 2019-01-17 11:34
Thanks I can reproduce the problem now.

**Comment by grossmj** [comment] 2019-03-12 11:22
Fixed by https://github.com/GNS3/gns3-gui/pull/2732

**Closed by grossmj** 2019-03-12 11:22 UTC
Labels: Bug
