### ISSUE TITLE
Cannot connect to compute 'GNS3 VM (GNS3 VM)' with request POST /projects

### ISSUE THREAD

**Issue by mukul1251** [GNS3/gns3-gui#2982] opened 2020-05-05 16:09 UTC
**Describe the bug**
GNS3 starts fine but the GNS VM indicator does not turn green.
Works for the first time I use GNS VM after installation. As soon as I reboot the system, it doesn't work.
Also, I cannot ping the VM or connect it to ssh.

**GNS3 version and operating system (please complete the following information):**
Windows 10 Pro Version 1909 (OS Build 18363.778)
Running GNS3 version 2.2.7 on Windows (64-bit) with Python 3.6.8 Qt 5.12.1 and PyQt 5.12.
Copyright (c) 2006-2020 GNS3 Technologies.

**Any use of the GNS3 VM or remote server (ESXi, bare metal etc.)**
VMware-player-14.1.8-14921873

**To Reproduce**
Steps to reproduce the behaviour:
Start GNS3. Wait for GNS3 VM to be fully started. Click on GNS3 menu to open an existing project.

**Comment by jasontomasi** [comment] 2020-05-06 13:36
Duplicate of issue #2969

**Closed** 2020-05-08 02:19 UTC
Labels: Duplicate

**Comment by RP-11** [comment] 2020-05-09 19:52
Same here:
Running GNS3 2.2.8 on Linux Mint 19.3 , Kernel: 4.15.0-99-generic, and VMware 15.5.2

- GNS3 starts fine but the GNS VM indicator does not turn green.

GNS3 management console.
Running GNS3 version 2.2.8 on Linux (64-bit) with Python 3.6.9 Qt 5.11.2 and PyQt 5.11.3.
Copyright (c) 2006-2020 GNS3 Technologies.
Use Help -> GNS3 Doctor to detect common issues.

=> Cannot connect to compute 'GNS3 VM (GNS3 VM v2)' with request POST /projects

**Comment by mukul1251** [comment] 2020-05-10 12:28
@RP-11 
For me, it turns out some problem with GNS3 on VMware.
So, I tried with VirtualBox. 
So far, so good.
Give it a try.

**Comment by darkonos** [comment] 2020-05-21 13:24
Hello,
Cannot connect to compute 'GNS3 VM (GNS3 VM )' with request POST /projects
For me, with GNS3 2.2.8 and 2.2.7 impossible !
No problem with version GN3 2.2.5. Very good !
My configuration : 
- OS : Windows 10 pro  version 1909 
- Version OS : 18363.836
- VMware Workstation Pro 15.5.2
- Firewall windows : deactivate
- Antivirus : deactivate

**Comment by lmckiwo** [comment] 2021-07-07 11:55
Sorry, late to the party, but I hope this will help others.
I have the same problem, and can get around it by 
1. shutting down gns3
2. restart the vmnet interface that the GNS3 VM uses to connect
3. start gns3

Sometimes I have to do this a couple of times.  It is a bit of a pain, but once it is running, it works well.
Still searching for permanent solution.

**Comment by MRashad-MSR** [comment] 2025-02-02 05:09
@lmckiwo 
how to restart the vmnet interface that the GNS3 VM uses to connect
i has restart gns3 vm
