### ISSUE TITLE
[2.0] VMBox without disk

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1824] opened 2017-01-28 11:01 UTC
Hi

When we reload this project created by my student, the VMBox don't have disk (just controller SATA)

[SISR4-SMTP_backup_170126_09_2526.tar.xz.txt](https://github.com/GNS3/gns3-gui/files/736842/SISR4-SMTP_backup_170126_09_2526.tar.xz.txt)

**Comment by noplay** [comment] 2017-01-30 10:51
I didn't test on Live Raizo (as usual I'm short on disk space on my computer) but I think the base VM is not correct.

In /opt/raizo/user/OS/VBOX/VM/VMRaizo-Debian-Jessie-v20170120/VMRaizo-Debian-Jessie-v20170120.vbox

```xml
      <HardDisks>
        <HardDisk uuid="{7b8388d0-ec04-472a-8ff8-a5469079508a}" location="/opt/raizo/user/OS/VBOX/VDI/VM-Raizo.vdi" format="VDI" type="Normal">
          <HardDisk uuid="{5cd70067-6bcc-4976-b071-6cf6fe5798a0}" location="Snapshots/{5cd70067-6bcc-4976-b071-6cf6fe5798a0}.vdi" format="VDI"/>
          <HardDisk uuid="{f6b4a309-6498-47ab-988b-9bb258314af9}" location="/home/user/projects/untitled/project-files/virtualbox/83e23b9a-610f-4c60-b3b5-5ba66be455f3/Internet/Snapshots/{f6b4a309-6498-47ab-988b-9bb258314af9}.vdi" format="VDI">
            <HardDisk uuid="{263a2b6c-9205-4f13-858d-a02cb03cc901}" location="/home/user/projects/untitled/project-files/virtualbox/83e23b9a-610f-4c60-b3b5-5ba66be455f3/Internet/Snapshots/{263a2b6c-9205-4f13-858d-a02cb03cc901}.vdi" format="VDI"/>
          </HardDisk>
          <HardDisk uuid="{a69c565b-76ce-4e50-87b4-8f14c96fee1d}" location="/home/user/projects/untitled/project-files/virtualbox/b8922811-1cb2-441a-853e-bd01b98fdbdb/DNS/Snapshots/{a69c565b-76ce-4e50-87b4-8f14c96fee1d}.vdi" format="VDI">
            <HardDisk uuid="{73d4a04b-fab7-4f64-8e61-33ae0324387e}" location="/home/user/projects/untitled/project-files/virtualbox/b8922811-1cb2-441a-853e-bd01b98fdbdb/DNS/Snapshots/{73d4a04b-fab7-4f64-8e61-33ae0324387e}.vdi" format="VDI"/>
          </HardDisk>
          <HardDisk uuid="{2cbcff07-4ccc-42c2-816e-6634162b6fec}" location="/home/user/projects/untitled/project-files/virtualbox/bdd2e7e4-dd52-46c8-bc66-a5d1cd2e8e29/Client/Snapshots/{2cbcff07-4ccc-42c2-816e-6634162b6fec}.vdi" format="VDI">
            <HardDisk uuid="{750c12c6-0f93-4e98-8706-7911ec12dbe8}" location="/home/user/projects/untitled/project-files/virtualbox/bdd2e7e4-dd52-46c8-bc66-a5d1cd2e8e29/Client/Snapshots/{750c12c6-0f93-4e98-8706-7911ec12dbe8}.vdi" format="VDI"/>
          </HardDisk>
          <HardDisk uuid="{47b49130-15ad-40ab-b8e5-fa8054814f23}" location="/home/user/projects/untitled/project-files/virtualbox/dfc5265f-7405-4f1a-bddc-efb7e744540e/CFA/Snapshots/{47b49130-15ad-40ab-b8e5-fa8054814f23}.vdi" format="VDI">
            <HardDisk uuid="{7244bc64-3be9-4ac2-bffd-d02b91ca9808}" location="/home/user/projects/untitled/project-files/virtualbox/dfc5265f-7405-4f1a-bddc-efb7e744540e/CFA/Snapshots/{7244bc64-3be9-4ac2-bffd-d02b91ca9808}.vdi" format="VDI"/>
          </HardDisk>
          <HardDisk uuid="{9fa87667-07a1-4f74-b361-14d9f46896d8}" location="/home/user/projects/untitled/project-files/virtualbox/466309d0-444b-4d37-ab02-2886f583fb1d/Entreprise/Snapshots/{9fa87667-07a1-4f74-b361-14d9f46896d8}.vdi" format="VDI">
            <HardDisk uuid="{86cc5ab6-38d9-42c2-a7c5-3de64ff775b1}" location="/home/user/projects/untitled/project-files/virtualbox/466309d0-444b-4d37-ab02-2886f583fb1d/Entreprise/Snapshots/{86cc5ab6-38d9-42c2-a7c5-3de64ff775b1}.vdi" format="VDI"/>
          </HardDisk>
        </HardDisk>
      </HardDisks>
```
As you can see the base VM reference some file in /home/user/projects/untitled this mean if you don't have the /home/user/projects/untitled with the same files it will broke.

I close for the moment but don't hesitate to comment if you still have the issue.

**Comment by Raizo62** [comment] 2017-02-09 13:48
re

I believe that i know how to reproduce it.

- I have a lab with VMBox (and Cisco). His name : SMTP1
- I stop VMs and rename the lab to SMTP2
- I close GNS3
- With GNS3, i open SMTP2
- In VirtualBox, VM has controlleur but no disk

Sorry I didn't have try to test on simple lab. Then if you can not reproduce, i can send you an example lab.

**Comment by noplay** [comment] 2017-02-09 14:14
How do you rename?

**Comment by Raizo62** [comment] 2017-02-09 14:24
Sorry, i had corrected my post but not fast enough ....

I use "save project as" of GNS3

**Comment by noplay** [comment] 2017-02-13 18:16
I tested and the problem is VirtualBox detect the duplicate of the disk and delete it :( I pushed a fix I hope it's enough.

**Comment by Raizo62** [comment] 2017-02-13 22:40
Sorry. I tested and i believe that doesn't work :-(

**Comment by noplay** [comment] 2017-02-14 08:08
You don't the disk or data are not correctly load?

**Comment by Raizo62** [comment] 2017-02-14 09:08
When i rename the project, i have a good disk (i can start the VM).
But, after rename, if i close the project, and reload it, the VM doesn't have disk (Virtualbox interface shows controlleur but not disk)

**Comment by noplay** [comment] 2017-02-14 11:38
Ok VirtualBox seem to keep references somewhere and is confused by our rewrite. I will rollback to the behavior where you can't use linked clone virtualbox and save as. It's clearly not designed to be use like that.

**Comment by Raizo62** [comment] 2017-02-14 12:40
After to rename the project and before to close GNS3,
- VirtualBox show to VM with the same name
- The "Virtual Media manager" of VirtualBox interface shows that the disk (snapshot) are always in the first directory (first name)

**Comment by noplay** [comment] 2017-02-14 15:48
This normal behavior until the project is cleaned by the GNS3 server you will see two VM with the same name in VirtualBox.

The fact the virtual media manager doesn't update, seem to indicate that VirtualBox keep a database somewhere.

The correct way to implement it is probably asking VirtualBox to do the duplicate, but we will not do it because for all other emulator we can just copy file and adding this will make the architecture more complex.

Now we prevent save as working when using a linked clone this will avoid corrupting data.

**Closed by noplay** 2017-02-14 15:48 UTC
Labels: bug

**Comment by Raizo62** [comment] 2017-02-14 18:18
Do you change UUID of "new" disk for VirtualBox ? (do you need to do it? )
