### ISSUE TITLE
save projects removes modified device links

### ISSUE THREAD

**Issue by taurus8** [GNS3/gns3-gui#992] opened 2016-02-04 11:39 UTC
Hi
i have 1.4.2 dev1 in ubuntu

 i delete IOU Router startup-configs by del in terminal and add new configs and save configs by cop run star and copy run unix:star... .cfg every things  is ok
but when i save the changes project and re open it  that device links is disappearing 
 in following picture i have deleted R4 iou router configs and added new one  then saved inital configs
and project  but after opening it again my device links disappears  
![links](https://cloud.githubusercontent.com/assets/8465075/12813999/ef204296-cb50-11e5-9d1e-c4df48d0b379.png)

**Comment by noplay** [comment] 2016-02-04 12:53
Sorry I'm confused. I reformat your post
* i delete IOU Router startup-configs by del in terminal
* add new configs
* save configs by cop run star and copy run unix:star... .cfg

Every things is ok
* when i save the changes project and re open it
* that device links is disappearing 

in following picture i have deleted R4 iou router configs and added new one then saved inital configs
and project but after opening it again my device links disappears

**Comment by taurus8** [comment] 2016-02-04 13:02
:)
in R4 Termianl 

del nvram:startup-config
del unix:startup-config.cfg

stop R4
start R4

add new configs 

copy running-config startup-config
copy running-config unix:startup-config.cfg

save project

open that project again and no links 

i dnot have that issue in 1.4.1  :)

**Comment by noplay** [comment] 2016-02-04 13:24
I didn't manage to reproduce it. Which config are you changing? You have the trouble with any topologies?

Are you sure at 100% it's work with 1.4.1? Because we didn't change anything to IOU and I don't see what could have a side effect.

Thanks for the help

**Comment by taurus8** [comment] 2016-02-04 13:36
i have my full working topology with all device configs {start-up configs}
then 
i delete my R4 router start-up configs by del in terminal 
and add new initial configs and save it to start-up configs
then i save my project.
when i open that saved  project R4 links disappears

so strange
i have just come back to 1.4.1 and i did the same process ,but did not have any issue.

**Comment by taurus8** [comment] 2016-02-04 13:54
i have one topology with saved startup-configs named LAB
open LAB
save projects as LAB 1
start R4

del nvram:startup-config
del unix:startup-config.cfg

stop R4
start R4

now every things is empty no configs
add new initial configs 

copy running-config startup-config
copy running-config unix:startup-config.cfg

save project

open that project again  LAB 1 and no links

**Comment by noplay** [comment] 2016-02-04 14:34
Since you Save as a project using IOU. I deduce you are under Linux and run IOU outside the GNS3 VM.

For both test you are using GNS3 1.4.1 and 1.4.2dev1 with same install process on the same computer?

**Comment by taurus8** [comment] 2016-02-04 14:43
yes Sir
same PC i have bare metal Ubuntu x64 15.10
Running GNS3 version 1.4.1 on Linux (64-bit) with Python 3.5.0+ Qt 5.4.2.

**Comment by noplay** [comment] 2016-02-04 14:46
Both install from Git?

**Comment by taurus8** [comment] 2016-02-04 14:46
yes

**Comment by taurus8** [comment] 2016-02-04 14:48
my first LAB was created under 1.4

**Comment by taurus8** [comment] 2016-02-06 10:23
so strange 
i open my project created {under 1.4.1 } in 1.4.2 dev1
start device {client1}
stop device {client1}
save project
re open it again
client1 connections disappears 

i receive following error in terminal

 2016-02-06 13:44:19 ERROR topology.py:895 Corrupted topology Link from Client1 port Ethernet0/1 to ASW1 port Ethernet0/1 source port doesn't exist

**Comment by taurus8** [comment] 2016-02-08 07:04
![error](https://cloud.githubusercontent.com/assets/8465075/12879920/82712190-ce4f-11e5-89e2-3aabe33d17b8.png)

**Comment by noplay** [comment] 2016-02-08 09:09
Can you share the .gns3 content? (You can open a gist with it or paste it here)

**Comment by taurus8** [comment] 2016-02-08 09:31
Sure
i have created new topology named my lab in 1.4.2.dev with 3 iou Routers 
following is my terminal error 
![error 2](https://cloud.githubusercontent.com/assets/8465075/12882042/ed17e0ce-ce63-11e5-9f61-6e9f4bb131cf.png)

**Comment by taurus8** [comment] 2016-02-08 09:32
this one is my lab.gns3 contents

{
    "auto_start": false,
    "name": "my lab",
    "project_id": "17730529-96cb-4b42-92d2-fa8588ab1e84",
    "revision": 4,
    "topology": {
        "links": [
            {
                "description": "Link from IOU3 port Ethernet0/1 to IOU2 port Ethernet0/1",
                "destination_node_id": 2,
                "destination_port_id": 18,
                "id": 1,
                "source_node_id": 3,
                "source_port_id": 34
            },
            {
                "description": "Link from IOU1 port Ethernet0/0 to IOU2 port Ethernet0/0",
                "destination_node_id": 2,
                "destination_port_id": 17,
                "id": 2,
                "source_node_id": 1,
                "source_port_id": 1
            },
            {
                "description": "Link from IOU1 port Ethernet0/1 to IOU3 port Ethernet0/0",
                "destination_node_id": 3,
                "destination_port_id": 33,
                "id": 3,
                "source_node_id": 1,
                "source_port_id": 2
            }
        ],
        "nodes": [
            {
                "description": "IOU device",
                "id": 1,
                "label": {
                    "color": "#ff000000",
                    "font": "Ubuntu,10,-1,5,50,1,0,0,0,0",
                    "text": "IOU1",
                    "x": 5.625,
                    "y": -25.0
                },
                "ports": [
                    {
                        "adapter_number": 0,
                        "description": "connected to IOU2 on port Ethernet0/0",
                        "id": 1,
                        "link_id": 2,
                        "name": "Ethernet0/0",
                        "nio": "NIO_UDP",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 0,
                        "description": "connected to IOU3 on port Ethernet0/0",
                        "id": 2,
                        "link_id": 3,
                        "name": "Ethernet0/1",
                        "nio": "NIO_UDP",
                        "port_number": 1
                    },
                    {
                        "adapter_number": 0,
                        "id": 3,
                        "name": "Ethernet0/2",
                        "port_number": 2
                    },
                    {
                        "adapter_number": 0,
                        "id": 4,
                        "name": "Ethernet0/3",
                        "port_number": 3
                    },
                    {
                        "adapter_number": 1,
                        "id": 5,
                        "name": "Ethernet1/0",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 1,
                        "id": 6,
                        "name": "Ethernet1/1",
                        "port_number": 1
                    },
                    {
                        "adapter_number": 1,
                        "id": 7,
                        "name": "Ethernet1/2",
                        "port_number": 2
                    },
                    {
                        "adapter_number": 1,
                        "id": 8,
                        "name": "Ethernet1/3",
                        "port_number": 3
                    },
                    {
                        "adapter_number": 2,
                        "id": 9,
                        "name": "Serial2/0",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 2,
                        "id": 10,
                        "name": "Serial2/1",
                        "port_number": 1
                    },
                    {
                        "adapter_number": 2,
                        "id": 11,
                        "name": "Serial2/2",
                        "port_number": 2
                    },
                    {
                        "adapter_number": 2,
                        "id": 12,
                        "name": "Serial2/3",
                        "port_number": 3
                    },
                    {
                        "adapter_number": 3,
                        "id": 13,
                        "name": "Serial3/0",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 3,
                        "id": 14,
                        "name": "Serial3/1",
                        "port_number": 1
                    },
                    {
                        "adapter_number": 3,
                        "id": 15,
                        "name": "Serial3/2",
                        "port_number": 2
                    },
                    {
                        "adapter_number": 3,
                        "id": 16,
                        "name": "Serial3/3",
                        "port_number": 3
                    },
                    {
                        "adapter_number": 0,
                        "id": 65,
                        "name": "Ethernet0/0",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 0,
                        "id": 66,
                        "name": "Ethernet0/1",
                        "port_number": 1
                    },
                    {
                        "adapter_number": 0,
                        "id": 67,
                        "name": "Ethernet0/2",
                        "port_number": 2
                    },
                    {
                        "adapter_number": 0,
                        "id": 68,
                        "name": "Ethernet0/3",
                        "port_number": 3
                    },
                    {
                        "adapter_number": 1,
                        "id": 69,
                        "name": "Ethernet1/0",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 1,
                        "id": 70,
                        "name": "Ethernet1/1",
                        "port_number": 1
                    },
                    {
                        "adapter_number": 1,
                        "id": 71,
                        "name": "Ethernet1/2",
                        "port_number": 2
                    },
                    {
                        "adapter_number": 1,
                        "id": 72,
                        "name": "Ethernet1/3",
                        "port_number": 3
                    },
                    {
                        "adapter_number": 2,
                        "id": 73,
                        "name": "Serial2/0",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 2,
                        "id": 74,
                        "name": "Serial2/1",
                        "port_number": 1
                    },
                    {
                        "adapter_number": 2,
                        "id": 75,
                        "name": "Serial2/2",
                        "port_number": 2
                    },
                    {
                        "adapter_number": 2,
                        "id": 76,
                        "name": "Serial2/3",
                        "port_number": 3
                    },
                    {
                        "adapter_number": 3,
                        "id": 77,
                        "name": "Serial3/0",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 3,
                        "id": 78,
                        "name": "Serial3/1",
                        "port_number": 1
                    },
                    {
                        "adapter_number": 3,
                        "id": 79,
                        "name": "Serial3/2",
                        "port_number": 2
                    },
                    {
                        "adapter_number": 3,
                        "id": 80,
                        "name": "Serial3/3",
                        "port_number": 3
                    }
                ],
                "properties": {
                    "console": 2001,
                    "ethernet_adapters": 2,
                    "l1_keepalives": false,
                    "md5sum": "a3a45f36df542b7d3988391a12b2d980",
                    "name": "IOU1",
                    "nvram": 128,
                    "path": "i86bi-linux-l3-adventerprisek9-15.4.2T4.bin",
                    "ram": 256,
                    "serial_adapters": 2,
                    "startup_config": "startup-config.cfg",
                    "use_default_iou_values": true
                },
                "server_id": 1,
                "symbol": "router.svg",
                "type": "IOUDevice",
                "vm_id": "d8b2439d-60db-4167-9d4d-c156cd040b29",
                "x": -360.0,
                "y": -142.5
            },
            {
                "description": "IOU device",
                "id": 2,
                "label": {
                    "color": "#ff000000",
                    "font": "Ubuntu,10,-1,5,50,1,0,0,0,0",
                    "text": "IOU2",
                    "x": 5.125,
                    "y": -25.0
                },
                "ports": [
                    {
                        "adapter_number": 0,
                        "description": "connected to IOU1 on port Ethernet0/0",
                        "id": 17,
                        "link_id": 2,
                        "name": "Ethernet0/0",
                        "nio": "NIO_UDP",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 0,
                        "description": "connected to IOU3 on port Ethernet0/1",
                        "id": 18,
                        "link_id": 1,
                        "name": "Ethernet0/1",
                        "nio": "NIO_UDP",
                        "port_number": 1
                    },
                    {
                        "adapter_number": 0,
                        "id": 19,
                        "name": "Ethernet0/2",
                        "port_number": 2
                    },
                    {
                        "adapter_number": 0,
                        "id": 20,
                        "name": "Ethernet0/3",
                        "port_number": 3
                    },
                    {
                        "adapter_number": 1,
                        "id": 21,
                        "name": "Ethernet1/0",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 1,
                        "id": 22,
                        "name": "Ethernet1/1",
                        "port_number": 1
                    },
                    {
                        "adapter_number": 1,
                        "id": 23,
                        "name": "Ethernet1/2",
                        "port_number": 2
                    },
                    {
                        "adapter_number": 1,
                        "id": 24,
                        "name": "Ethernet1/3",
                        "port_number": 3
                    },
                    {
                        "adapter_number": 2,
                        "id": 25,
                        "name": "Serial2/0",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 2,
                        "id": 26,
                        "name": "Serial2/1",
                        "port_number": 1
                    },
                    {
                        "adapter_number": 2,
                        "id": 27,
                        "name": "Serial2/2",
                        "port_number": 2
                    },
                    {
                        "adapter_number": 2,
                        "id": 28,
                        "name": "Serial2/3",
                        "port_number": 3
                    },
                    {
                        "adapter_number": 3,
                        "id": 29,
                        "name": "Serial3/0",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 3,
                        "id": 30,
                        "name": "Serial3/1",
                        "port_number": 1
                    },
                    {
                        "adapter_number": 3,
                        "id": 31,
                        "name": "Serial3/2",
                        "port_number": 2
                    },
                    {
                        "adapter_number": 3,
                        "id": 32,
                        "name": "Serial3/3",
                        "port_number": 3
                    },
                    {
                        "adapter_number": 0,
                        "id": 97,
                        "name": "Ethernet0/0",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 0,
                        "id": 98,
                        "name": "Ethernet0/1",
                        "port_number": 1
                    },
                    {
                        "adapter_number": 0,
                        "id": 99,
                        "name": "Ethernet0/2",
                        "port_number": 2
                    },
                    {
                        "adapter_number": 0,
                        "id": 100,
                        "name": "Ethernet0/3",
                        "port_number": 3
                    },
                    {
                        "adapter_number": 1,
                        "id": 101,
                        "name": "Ethernet1/0",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 1,
                        "id": 102,
                        "name": "Ethernet1/1",
                        "port_number": 1
                    },
                    {
                        "adapter_number": 1,
                        "id": 103,
                        "name": "Ethernet1/2",
                        "port_number": 2
                    },
                    {
                        "adapter_number": 1,
                        "id": 104,
                        "name": "Ethernet1/3",
                        "port_number": 3
                    },
                    {
                        "adapter_number": 2,
                        "id": 105,
                        "name": "Serial2/0",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 2,
                        "id": 106,
                        "name": "Serial2/1",
                        "port_number": 1
                    },
                    {
                        "adapter_number": 2,
                        "id": 107,
                        "name": "Serial2/2",
                        "port_number": 2
                    },
                    {
                        "adapter_number": 2,
                        "id": 108,
                        "name": "Serial2/3",
                        "port_number": 3
                    },
                    {
                        "adapter_number": 3,
                        "id": 109,
                        "name": "Serial3/0",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 3,
                        "id": 110,
                        "name": "Serial3/1",
                        "port_number": 1
                    },
                    {
                        "adapter_number": 3,
                        "id": 111,
                        "name": "Serial3/2",
                        "port_number": 2
                    },
                    {
                        "adapter_number": 3,
                        "id": 112,
                        "name": "Serial3/3",
                        "port_number": 3
                    }
                ],
                "properties": {
                    "console": 2002,
                    "ethernet_adapters": 2,
                    "l1_keepalives": false,
                    "md5sum": "a3a45f36df542b7d3988391a12b2d980",
                    "name": "IOU2",
                    "nvram": 128,
                    "path": "i86bi-linux-l3-adventerprisek9-15.4.2T4.bin",
                    "ram": 256,
                    "serial_adapters": 2,
                    "startup_config": "startup-config.cfg",
                    "use_default_iou_values": true
                },
                "server_id": 1,
                "symbol": "router.svg",
                "type": "IOUDevice",
                "vm_id": "a4974dae-476d-44c9-9513-59599c18b734",
                "x": -138.0,
                "y": -144.5
            },
            {
                "description": "IOU device",
                "id": 3,
                "label": {
                    "color": "#ff000000",
                    "font": "Ubuntu,10,-1,5,50,1,0,0,0,0",
                    "text": "IOU3",
                    "x": 5.625,
                    "y": -25.0
                },
                "ports": [
                    {
                        "adapter_number": 0,
                        "description": "connected to IOU1 on port Ethernet0/1",
                        "id": 33,
                        "link_id": 3,
                        "name": "Ethernet0/0",
                        "nio": "NIO_UDP",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 0,
                        "description": "connected to IOU2 on port Ethernet0/1",
                        "id": 34,
                        "link_id": 1,
                        "name": "Ethernet0/1",
                        "nio": "NIO_UDP",
                        "port_number": 1
                    },
                    {
                        "adapter_number": 0,
                        "id": 35,
                        "name": "Ethernet0/2",
                        "port_number": 2
                    },
                    {
                        "adapter_number": 0,
                        "id": 36,
                        "name": "Ethernet0/3",
                        "port_number": 3
                    },
                    {
                        "adapter_number": 1,
                        "id": 37,
                        "name": "Ethernet1/0",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 1,
                        "id": 38,
                        "name": "Ethernet1/1",
                        "port_number": 1
                    },
                    {
                        "adapter_number": 1,
                        "id": 39,
                        "name": "Ethernet1/2",
                        "port_number": 2
                    },
                    {
                        "adapter_number": 1,
                        "id": 40,
                        "name": "Ethernet1/3",
                        "port_number": 3
                    },
                    {
                        "adapter_number": 2,
                        "id": 41,
                        "name": "Serial2/0",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 2,
                        "id": 42,
                        "name": "Serial2/1",
                        "port_number": 1
                    },
                    {
                        "adapter_number": 2,
                        "id": 43,
                        "name": "Serial2/2",
                        "port_number": 2
                    },
                    {
                        "adapter_number": 2,
                        "id": 44,
                        "name": "Serial2/3",
                        "port_number": 3
                    },
                    {
                        "adapter_number": 3,
                        "id": 45,
                        "name": "Serial3/0",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 3,
                        "id": 46,
                        "name": "Serial3/1",
                        "port_number": 1
                    },
                    {
                        "adapter_number": 3,
                        "id": 47,
                        "name": "Serial3/2",
                        "port_number": 2
                    },
                    {
                        "adapter_number": 3,
                        "id": 48,
                        "name": "Serial3/3",
                        "port_number": 3
                    },
                    {
                        "adapter_number": 0,
                        "id": 81,
                        "name": "Ethernet0/0",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 0,
                        "id": 82,
                        "name": "Ethernet0/1",
                        "port_number": 1
                    },
                    {
                        "adapter_number": 0,
                        "id": 83,
                        "name": "Ethernet0/2",
                        "port_number": 2
                    },
                    {
                        "adapter_number": 0,
                        "id": 84,
                        "name": "Ethernet0/3",
                        "port_number": 3
                    },
                    {
                        "adapter_number": 1,
                        "id": 85,
                        "name": "Ethernet1/0",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 1,
                        "id": 86,
                        "name": "Ethernet1/1",
                        "port_number": 1
                    },
                    {
                        "adapter_number": 1,
                        "id": 87,
                        "name": "Ethernet1/2",
                        "port_number": 2
                    },
                    {
                        "adapter_number": 1,
                        "id": 88,
                        "name": "Ethernet1/3",
                        "port_number": 3
                    },
                    {
                        "adapter_number": 2,
                        "id": 89,
                        "name": "Serial2/0",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 2,
                        "id": 90,
                        "name": "Serial2/1",
                        "port_number": 1
                    },
                    {
                        "adapter_number": 2,
                        "id": 91,
                        "name": "Serial2/2",
                        "port_number": 2
                    },
                    {
                        "adapter_number": 2,
                        "id": 92,
                        "name": "Serial2/3",
                        "port_number": 3
                    },
                    {
                        "adapter_number": 3,
                        "id": 93,
                        "name": "Serial3/0",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 3,
                        "id": 94,
                        "name": "Serial3/1",
                        "port_number": 1
                    },
                    {
                        "adapter_number": 3,
                        "id": 95,
                        "name": "Serial3/2",
                        "port_number": 2
                    },
                    {
                        "adapter_number": 3,
                        "id": 96,
                        "name": "Serial3/3",
                        "port_number": 3
                    }
                ],
                "properties": {
                    "console": 2003,
                    "ethernet_adapters": 2,
                    "l1_keepalives": false,
                    "md5sum": "a3a45f36df542b7d3988391a12b2d980",
                    "name": "IOU3",
                    "nvram": 128,
                    "path": "i86bi-linux-l3-adventerprisek9-15.4.2T4.bin",
                    "ram": 256,
                    "serial_adapters": 2,
                    "startup_config": "startup-config.cfg",
                    "use_default_iou_values": true
                },
                "server_id": 1,
                "symbol": "router.svg",
                "type": "IOUDevice",
                "vm_id": "9236a43c-a5ea-4bd7-b5e9-3506fbb88793",
                "x": -234.0,
                "y": -40.5
            }
        ],
        "servers": [
            {
                "host": "127.0.0.1",
                "id": 1,
                "local": true,
                "port": 8000,
                "protocol": "http",
                "ram_limit": 0,
                "vm": false
            }
        ]
    },
    "type": "topology",
    "version": "1.4.2dev1"
}

**Comment by taurus8** [comment] 2016-02-08 09:40
when i start iou devices and stop
then save the project my iou device links is being removed

**Comment by noplay** [comment] 2016-02-08 10:25
Thanks I edited it to add syntaxic coloration

**Comment by noplay** [comment] 2016-02-08 13:56
Ok the file is corrupted. We have twice the Ethernet0/0. Now I need to find why the adapter is duplicate

**Comment by noplay** [comment] 2016-02-08 16:23
Can you try with the branch detect_corrupt_port_name it should auto fix the issue at load. And warn when the error appear at save. 

At this time I don't understand when the corruption appear :(

**Comment by noplay** [comment] 2016-02-08 16:23
Thanks for the help

**Comment by taurus8** [comment] 2016-02-08 18:25
Thanks Sir
It has been fixed now
everything is working perfect now
thx

**Comment by taurus8** [comment] 2016-02-08 18:27
i have no problem with save as project too thx

**Comment by taurus8** [comment] 2016-02-10 07:33
topology summary is not working normal
before start
![before start](https://cloud.githubusercontent.com/assets/8465075/12941256/da5324f2-cfe5-11e5-8a61-f6a3ef67e790.png)
after start
![after start](https://cloud.githubusercontent.com/assets/8465075/12941263/e8319fae-cfe5-11e5-86d2-1661a2d88456.png)

**Comment by taurus8** [comment] 2016-02-10 08:00
QEMU VM   has the same  , but not Dynamips

**Comment by taurus8** [comment] 2016-02-10 08:13
One more issue is that when i point my mouse on started IOU device it shows double the interfaces  but when i drag link on IOU device it show normal interfaces .
![dup](https://cloud.githubusercontent.com/assets/8465075/12941830/76b1d294-cfeb-11e5-8160-e3fc4615c9ac.png)

**Comment by noplay** [comment] 2016-02-10 10:15
Should be fixed thanks for the report

**Closed** 2016-02-10 10:14 UTC
Labels: bug
