### ISSUE TITLE
[2.0.0b4] Using NAT node to connect GNS3 to the Internet issue

### ISSUE THREAD

**Issue by KeVI121** [GNS3/gns3-gui#1896] opened 2017-03-02 00:50 UTC
I cannot ping any sites when using NAT node to connect GNS3 to the internet. I get a DHCP address in the 192.168.122.x subnet but cannot ping www.google.com or any other.  I saw lab where this works so not sure if it my machine/gns3 setup or even service provider.

**Comment by jtorri** [comment] 2017-03-02 03:12
Windows 10 Prof x64 also using GNS3 2.0.0b4
Using the NAT interface on the GNS3 VM (eth1) I am able to ping www.google.com.  The NAT interface I am using is the default VMWare NAT vmnet8 with IP 192.168.116.0/24 gateway IP 192.168.116.2.  The IOUL2 interface has static IP of 192.168.166.200/24.  Default route 192.168.116.2 and name server 8.8.8.8.
Hope this helps.

**Comment by noplay** [comment] 2017-03-02 07:35
How your GNS3 is installed? You use the GNS3 VM?

**Comment by KeVI121** [comment] 2017-03-02 18:21
GNS3 v2.0 beta 4 on 64 bit Windows 7 machine. My GNS3 VM is installed on
VMWare workstation 12.

On Thu, Mar 2, 2017 at 2:35 AM, Julien Duponchelle <notifications@github.com

**Comment by KeVI121** [comment] 2017-03-02 23:50
I am using Windows 7 x64 and also using 2.0 0 b4. I am not able to select
vmnet8 as option. Can you send me screens shots on how u have this setup?

**Comment by jtorri** [comment] 2017-03-03 02:34
GNS3 comes with a command file, vmnet-manager.cmd, located in the folder into which GNS3 application was installed, e.g., c:\program files\GNS3 2.0.0b4\
If you open a DOS prompt as Windows administrator and run vmnet-manager.cmd it will add additional vmnet interfaces to VMware Workstation.  One of those will be vmnet8 as NAT.  
As you know, you can via the VMWare Workstation network editor decide yourself which vmnet interface you wish to be NAT.  
Also, when you "create" the GNS3 VM in VMware Workstation you have the opinion, as with any virtual machine, to add/edit or delete virtual NICs.  The default for GNS3 VM is eth0 is host only and eth1 is NAT.  You can add a third virtual NIC, eth2, as bridged mode if you like.
Hope this helps.

**Comment by KeVI121** [comment] 2017-03-03 04:41
It already has vmnet8 as NAT but in subnet 192.168.193.0. My router is a
dhcp ip address from the NAT node in subnet 192.168.122.0 and think that is
why I am having the issue. Also, only one interface can NAT which vmnet8 is
NAT. I am knew to this so not sure what to do.

**Comment by joelazaro** [comment] 2017-03-03 05:50
KeVI121, I am not able to reproduce your problem. I'm using GNS3 v2.0 beta 4 on 64 bit Windows 10, with the GNS3 VM is installed on VMWare workstation 12.5.

To create the test I added a NAT node and a VPCS node to my topology.
![topology](https://cloud.githubusercontent.com/assets/25847784/23539661/95f69b22-ff91-11e6-8e61-22625705696a.PNG)

I then logged into the PC and acquired an address via DHCP and was able to ping internet addresses with no problem.

`PC4> ip dhcp
DDORA IP 192.168.122.10/24 GW 192.168.122.1

PC4> ping 8.8.8.8
84 bytes from 8.8.8.8 icmp_seq=1 ttl=127 time=16.301 ms
84 bytes from 8.8.8.8 icmp_seq=2 ttl=127 time=17.954 ms
84 bytes from 8.8.8.8 icmp_seq=3 ttl=127 time=18.485 ms
84 bytes from 8.8.8.8 icmp_seq=4 ttl=127 time=15.060 ms
84 bytes from 8.8.8.8 icmp_seq=5 ttl=127 time=14.050 ms

PC4> ping www.google.com
www.google.com resolved to 216.58.216.132
84 bytes from 216.58.216.132 icmp_seq=1 ttl=127 time=28.022 ms
84 bytes from 216.58.216.132 icmp_seq=2 ttl=127 time=27.758 ms
84 bytes from 216.58.216.132 icmp_seq=3 ttl=127 time=29.507 ms
84 bytes from 216.58.216.132 icmp_seq=4 ttl=127 time=28.445 ms
84 bytes from 216.58.216.132 icmp_seq=5 ttl=127 time=50.120 ms

PC4>`

As you can see, it was successful. In VMware, I have not changed the default network adapters that are created in the GNS3 VM. I have only added a third network interface, but that has no effect on this test.
![image](https://cloud.githubusercontent.com/assets/25847784/23539727/fdc0cf02-ff91-11e6-8f85-f2ff5fec9a2a.png)

I suggest that you try the same experiment. If it works, then maybe there is a problem with your IOUL2 configuration.

- Joe

**Comment by jtorri** [comment] 2017-03-03 13:19
KeVI121
Yep it can be confusing.  Can you post a screen shot of your topology?  The specific IP of the NAT interface is not important.  What is important is the gateway IP of the NAT interface and the configuration of the interface on the network object from which you are trying to ping.  You can use the VMWare Workstation network editor to determine the gateway IP of your VMWare Workstation's NAT vmnet.  Then use that information to configure the interface of your network object's, e.g,, router, appropriate default route,  Then configure a name-server and, ip domain-lookup, of course.  If you are using a virtual machine, e.g., Lubuntu, from which to ping there may be another issue.
Hope this helps!

**Comment by KeVI121** [comment] 2017-03-04 03:38
Joe,

thanks for showing me your VM settings. The issue was I only had one
Network Adapter. Once i added Network Adapter 2 as NAT interface now i can
ping google and cisco. I tried with VPCS like you did in your topology but
i will also try with router.

Once again, thank you much!!

KevA

**Comment by KeVI121** [comment] 2017-03-04 03:43
jtorri,

I figured out the issue. My VM settings only had one Network Adapter (Host
Only). I added a 2nd Network adapter as NAT now i can ping. I didn't
checked the Virtual Network Editor settings and saw there was a NAT
interface there so I assumed there would be NAT adapter in the VM settings.

My topology was simple really, a VPCS or router connected to the NAT Node.

I appreciate the help and feedback though!! Thanks!!

**Comment by jtorri** [comment] 2017-03-04 21:07
KeVI121
Clearly I need to ask a few more questions before offering advice! :)  I did not even consider you might be using the NAT object or VPCS.  Like you, glad it's all solved!

**Comment by noplay** [comment] 2017-03-08 08:35
It seem solve, I close the issue thanks everyone.

**Closed by noplay** 2017-03-08 08:35 UTC
Labels: bug

**Comment by souravns92** [comment] 2019-09-14 19:03
Hii.. I am getting a typical error of  -  _Error while creating node: Internal server error http://127.0.0.1:3080/v2/compute/projects/348eb69d-9070-4837-a7de-f62d26d55ff9/nat/nodes_
while adding NAT in GNS3. Request help please.
