### ISSUE TITLE
NotADirectoryError: [WinError 267] The directory name is invalid

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#562] opened 2015-07-22 05:14 UTC
https://app.getsentry.com/gns3/gns3-gui/group/72574681/

```
NotADirectoryError: [WinError 267] The directory name is invalid
  File "./gns3-gui\gns3\modules\qemu\dialogs\qemu_image_wizard.py", line 238, in _createDisk
  File "C:\Python343-64bit\lib\subprocess.py", line 859, in __init__
  File "C:\Python343-64bit\lib\subprocess.py", line 1112, in _execute_child
```

**Comment by noplay** [comment] 2015-07-27 12:43
Duplicate of #569

**Closed by noplay** 2015-07-27 12:43 UTC
Labels: bug
