### ISSUE TITLE
Add Reconnect option.

### ISSUE THREAD

**Issue by syndgr** [GNS3/gns3-gui#2105] opened 2017-06-13 10:37 UTC
Using a laptop, the laptop may go to sleep or lose network connectivity when roaming, GNS3 client can get disconnected from GNS3 server (remote or GNS3 VM) and stops trying to reconnect.

Implement a "Reconnect" menu option/toolbar button/management console command so the GUI does not need to be closed and re-opened. This is particularly painful if using the GNS3 VM and the GUI preference action is set to "stop the GNS3 VM" because you have to wait for the GNS3 VM to stop and start again for no reason.

**Comment by noplay** [comment] 2017-06-13 14:57
On which OS are you? Reconnect should be automatic.

**Comment by noplay** [comment] 2017-06-13 14:58
Could be the same API as https://github.com/GNS3/gns3-gui/issues/2104

**Comment by syndgr** [comment] 2017-06-13 17:34
@noplay Sorry that the information was poor. Let me do some more experimenting and report back. I only noticed it today when I went in to a meeting and my laptop went to sleep. I was using GNS3 VM and GUI all on my laptop and had a project open and running. After waking my laptop up I saw in the console that it wasn't able to connect and I had to close GUI (which then stopped the GNS3 VM), although I did confirm that my host could connect to the GNS3 VM. It just seemed as though the GUI gave up.

**Comment by noplay** [comment] 2017-06-14 09:34
Are you on Linux?

**Comment by noplay** [comment] 2017-06-14 09:35
We got similar report by Linux users

**Comment by noplay** [comment] 2017-07-17 07:35
Duplicate of #2104 we will try to solve hibernation issues in 2.1

**Closed by noplay** 2017-07-17 07:35 UTC
Labels: Enhancement
