### ISSUE TITLE
When the User field defined by docker images is ID, the image cannot run

### ISSUE THREAD

**Issue by zccing** [GNS3/gns3-gui#3411] opened 2022-12-08 05:06 UTC
**Describe the bug**
When the User field defined by docker images is ID, the image cannot run
![image](https://user-images.githubusercontent.com/35253469/206360501-efd502f4-d0c8-4f29-b386-f00b817ecdce.png)

**GNS3 version and operating system (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - GNS3 version 2.2.35.1
 - bare metal

Try to modify“ https://github.com/GNS3/gns3-server/blob/master/gns3server/compute/docker/resources/init.sh "After the file, the image can be started normally

![image](https://user-images.githubusercontent.com/35253469/206361024-64217a2d-089c-4b34-baea-496afde28e69.png)

**Comment by grossmj** [comment] 2022-12-28 01:36
Duplicate of https://github.com/GNS3/gns3-server/issues/2134

**Closed by grossmj** 2022-12-28 01:36 UTC
Labels: Bug
